### ISSUE TITLE
Telegram group

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Accessibility#1]
_From @zvili on November 16, 2016 17:56_

_Copied from original issue: TechnionYP5777/SmartCity-ParkingManagement-A#1_

**Comment by zvili** [comment]
- Please define a Telegram group
- Send us your chosen users in Telegram
- Choose a group leader and share with us her/his user name.

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-ParkingManagement-B#2

**Comment by zvili** [comment]
This issue was moved to TechnionYP5777/SmartCity-Accessibility-A#1

**Comment by kapalex** [comment]
https://telegram.me/KaplanAlexander

**Comment by Kolikant** [comment]
https://telegram.me/Kolikant

**Comment by yaelAmitay** [comment]
https://telegram.me/yaelAmitay

**Comment by assaflu** [comment]
https://telegram.me/AssafLustig

**Comment by kapalex** [comment]
< Group leader

**Comment by ArthurSap** [comment]
https://telegram.me/ArthurSap

**Comment by koralchapnik** [comment]
https://telegram.me/skoralch

**Comment by idabran** [comment]
How come this issue is still open #6 karma--

**Comment by idabran** [comment]
@KaplanAlexander as group leader you should have assigned yourself or some of us 👎

**Comment by yossigil** [comment]
:+1:
