### ISSUE TITLE
Handling unauthorized access.

### ISSUE THREAD

**Issue by ArthurSap** [TechnionYP5777/SmartCity-Accessibility#104]
How should we handle unauthorized access?
e,g in Location's newly added pin and unpin methods, if a user that doesn't have the authorization level (i.e User.privilege >= RegularUserPrivilege) tries to activate those methods - should we return (and maybe print a message) or throw a custom exception?
@Kolikant @KaplanAlexander

**Comment by Kolikant** [comment]
the gui should present buttons for autheriz requiring methods, but just in case, printing a message "unautherised" would do

**Comment by ArthurSap** [comment]
So no need to throw exception yes?
Regarding pin and unpin methods - what if we're trying to (un)pin an already (un)pinned review or a review that doesn't belong to the current location (i.e this.reviews.conatins(review) == false) should we throw an exception there or simply print a message too? I think exception is more fitting here.

**Comment by Kolikant** [comment]
the user doesn't know what the exceptions meens, they aren't programmers. because the databse might be unreliable we should just assume that the information is not there.
unpin an unpinned review? fine, nothing happens
I think so, at least

**Comment by ArthurSap** [comment]
So I will print stuff for now, until we might decide otherwise

**Comment by ArthurSap** [comment]
Decided to add some exceptions to aid ReviewManager's implementation
