### ISSUE TITLE
Update JxMaps to version 1.2.2

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#114]
Following a discussion with the developers about a bug with JxMaps and JavaFX they have released a new version that includes bug fixes 
I need to update the external jars we are using and the maven dependency.
After which I will notify everyone to update their files as well.

**Comment by kapalex** [comment]
files are updated on the google drive folder
**Download them now to avoid errors**
same instructions as before on the JxMaps dependency wiki
@Kolikant @koralchapnik @assaflu @ArthurSap @yaelAmitay

**Comment by Kolikant** [comment]
- [x] Kolikant
- [x] koral
- [x] alex
- [x] assaf
- [x] yael
- [x] athur 

great job!
last time some problems occurred, so just want to make sure everyone gets this working before we close it

**Comment by kapalex** [comment]
nice idea!

**Comment by Kolikant** [comment]
@ArthurSap 
when you manage to get the update up and running for yourself, close the issue :)

**Comment by ArthurSap** [comment]
Hmm tried to update it and it failed, @KaplanAlexander talk to me via whatsapp or something when you're free

**Comment by kapalex** [comment]
Add the error you getting here, we'll talk about it tomorrow

**Comment by yossigil** [comment]
Any lessons here for other course members re the upgrade?

**Comment by kapalex** [comment]
@yossigil don't think anyone else is using JxMaps so this isn't really relevant to them
