### ISSUE TITLE
integrating the new user with usermanager

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#118]
great job @ArthurSap  with the new userImpl functionality, however all the functionality must be integrated with me (usermanager) I'm going to make the changes I need for it and comment out other things. if you approve the changes just close the issue, otherwise let's talk.

**Comment by ArthurSap** [comment]
Only thing I don't understand is why do you want to remove setPassword.

**Comment by Kolikant** [comment]
parse server's password saving doesn't allow for a simple field change, not even manually from the server dashboard. what it does allow is to send an email to the user and have him change it from there, asking the mentors they said it's fine just not being able to change the password.
if you change the password in the local user, it won't be able to work with the database as it's password would just be wrong

**Comment by ArthurSap** [comment]
If you say so, worst case we can revert it back.

**Comment by Kolikant** [comment]
looking at the changes I made, I feel I coupled it way too much with the database.
I think what we should do is dissallow the setters from the class (as if a field is changed and not updated to the server it is no longer recognizable) and allow the changes to happen only in the database

**Comment by ArthurSap** [comment]
You want to completely remove all setters from User? I don't know how much better it would be to delete them from user.. Might be too hard to use afterwards.

**Comment by Kolikant** [comment]
see, everytime a set happens it needs to be coherent with the databse. but that means that user is in no way independent from the database and makes for a confusing interface.
limiting the changing of fields to the database (as they all must pass through it regardless) would make for a logical interface

**Comment by Kolikant** [comment]
another option would be to force the user to remember after a set to make an update (meening st changes things localy while update changes the database)

**Comment by Kolikant** [comment]
okay, how about this.
have the changes, fine
but! 
when user logs out, update everything he changed. that sees the obvious choice

**Comment by Kolikant** [comment]
decouples and seems logical

**Comment by Kolikant** [comment]
no good,
the very act of finding the user in the server is reliant on knowing it's name. this would force the user to remmember it's server name and local name which is silly

**Comment by Kolikant** [comment]
I added a field "local name" for now.
this allows the user to change his name as he sees fit, and when he logs out we need to call usermanager method to save info permenatly. sounds good?
