### ISSUE TITLE
User stories review

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-Accessibility#12]
Please schedule a meeting, next week, with Itay and myself to review and prioritize your user stories.
@idabran - fyi

**Comment by kapalex** [comment]
We are all avilable on tuesday at 16:30 (The scheduled lecture time)
Is that ok by you? @zvili @idabran

**Comment by zvili** [comment]
@zvili - ok with me. Lets meet in Taub 5
@idabran - ?
