### ISSUE TITLE
Route Type: Walking or Driving or Both

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#123]
What kind of route do we want? Walking? Driving? or Both?
if you want both, don't forget to get the chosen type from the gui.

Let me know what you all prefer.
@koralchapnik , @assaflu , @ArthurSap , @KaplanAlexander , @Kolikant

**Comment by yaelAmitay** [comment]
Now that I think about it, "Walking" seems more relevant. I made it walking for now.
probably will stay "walking".

**Comment by kapalex** [comment]
Yeah I agree, walking is the interesting choice

**Comment by Kolikant** [comment]
Yes, walking

**Comment by koralchapnik** [comment]
I also agree on walking
