### ISSUE TITLE
Cycle in saving reviews and location

### ISSUE THREAD

**Issue by assaflu** [TechnionYP5777/SmartCity-Accessibility#124]
When function getLocation is called it needs to return a location, and location is built with all it's reviews, so each review need to be built as well, but in order to build the review we need the location -> cycle that need to be solved

**Comment by assaflu** [comment]
@Kolikant @KaplanAlexander @yaelAmitay @koralchapnik @ArthurSap

**Comment by assaflu** [comment]
I suggest a solution in which review wont save location, but only the coordinates of the location

**Comment by Kolikant** [comment]
That would work
Were we tk have agurantee that that serves as a uniaue identifier
But if a building as a facility (cafe shop in x street) or as an adress share the same latlong

Having that they are different locations for us (one being building and other street)
Wint work.

**Comment by Kolikant** [comment]
How about latlong and type? Type being string

**Comment by koralchapnik** [comment]
@assaflu  Fine for me

**Comment by Kolikant** [comment]
Again
It needs tobe unique.
Locations thatare different can have thesame latlong.
That is the case, a simple r example is a location of coordinate type and the facility inthatcoordinates
Both havethesamelatlong but are different locations, save thelocation type as well

**Comment by kapalex** [comment]
We are supposed to be able to get the Location from a latlng as the user should be able to click on a point in the map and by directed to a page with info and reviews
So from the click point( a latlng) we need to be able to translate it to a location as the user won't provide any additional info

**Comment by Kolikant** [comment]
we need to rethink the location representation then, for duplicities in latlong occour in the current one.

the entire logical wrappers that are locations get broken

**Comment by kapalex** [comment]
Do they occur?  I would think google had that covered in their api

**Comment by Kolikant** [comment]
how about a hierarchy?
facility > route > coordinate

thus if we have both a route and coordinate with the same latlong we return the route
if we have both a street and a facility we return the facility

**Comment by Kolikant** [comment]
google has it covered in their api.
as well as latlong they have an id which is googles unique identifier differentiating streets and building with the same latlong for instance.
we could use it, but the type seems more friendly as an interface

**Comment by kapalex** [comment]
> how about a hierarchy?
facility > route > coordinate
thus if we have both a route and coordinate with the same latlong we return the route
if we have both a street and a facility we return the facility

Seems to me like this avoids the issue more than solves it

> google has it covered in their api.
as well as latlong they have an id which is googles unique identifier differentiating streets and building with the same latlong for instance.
we could use it, but the type seems more friendly as an interface

If that's how they solve it, it still doesnt actually solve our problem
When a user clicks on a point he doesn't have the id, again only has latlng

**Comment by Kolikant** [comment]
explain why the hierarchy doesn't work again, please
the more specific we have, the more specific we should give, no?

**Comment by kapalex** [comment]
but how do we get more specific? user clicked on a point in the map that has a route and a facility, or two facilities, we still don't what he means

**Comment by Kolikant** [comment]
how about this.
anything beats coordinate, everything 
but! if we have both facility and street under the same latlong, we simply just ask the user which he wants

that seems the obvious choice

**Comment by Kolikant** [comment]
let the user tell apart which of duplicities he wants, no?

**Comment by kapalex** [comment]
allowing duplicates and just asking might be the way to go
just need to think how that looks design wise

**Comment by Kolikant** [comment]
lets conclude to all the tl;dr 

@assaflu you can save only the latlong, but save the type as well (location type, look at locations for those)

when duplicates occour under latlong, resolve them if we can, or ask the user which he wants

I will open the issues right now

**Comment by kapalex** [comment]
ideally he should only need to save the latlng and we will ask the jxmaps (google api) which options we have
i'm hoping that's possible with jxmaps

**Comment by Kolikant** [comment]
will that work? we need to integrate it with our own database (having saved in the server on that latlong both street, facility and coordinate)

**Comment by Kolikant** [comment]
oh never mind, I understood what you said. right

**Comment by assaflu** [comment]
@Kolikant @KaplanAlexander  I can save a type for a location if it is needed, and I think it is better, because the more our project wont depend on comunication with Jxmaps is better. Jxmas might be slow (correct me if I am worng)

**Comment by Kolikant** [comment]
Great :)

**Comment by assaflu** [comment]
I have reopened this issues cause i looked again on the implemetation of review and I steel see that we save location and not the cooardinate. Didn't we agreed to save only the cooardinate?

**Comment by kapalex** [comment]
@koralchapnik was in charge of `Review` , you should talk to her so she can change it

**Comment by koralchapnik** [comment]
The question is if all of you fine with the change

**Comment by assaflu** [comment]
this change is nessesary for the DB saving otherwise it is not possible

**Comment by assaflu** [comment]
Or we will have to decide on another way of saving
