### ISSUE TITLE
Create location screen

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#126]
Location is instantiated with a `Location` type
The screen will show a list of review for this location and an option to create an additional review

- [x] Info about the location as provided by Google maps API
- [x] List of reviews
- [x] List sorted by pinned
- [x] Pinned review are highlighted
- [x] Add review button only appears if user is logged in
- [x] Navigate button
- [x] On close database is updated

**Comment by KaplanAlexander** [comment]
currently gets a LatLng at init and has demo reviews and not real ones from the server

**Comment by Kolikant** [comment]
I may be using it wrong but it seems to me that upon closing review are not sotred.

this is the flow of my work:

login
search for yehalom 70.
click yehalom 70
add a review
refresh (see review on the frame)
close
click the same marker
review no longer appears

could be a problem with either the uploading or the recieving of the reviews

**Comment by kapalex** [comment]
both update functions are not working, as I've informed @assaflu 
So yes, it isn't saving it in the database at the moment

**Comment by kapalex** [comment]
This specific problem is related to `getLocation` not getting the reivews tied to a location when bringing the location, instead just the location it self

**Comment by Kolikant** [comment]
okay, as long as the bug is known
