### ISSUE TITLE
Create review screen

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#127]
The review screen will show the contents of a specific review to the user
 should include

- [x] Review content
- [x] rating
- [x] upvotes and downvotes
- [x] upvote and downvote button when user is logged in
- [x] delete button if review was created by the current user or the user is an admin
- [x] pin / unpin button if user is admin

**Comment by Kolikant** [comment]
#32 need to take decisions here to account
