### ISSUE TITLE
Add Searchbar to gui

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#129]
The seach bar should let the user enter free text to search for location as well as let them choose a facility type they are interested in

Similar code can be found [here](https://github.com/TeamDev-Ltd/JxMaps-Examples/blob/master/src/com/teamdev/jxmaps/examples/PlacesSearchExample.java) and [here](https://github.com/TeamDev-Ltd/JxMaps-Examples/blob/master/src/com/teamdev/jxmaps/examples/GeocoderExample.java)

The demo that actually demonstrates it (can help understand what the code does) can be found [here](http://cloud.teamdev.com/downloads/demo/jxmapsdemo.jnlp)

**Comment by kapalex** [comment]
A note about this relating to #29 
Because the default markers cannot be made clickable (JxMaps.. ) after you search for something from this gui, the results should be made into `ExtendedMarker` and put on the correct location for the user to see, this way he will be able to click on them

**Comment by Kolikant** [comment]
are these extended markers part of jxMaps or part of your code?
regardless of answer, how do I create one

**Comment by kapalex** [comment]
You give the map object and location in the constructor, the rest is taken
care of

**Comment by kapalex** [comment]
Example can be found in the `onRightClick` method of jxmapsfunctionality

**Comment by Kolikant** [comment]
the extended marker seems to bypass all the functionality I had with markers in jxMaps functionality.
I need to integrate it with everything existing in the jxmapsfunctionality before it, assuming the functionality is necessary.

**Comment by Kolikant** [comment]
look at the result for now (search for an ----address----) it uses the regular markers I've implemented already in jxmapsfunctionality but should look the same with the extended markers. 
any insight? @yaelAmitay @ArthurSap @koralchapnik @assaflu @KaplanAlexander

**Comment by Kolikant** [comment]
![image](https://cloud.githubusercontent.com/assets/23051198/21775781/1e51d1fa-d6a0-11e6-9048-070763f30960.png)

**Comment by kapalex** [comment]
Yes it does seem necessary because of JxMaps not offering the functionality we need from the default markers so creating a subclass seems like the best solution
ExtendedMarker does (as the name suggests) extend Marker so it should be to much of a mess switching the two out
If you think the ExtendedMarker class should behave differently we can change it to work better with what you made
Other than adding the extendedmarkers what you made looks great

**Comment by Kolikant** [comment]
the problem I am having is that extendedmarker works with location. 
but thinking about it, it really should do that, just brings up the next quentsion: does everytime a user search for some place (being a location not previously known) we create and upload the location? 

this creates heavy coupling with search and location which makes sense to me, but maybe we had someting done wrong to lead to this

**Comment by kapalex** [comment]
Went into more detail about it at #141 
I think this should be regarded the same as when a user click on a random location - the location isn't added to the database until the point where the user actually adds the review

**Comment by Kolikant** [comment]
mmmmmm, this seems to be more complicated.
if the user clicks, the gui will interface with the database, fine.
but if the user searches, search will need to interface with DB and then either return that or create a dummy and offer it to the DB for upload.
makes sense. just writing it for future me (the forgetful guy)

**Comment by yaelAmitay** [comment]
What was the problem? I can't understand you.

**Comment by Kolikant** [comment]
with the build or with the searchbar gui?

**Comment by yaelAmitay** [comment]
with the search bar, you wanted to consult with us...

**Comment by Kolikant** [comment]
Yes
Is the search api to your liking?
