### ISSUE TITLE
Draft of the "readme" file

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#13]
This issue is a draft of the readme file. i.e. this is a draft of the project  report.

**Introduction**
This project is designed to help navigate the city taking to consideration acceptability. The main features would include:
1.	A social network for ranking and reviewing of different street sections and buildings. User rating will effect if a street section and/or building would be considered accessible or not and if so, how accessible it is.
2.	Searching for locations in accordance to queries that can involve travel time, acceptability rank, etc.
3.	Navigation in accordance to only accessible paths.

**Theoretical Background**
People with movement disabilities find it difficult to move freely in the public domain because the street and the buildings of the city are not adapted to their special needs. Our goal is to create a smart city that allows to improve the quality of life of these people.
Our project consists of two main parts:
 One is improving the city's infrastructures. The City Activity Center will collect reports of problematic areas in the city and then the city administrators can perform specific changes in these areas in order to make them more accessible.
 The second part of the project is to enable improvement of everyday life of the disabled people. The application will allow the user to orientate in the city effectively taking into account the limitations of his movement. i.e. the user can find accessible trails in the city and find accessible places such as restaurants, cinemas, etc.

**Programming Environment**
-Eclipse Neon Java
-Linux
-Github

**Basic System Functionalities**
Fully detailed at github: https://github.com/TechnionYP5777/SmartCity-Accessibility/projects/1
Will be detailed in the final report.

**Software Implementation**
Modules-
1.	GUI – TBD
2.	DataBases  - 
•	Social networks – reviews, profiles, likes/dislikes.
•	Rating – link rates to map.
•	"live" reports from users.
•	Accessibility – link static rating to map by superuser. 
3.	Social network
4.	Navigation algorithms.
5.	Searching queries

**User Interface**
The project has two main interfaces, one for each type of user. 
The first type of user is the city manager. The interface of the city manager will include: 
1.	The list of problematic areas of the city (according to statistics from the reports received by other users).
2.	Tools which can determine changes in the city.
3.	The map of the city. The problematic areas of the city will be marked on the map

The second type is a user with a disability. This user interface includes:
1.	Map of the city.
2.	 A search bar that will allow him to find accessible places in the city.
3.	 Option to mark locations on the map and search for accessible trails.
4.	 Option to criticize streets/specific places on the map.
5.	 Option to mark like/dislike on the reviews of others users.

**Comment by yossigil** [comment]
Move the contents into a wiki page or README.md

**Comment by idabran** [comment]
issue should be formulated as a task to do, not as an amorphic idea. 
Issue should sthouil start and end, and not just lurk in the air for someone to look at it. 

Please rephrase as a task/something to do, and close when it is done.

**Comment by kapalex** [comment]
moved to readme.md
