### ISSUE TITLE
Why Review class doesn't have a boolean isPinned function?

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#130]
While trying to work out how pinned and unpinned reviews will look ont he gui I noticed a review doesn't have a way of knowing if it's pinned or not
The only way to check is thruogh the location which seems to be really redundant as a review only has a single location and can't be pinned in one location and unpinned in the other.

What I think the design should be :
- Location only saves one array of reviews
- Review class has a boolean "pinned"
- when admin pins review the boolean will be set to true (default false of course)
- `getPinnedReviews` will simply return all reviews from the list that have true in "pinned"

This way a review will know whether it is pinned or not, in addition to avoiding using the circular dependency which according to @assaflu should be removed entirely.

Thoughts ? @koralchapnik @ArthurSap 

I'm assigning to you as I remember you are the relevant people for this issue, if not assign someone else who fits better

**Comment by koralchapnik** [comment]
I can do the relevant changes in location and review if it is fine by you @ArthurSap

**Comment by kapalex** [comment]
Would appreciate if you could do it soon as I'm dependent on it for #126

**Comment by koralchapnik** [comment]
Working on this now :)

**Comment by ArthurSap** [comment]
Can I assume changed were made correctly and work on #172 ?
