### ISSUE TITLE
Jx-maps cant be decoupled in the nearbyplaces search

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#135]
when ran in a class that does not implement the mapView class of jxmaps, the finding of nearby places inexplicibly runs for all of eternity. when run from one that does(as found by koral) it finishes and works.

this meens that everynearby search will need to create a new map and that the none basic search is coupled with jx-maps.

is this fine, or...
@assaflu @koralchapnik  @KaplanAlexander  @yaelAmitay @ArthurSap

**Comment by kapalex** [comment]
Will look at it today and try to search for a solution as well

**Comment by koralchapnik** [comment]
For now the problem in getting mapView as argument rather than inheriting MapView is the error : 
com.teamdev.jxmaps.internal.aq: Uncaught TypeError: Cannot read property 'PlacesService' of undefined

Working on solving it now..
