### ISSUE TITLE
wierd default behaviour of jxmaps

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#136]
when not being able to decipher the building type given to it, JxMaps (consistently!) returns the same building with nothing recognizable alike. wheter the type is hotel, asdasdasasd or floopyfloopydu 

the same buildings are returned, find out what is the default behaviour

**Comment by Kolikant** [comment]
seems to be effected by radius.
I out the entire countries length and the type of "floopyfloopymanmangfgfgfblahblahthisisatypeeeee" and it resulted with new locations

![image](https://cloud.githubusercontent.com/assets/23051198/21788646/806eab46-d6d8-11e6-8365-033a1cab363a.png)

**Comment by Kolikant** [comment]
add to known bugs? cant figure out any reason behind this wierd consistency

@koralchapnik @KaplanAlexander @assaflu @ArthurSap @yaelAmitay

**Comment by kapalex** [comment]
I think so
Add a section in the readme file of known bugs and put it there

**Comment by Kolikant** [comment]
added
