### ISSUE TITLE
bug in searchQuery

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#137]
when trying to execute the following code:

```JAVA
        MapView mapView1 = JxMapsFunctionality.getMapView();

        SearchQuery s1 = SearchQuery.adressSearch("Rothschild 22, Rothschild Boulevard, Tel Aviv");
        
        JxMapsFunctionality.waitForMapReady((extendedMapView) mapView1);
        
        SearchQueryResult sqr1= s1.SearchByAddress(mapView1);
        
        
        s1.waitOnSearch();
        
        LatLng position1 = sqr1.getCoordinations().get(0).getGeometry().getLocation();
```

it is running forever.
the loop it stuck in is in waitOnSearch but it is arriving to the onComplete method of the search.

do you have an idea for what is the problem ? 
@Kolikant

**Comment by Kolikant** [comment]
I just turned my pc off
Try looking if google maps recognizes the adress (website) if it doesnt it moght be that, if it does maybe consulting with searchtest 1 will help

I would look at it tommorow though :)

**Comment by koralchapnik** [comment]
That is an address that Google maps found.
And I copied the search test and changed the address.
Also turned off my PC..
We'll look at this tommrow

**Comment by yaelAmitay** [comment]
Is this the same problem as #135?

**Comment by koralchapnik** [comment]
I don't think so, but maybe it is..

**Comment by Kolikant** [comment]
yep, definitely a bug
good catch!

**Comment by Kolikant** [comment]
I don't know as to why JxMaps is unable to find the address, but it seems that the very jxsearch fails.

I have added another search status, being search failed, at to avoid being stuck waiting on a successfull search. should resolve the bug. would be commited shortly

**Comment by Kolikant** [comment]
notice that searching for "Rothschild st 22 Tel Aviv" does work
