### ISSUE TITLE
Add access control to upvote and downvote functions

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#138]
Following the change in user design this should be updated to check if a user has the rights to comment (logged in user) before letting the user upvote or downvote

Followup to #16

**Comment by ArthurSap** [comment]
Shouldn't this be under my jurisdiction ?

**Comment by kapalex** [comment]
I originally made the upvote and downvote functions so I thought I'll continue the work
you're welcome to reassign this issue to yourself

**Comment by ArthurSap** [comment]
If these functions are already written I'll just add the access control

**Comment by ArthurSap** [comment]
I did the changes, please look over them.
I also changed your test (look at commit list, i forgot to refer it here) so it will compile.

**Comment by kapalex** [comment]
Looks good
