### ISSUE TITLE
Bug tests of navigation only work on debug mode

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#139]
Bug in navigation the tests only work on debug mode.
I think I know why this is happening, I probably didn't initalize the map of JxMaps correctly.
I'll fix this.

**Comment by yossigil** [comment]
It is better to make a test case with a failing test for bugs. This stops them for repopping

**Comment by yaelAmitay** [comment]
there is a test about it but because it uses gui  I put ignore on this test.

**Comment by yossigil** [comment]
Check out test categories.

**Comment by Kolikant** [comment]
Only working in debug mode strikes me as needing sleep (and therefor a wait)

Have you tried putting thread.sleep(2000) where ever yoyr breakpoint is?

If that gets it to work, you may need to add a sleeping and waking mechanism like there is in jxmapsfunctionality and search query

**Comment by yaelAmitay** [comment]
i know what you talking about but this is not the probelm.(there is already sleep in my tests)
the problem is that an exception rises. i think i didn't initalize the map correctly. maybe i didn't wait for the map to be ready.
i'll fix it after my test on monday.

**Comment by Kolikant** [comment]
Another thing to check out then in case yku are right
Jzmapsfhnctionality offers an extended mapview with a waitonmap method, to call if you need the map ready and dont want crushing

**Comment by yaelAmitay** [comment]
fixed.
