### ISSUE TITLE
The client activates the application, a map is shown.

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#14]
The basic idea is imitating google maps
the initial map will not show any reports, just the map it self
you can move to map by dragging
* possibly zoom in out

**Comment by yossigil** [comment]
@KaplanAlexander  a title is not enough. We expect a good description.

@idabran @zvili

**Comment by kapalex** [comment]
added in latest code
in GUI package Application class has the main, and can be run to see the map
