### ISSUE TITLE
On map startup load all location that are next to the user location and are in the database

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#141]
In order to complete #29 the user needs to have thing to click on.

What this issue aims to provide :
- When the map loads it will check with the database for locations near the user location that are saved on the database
- This location will be marked for the user and he will be able to click on them to see the location frame ( #126 ) 
- If a user click on a location that is not marked on the map ( not in the database) he will also get the location frame, and will be able to enter a review
- If a review is entered into the location it will then appear on the database and next time the user will be able to see it

todo :
- [x] Marker is created by the locations type
- [x] Previous markers are delete when new ones are created
- [x] search should remove these markers
- [x] Ignore streets

**Comment by Kolikant** [comment]
no, this doesn't seem right.
search is supoused to show the location for the user once requested and is suppoused to do it for nearby places. this way would cause an abundance of nameless markers that the user knows nothing about.

**Comment by kapalex** [comment]
What I'm trying to achieve (and maybe i'm going about it the wrong way) is the same thing that jxmaps shows when the map is loaded for the first time.  The user seems locations near him automatically so he can see what is around his location

BUT, because the default markers are useless to us (the user cannot interact with them), I attempt to achieve the same result by showing the user all the locations around his coordinate within some radius

The point being the user doesn't have to know what exactly his looking for, but just look around as well
It shouldn't be too overwhelming in theory

**Comment by Kolikant** [comment]
oh, I see. assuming it is indead not overwhelming information we need to take a few things to consideration.
1) not show streets.: our location managers saves streets and coordinates as well, we mustn't show them-> that would be overwhelming
2) clear them all when search comes: it's a great idea for a starting map, but if the user searches for something, we should clear the map. jxmapsfunctionality already covers that (assuming you used putmarket/putextendedmarker) by useing clear markers

does that make sense?

**Comment by kapalex** [comment]
1.  not completely sure.  how else is the user supposed to see streets?  will search cover streets? because that seems kind of un-intuitive to search for a street (clarifying, not an address, a whole street)
2. definitely makes sense, adding it as a task

**Comment by Kolikant** [comment]
search covers searching for streets (just an a street name gives the center of the street, so it could count) it does seem intuitive to me to search for a street (say the user wants to comment on a streets accessability?)

but if you want --ALL-- the streets near the user to appear (all must appear if searching for them is unintuitive) we need to find a way to inititalize all the street locations or atleast all those relevant to the user's position

**Comment by kapalex** [comment]
Now that I think about it , it does seem better to just search for streets
I'll put it as a task to ignore street locations when showing to the user

**Comment by Kolikant** [comment]
#155 is an expantion of the idea, I beleive

**Comment by kapalex** [comment]
@Kolikant can you add (or maybe you already have) a clearMarkers() call before search?
this will clear out the existing markers created here 
When you do this issue can be closed

**Comment by Kolikant** [comment]
It does so automaticly for elaborate search

It doesnt do it for regular sear h, under the assumption that user would want to agregate markers, and then clear if tjey want.

It should work, if it doesnt open a bug issue for me

**Comment by kapalex** [comment]
That seems good enough, closing this
If I'll run into any problems I'll open a new issue
