### ISSUE TITLE
Implement update functions in Review and Location managers

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#144]
I've added the stubs for my use
The functionality is similar in both : 
- Check if the object is already in the server
- If it is update it
- If it isn't you should decide if it should be uploaded or discarded (for example a new location should be created as locations cannot be deleted, a new review might be an old review deleted and re-uploaded by a different user when he tried to upvote it, in this case you want to discard it)

Noth should be done in the background as to not effect gui functionality, no return value is needed

If you need any additional functionality from DatabaseManager create the stubs, open a new issue and assign it to me

**Comment by assaflu** [comment]
@KaplanAlexander  can you please look at the implementation of the two function and tell me if you think it is ok, so i know that i can advance

**Comment by kapalex** [comment]
yes this looks good
few notes :
- when either uploading or updating review the "pinned" status is disregarded, @koralchapnik  added the `getPinned` function today and you should use it
- We talked about using `HiddenReviews` in review and I don't see that reflected anywhere
- not entirely related here but make sure `getLocation` returns the reviews

**Comment by assaflu** [comment]
About the pinned reviews - I know that i have to add it it just that the function wasn't implemented when i worked
HiddenReviews - i didn't get the time today to get to that hope to reach it tomorrow
