### ISSUE TITLE
LocationType design

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#145]
Following a discussion started earlier we decided to remove the current Location class layout where the Location class is abstract and different types inherit from it, and replace to with a single Location class that has a `LocationType` enum that has `Coordinate, Street, Facility` values

What I propose is to break down the Facility value into sub values such as `Hotel, Bar, ...` to be used as both information given to the user and everywhere else it is needed

Some concern about it were raised so we decided to open the discussion here

In addition I'm proposing another change as a better solution where we keep both a `LocationType` and `LocationSubType` enums and define the subtyping in a similar fashion as can be found in [this](http://stackoverflow.com/questions/15288630/use-of-nested-enums-appropriate-in-this-case) stackoverflow answer

Thoughts ? @Kolikant @koralchapnik @yaelAmitay @ArthurSap @assaflu

**Comment by Kolikant** [comment]
just pointing out that we have not agreed on the enum. 
however, having an enum of enums, puts all of my worries to rest, as long as we make one for street as well. so I am okay with that solution

**Comment by kapalex** [comment]
Alright, we'll see if anyone else has any objections with the new proposal

**Comment by yaelAmitay** [comment]
I'm okay with this 👍

**Comment by kapalex** [comment]
Alright, good enough for now, if anyone else has any new insights reopen this
