### ISSUE TITLE
interface extended marker under JxmapsFunctionality

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#148]
a lot of the functionality of jxmapsfunctionality relies in jxmaps functionality being used....
extendedmarker works around it, so need to add it to work under it

**Comment by kapalex** [comment]
I want to use the function you created to put the extended marker on mark load, but I need a variant that doesn't put an infowindow as I don't need one for this purpose

**Comment by kapalex** [comment]
added it
