### ISSUE TITLE
search API

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#151]
as discussed there are two kinds of searches, adress search (very intuitive) and nearby places search (which finds all following a keyword of a type of place)

how would this appear to the user? 
the current searc (address only)  looks like this 
![image](https://cloud.githubusercontent.com/assets/23051198/21783317/7a55214a-d6bf-11e6-8978-2492fd122162.png)

so here are the options I see that could make sense.
1-most simply: user command line. the user puts opcods such ass : address or nearby which we parse.
this might be tedious for users, but is very simple to implement.
2-another search bar, no way to differntiate an adress to a nearby search, especially since we allow user mistakes, so another search bar. this seems like a bad choice to me, but majority would dictate
3- a button and a frame. most of thetime, users would search by address, it is most intuitive. if they want an elaborate search they would open a frame and fill the fields (currently field) to activate the search. this is probably the most user friendly option but not the simpelest to implement.

@yaelAmitay @KaplanAlexander @ArthurSap @assaflu @koralchapnik

**Comment by yaelAmitay** [comment]
Why not a small button like "show me nearby places". if they want something more complex then i think it should be part of the complex searching.

**Comment by Kolikant** [comment]
Probably explained myself badly
It is with complex searching, just figuring out tje api. What you suggested is with the guidelines of option 3

**Comment by yaelAmitay** [comment]
i meant that in addition to the search button there will be a "show me nearby places" button.
or this could be just a feature of the complex searching.
either way i ok with that.

**Comment by Kolikant** [comment]
show me nearby places button is actually a pretty good feature we should have, but that's not the question at hand here.
the complex searching doesn't just show nearby places, it gets a required type of location and accessability and shows only them. option 3 it is then

**Comment by Kolikant** [comment]
I'm adding the "show nearby location/hide nearby location button" you sugested to the issues, seems necessary

**Comment by Kolikant** [comment]
currently works directly with neabyplacessearch, so not compatible with users favourite serch queries nor with searcquery. but looks goddamn impressive as hell
