### ISSUE TITLE
integrate searchQueryResult with locationManager

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#153]
the search returns information from google maps, we need to be able to sync it with whta we have saved on the database, meening.

we should create dummies for locations not saved in database found by this search, yet have real locations (saved in DB) presented should they exist. the dummies are there because user needs to be able to see places not yet in DB and maybe review them (and thus lead to it being saved in DB in the future) #17

**Comment by yaelAmitay** [comment]
What exactly are you going to do with these dummies?
i mean what happen to them from the moment you create them till the moment they are added to the DB(if they will be added) .
i just cannot see why would you need to keep them. maybe you will need to keep one dummy, the current dummy. but why more?

**Comment by Kolikant** [comment]
need to understand what the complex search does.
it gets a location type and accessability and returns ALL locations in a radius from the user answering it.

however, this search is also the api from which the user finds locations to comment on to begin with.

hence the problem and the solution dummies. the complex search returned a location not in our db? stil need to show it to our user (assuming defult max accessability (for this reason and navigation we decided max acc... to begin with)). now the user can choose the location he wants (including dummies) and comment on them, navigate to them.

should he review one, it can be added to our DB for future use, all none reviewed dummies can a-> be discarded, b-> be added to db for future use without reviews.

**Comment by yaelAmitay** [comment]
I do understand the complex search I just didn't understand you.
now that you detailed i understand what you want to do.

**Comment by Kolikant** [comment]
do you agree? 
any addition is welcome

**Comment by Kolikant** [comment]
I managed to make the adress search do the following: on the map it would show the marker on the adress requested, but when clicked it would show the location of the street, thus allowing adress searches to be usefull both on map and on the database.

all that remains for you to do, is to 1: make elaborate search, look for locations in the database and present them as the location being presented when pressing the marker
2: make dummies out of location NOT in the database still found (as we assume maximal accessability) I will split it to two issue.

**Comment by Kolikant** [comment]
until the update and pulling of review is done we cannot check if this works, so we will close this issue even though it was not tested yet, as we need to see the full flow of the program working
