### ISSUE TITLE
filter out locations under accessability level in search result

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#154]
this is the simplest of the 3 issues created from #17, just a filter of the locations given by the DB. dummies have maximal accessability.

**Comment by yaelAmitay** [comment]
1. the term "dummies" in this contex is not clear...
2. there is already a method that filter the locations from DB

**Comment by Kolikant** [comment]
Yes there is, i built it. 
Vut this is a different filter.

I probably explained, for locations not appearing in our database should still appear here, meaning that we need to get all of the locations weknow out and only then filter.

This with what i defined as a dummy, a location onject of a location not yet in our db, we still need to show it, so users can use them regardless of our db.

So this filter as after being read feom db and not during tje read.

**Comment by Kolikant** [comment]
dummies were explained in #153
