### ISSUE TITLE
current location of user

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#156]
We talked about navigation from current location of the user to some point in the map.
I'm trying to integrate the navigation with the gui. 
Are we saving the current location of the user somewhere?
I saw "Marker currLocation" in Application.java but it looks like it wasn't initialized, and I'm not sure if it's supposed to keep the current location of the user.
In addition I saw that the map is initialize to start "Eliezer 10, Haifa, Israel". Is this is the current location? if so we need to keep the current location in some variable.

#133

**Comment by kapalex** [comment]
How it works right now -
`currLocation` marks the current location.  It is set on startup to a default locaiton "Eliezer 10, Haifa, Israel".  The user can right click anywhere on the map to set his location to that point.
use `currLocation.latLng()` to get the latlng of the user.

Now maybe something should be added to set the initial location, but for now that what we got

**Comment by yaelAmitay** [comment]
yes but where does the initialization of "currLocation" happens? I looked it up but i just can't find it.
i see the part of the "right click" but i can't see the first initializatin.

**Comment by yaelAmitay** [comment]
Nevermind.
