### ISSUE TITLE
navigation blocking the user

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#159]
Right now when a user push "navigate", the navigation block him from doing anything else.
I want to make the navigation a non blocking action. But i'm using the shared mapView so do we need to add synchronization for mapView access?

@koralchapnik @Kolikant @KaplanAlexander

**Comment by Kolikant** [comment]
No, its a copy ont the user's local device,
Synchronization of the real map stuff is done by google.

All we need to synchronise is db, but even that is taken care of.

Nome blocking is a good call, you will need to accept a callback function from gui though

**Comment by yaelAmitay** [comment]
So it's okay to add stuff to the map while the user might change some other stuff on the map? are you sure?
I'm not sure if I'll have to use callback, I'll check this out...

**Comment by Kolikant** [comment]
Oh
I have completley misunderstood the question
Yeah
You should block --> the map
You should stop activation of searches though and other map changing things

**Comment by Kolikant** [comment]
But moving the map? Changing profile things, looking at database and cheking reviews should still be active on the map

**Comment by yaelAmitay** [comment]
Why should I stop other activation of search? I just need to draw the route on the map,
if I could take control on the map for a second or so(using mutex) it should be okay.
but everybody should do the same.

**Comment by Kolikant** [comment]
You shouldnt stop them
You need to dissallow them
Make rhe buttons go grey

**Comment by yaelAmitay** [comment]
but if they start before my navigation?
then they won't allow the navigation?
i still have a problem with the user, because i'm changing the center of the map and the zoom, if they uer change them in the same time it might be a problem.

**Comment by kapalex** [comment]
ideally clicking the 'navigate' button shouldn't stop the user from doing anything
We haven't implemented it but some spinner that shows something happening in the background would be great
and them only when the results of navigation are in the center of the map and zoom should be changed, making the user see the navigation route

**Comment by yaelAmitay** [comment]
I'm talking about showing the route in the map, I've to make changes in the map if I'm not blocking the user and he tries to change thing on the map in the same time I'm changing the map it can cause problems.

Yael

‫ב-12 בינו׳ 2017, בשעה 7:40, ‏‏Alexander Kaplan ‏<notifications@github.com> כתב/ה:‬

**Comment by yaelAmitay** [comment]
@Kolikant and I tried to do some experiment and it looks like the current implmantion does not block the user from moving the map or zoom in/out. though the location frame is blocked.
I think i'll just do the navigate on different thread with no callbacks and no synchorinzation. and then the location frame won't be blocked.

**Comment by yaelAmitay** [comment]
done.
