### ISSUE TITLE
Users can upvote or downvote a certain review

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#16]
for reviews for a certain location ( #21 ) , a user can upvote or downvote to mark his agreement or disagreement with this review
sum of upvote and downvote will be shown on the review
includes not letting a client(non signed-up user) do this

**Comment by yossigil** [comment]
Better terms are upvote and downvote

**Comment by kapalex** [comment]
Will change, definitely better

**Comment by kapalex** [comment]
Following the change in user design this should be updated to check if a user has the rights to comment (logged in user) before letting the user upvote or downvote

**Comment by yossigil** [comment]
Don't reopen issue. Start new ones.
