### ISSUE TITLE
pop a message alert when navigation failed

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#161]
the navigation can fail for many reasons: bad connection to the internet, mapQuest server not available(rare), no route exists, etc.
we need to pop a small window to tell the user that the navigation failed. 
right now if the navigation failed the user won't know about it and the app **won't** crash.

**Comment by yaelAmitay** [comment]
done.

**Comment by Kolikant** [comment]
wrong issue reopened, sorry
