### ISSUE TITLE
Navigation doesn't goes throgh parks

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#163]
Navigation doesn't go through parks.
I'm not sure if I can fix it because we are using MapQuest and it probably their fault.
So maybe we will addd this to the list of known bug?

What do you think about it?
@KaplanAlexander @Kolikant @koralchapnik @assaflu @ArthurSap

**Comment by kapalex** [comment]
If it's a problem with MapQuest (as opposed to some configuration problem which I assume you've checked)  then we probably don't have time to fix it this sprint, I think adding it as a known bug is the right call, and later we will think of what should be done (next sprint)

**Comment by Kolikant** [comment]
How about adding a dotted line from where mapquest ends to the end point?
Saying we know you can get to here (none dotted) but this short path was not marked ( dotted)

For now?

**Comment by yaelAmitay** [comment]
I can do something like that, I'm not sure about dotted but i can try different color.

Yael

‫ב-12 בינו׳ 2017, בשעה 15:40, ‏‏Ariel Kolikant ‏<notifications@github.com> כתב/ה:‬

**Comment by yaelAmitay** [comment]
I just want to add that it's not just parkd. it's all the gray parts of the map.

**Comment by yaelAmitay** [comment]
I added blue lines to start and/or the end of route that start or end in a gray area of the map.
I'll also add this to the list of knonw bug.
