### ISSUE TITLE
give up on user favourote search queries?

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#165]
the entire reason i am even integrating elaborate search with search query is because we wanted users to be able to save their favourite search queries, but we dont seem to be that interested in it.

leaving them incompatible (which they are so deffinetly are) would allow for more meaningfull return values from each.

since GeocoderResult and PlaceResult are completley incompatible I have to resort to extracting just latlng from searches, whilst the regular returns are more meaningfull.

does anyone beside me even remmember favourite search queries anyway? #164 

@koralchapnik @yaelAmitay @ArthurSap @KaplanAlexander @assaflu

**Comment by kapalex** [comment]
It definitely isn't a main feature, more of a nice to have, so if it compromises other more important features I say put it aside

**Comment by Kolikant** [comment]
managed to integrate! so the way to adding searc hwueries is paved.
they are saved, parsed and loaded, just not added nor used.

wont mind them until next sprint though
