### ISSUE TITLE
SearchQuery needs MAJOR refactoring

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#166]
managed to integrate the two types of searches, but it sure ain't pretty.
it works for now but is very higly not fool proof and needs to be used in precise manners (AKA bad design) so refactoring of it is needed

**Comment by koralchapnik** [comment]
Which refactoring did you think about ? (in terms of design)

**Comment by Kolikant** [comment]
I integrated the usage of nearby places to be encapsulated under SearchQuery.

the usage is pretty much horrid, but doesn't effect the class you wrote, I had some ideas, but explaining all of them here would take too long, next meeting?

**Comment by Kolikant** [comment]
might be reopened next sprint
