### ISSUE TITLE
add path cleaning to be activated from clean markers

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#167]
pressing clear markers means that the user wants to see a clean map, cleaning the navigation path should also be activated from clear markers

**Comment by yaelAmitay** [comment]
I already did it....

**Comment by Kolikant** [comment]
wierd, I ran the most recent version and it didn;t delete, made sure a couple of times before opening the issue. 

now after you said it, i pulled, had no changes and now it works.
strange indeed

**Comment by yaelAmitay** [comment]
maybe you didn't refresh?

**Comment by Kolikant** [comment]
I think I did, regardless it doesn't matter. god job. check out the issue I reopened, that one seems to be still valid

**Comment by kapalex** [comment]
can confirm it worked when I tried it
