### ISSUE TITLE
when user click Navigate show the user that navigation is working

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#169]
when user click Navigate show the user that navigation is working by opening a small window or somethinkg like that.

**Comment by kapalex** [comment]
One option would be to add a spinner in the main screen of the app, and make it visible when navigation is working (this can also be reused for other parts of the app)

Also when navigation is started the `LocationFrame` should be disposed (`frame.dispose()`)

**Comment by yaelAmitay** [comment]
done. I'll leave this issue open for a while to let you express your opinion about it.

**Comment by kapalex** [comment]
There's place for improvement aesthetically (mostly making the background transparent) but it looks very good and definitely good enough for now
Should probably be reused for search @Kolikant 

Closing this for now, since this seems done to be

**Comment by yaelAmitay** [comment]
making it transparent is going to be a little difficult for me because I had to make the animation myself and i don't have the tools to make it transparent...

**Comment by yaelAmitay** [comment]
We can't use images or animation from the internet because of copyright.

**Comment by kapalex** [comment]
As I said, theres really no need in changing anything right now, maybe in the future if we see the need
And we can use things from the internet as long as we check the license they are provided with and see we can comply with such a license
Things provided as freeware (and there are plenty) should do fine, and not cause any legal issues

**Comment by kapalex** [comment]
A quick google search turned up [this](http://loading.io/), according to their terms of use, we can use any of the generated loading gifs for free for any purpose

**Comment by yaelAmitay** [comment]
cool I thought it wasn't allow...
I'll replace the icon soon
