### ISSUE TITLE
Users can search for a certain facility (Cafe, hotel, etc.) of a certain accessibility rating

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#17]
This will be an extension to the search bar functionality ( #28 )
when searching user will be given an option to filter by accessibility rating

**Comment by koralchapnik** [comment]
you can help the info [here](https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/JX-Maps-Search)

**Comment by Kolikant** [comment]
wow, great Job!

**Comment by Kolikant** [comment]
even after all the work done for this so far, this is too big for me.
anyone care to share?

@koralchapnik @ArthurSap @assaflu @yaelAmitay @KaplanAlexander

**Comment by ArthurSap** [comment]
If you'll finally give me that sweater!!
Talk to me tomorrow and give me an update

**Comment by Kolikant** [comment]
I am spliting it into two
