### ISSUE TITLE
Update admin tests

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#172]
After the changes discussed at #130 both tests seem to be failing (One was put on ignore temporarily)
You should look into what is happening and update the test to be relevant
Consult with @koralchapnik regarding the changes

**Comment by koralchapnik** [comment]
I've been told to ignore these teses sience admin is deprecated

**Comment by koralchapnik** [comment]
Maybe I forgot to put ignore annotation on the other test

**Comment by kapalex** [comment]
Ignore isn't the solution anyway, as we want that functionality tested
regardless of the changes

**Comment by ArthurSap** [comment]
I intend to deprecate MockAdminTest as all relevant classes work right now.
In case of future bugs I will make the class relevant again.

**Comment by ArthurSap** [comment]
K seems I'm finished, gonna add some more tests but that's not relevant for this issue.
@KaplanAlexander check if everything's fine and close it.

**Comment by kapalex** [comment]
As you can see the build is still failing because of those tests, note #171

**Comment by ArthurSap** [comment]
Deprecated mock test but it doesn't seem to ignore it while building... should I just delete it?

**Comment by kapalex** [comment]
either put a `@Ignore` annotation if you think you'll need it at some point in the **near** future or just delete it
