### ISSUE TITLE
Change getLocation to void

### ISSUE THREAD

**Issue by assaflu** [TechnionYP5777/SmartCity-Accessibility#175]
Since we want getLocation to run in the background it should be void functoin that gets a getCallback function, if I am not mistaken. But the function is already in use in some parts of the code. How should we change it?

**Comment by kapalex** [comment]
create a new getLocation function that works with the callback and put a deperecated label on the previous, than transfer the issue the to people using the old one so they know they need to update

**Comment by assaflu** [comment]
Ok thanks
