### ISSUE TITLE
Review keep id location instead of latLng

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#180]
Review keep the id of Location instead of latLng. The id is the same as the id of the location in the server.

- [x] Review keep id of location and not latLng

- [x] The DB of Review will keep the id of the location and not the latLng

- [ ] The LocationManager should has a method that get id of Location and retur nthe location

- [ ] everybody else who's this change concern them comment here and change accordingly

- [x] When a review is added to the DB but the location doesn't exist you need to add the location.

@Kolikant , @KaplanAlexander , @assaflu , @ArthurSap  , @koralchapnik

**Comment by kapalex** [comment]
id should be the id given by the server not some id we create
Meaning when a review is created we get a location type, we check if it is already in the server (if it is we can get its id from the server) or if it isn't then we create a new location object in the server and take the id from there
So location type does not need to have an id field (bullet point no. 1)

**Comment by yaelAmitay** [comment]
So first of all we need to add a bullet: add locaion to DB if someone upload a review that does not exsits, right?
About using the id of the server that's okay I'll update the issue

**Comment by kapalex** [comment]
yes, if someone uploads a review that relates to a _location_ not in the DB

**Comment by Kolikant** [comment]
In previous discussions we have changed location completely as to allow (latlong, type, subtype) tp be the unique identifier

That being because we want to be able to find locations unknown by the server

**Comment by yaelAmitay** [comment]
I know but as you can remember we can't store location in review because of the cycle @assaflu  talked about. therefor we stored latLng. BUT latlng is not a uniqe key of location. therefor if you ask for reviews of some location and there are several location with the same latLng you will get all of them. And we don't want to store (latlong, type, subtype) in review.
Although,we can take care of this issue in the next sprint, that's fine by me.

**Comment by Kolikant** [comment]
latlong,type,subtype are just strings? why cant we save those?

that was the entire purpose of this change.
but sure, (makes the change abit pointless but would still achieve all we wanted)

**Comment by kapalex** [comment]
The change is still relevant as we still do need a way to distinguish different `Location`s
But the way of referring to those `Location`s from `Review`s is by referring to their id in the server instead of saving all the fields that the `Location` consists of
This has the benefit of not being dependent on any future change in the `Location` identifier while still linking to a single `Location`

**Comment by yaelAmitay** [comment]
Exactly what Alex said!

**Comment by Kolikant** [comment]
now i understand what you meant, and agree that it is the better design

**Comment by assaflu** [comment]
to sum up - Review will hold the id number (in the server) of the location it belongs to.
when adding a review, if it's location is not in the server the location will be added
