### ISSUE TITLE
Some test in NavigationTests is stuck in infinite loop

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#187]
The build isn't working since yesterday because of some test in NavigationTests
I can't tell which because it is stuck
You should either fix it or put some global timeout so it will actually fail

**Comment by yaelAmitay** [comment]
I didn't made any changes so it's very strange, and where can I see the jenkins issue about it?

**Comment by yaelAmitay** [comment]
I run the test on my computer and everything works fine, it takes time because I put sleep in the end of the tests.

**Comment by kapalex** [comment]
It's working now, have no idea what changed
but it stayed the entire night yesterday and didn't finish
if you don't mind, tests that are not automatic should be on ignore
or put in a different test category (although we have have yet to completely set that up)
At the very least put a global timeout so it never gets stuck

**Comment by yaelAmitay** [comment]
I was told to not use Ignore on test, and although I can't see why any of my test would  stuck I will add a timeout just to be sure.

**Comment by kapalex** [comment]
This isn't the right solution, I agree.  But we haven't worked categories out yet, and that's why for now ignore is the way we use
Running tests that are just sleeping for 10 minutes is very wasteful
