### ISSUE TITLE
Calculating the best n reviews

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#189]
Just to make sure:
assume the number of pinned reviews is x.
if n <= x then we calculate is by average of the x reviews.
if n > x then we calculate the rating by average the pinned reviews and the best n-x unpinned reviews.

Am I right ? 
@KaplanAlexander @Kolikant

**Comment by koralchapnik** [comment]
After the approval I should : 
Change the tests of bestReviews and change the implementation

**Comment by Kolikant** [comment]
Yes that is right
