### ISSUE TITLE
Tidy up code for Yael

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#194]
_This issues is meant to help finalize our code towards the submission, in addition to leaving the code as coherent as possible to better understand it next semester_

## Follow the list of tasks and close this issue when finished

- [x] Edit the following list to include all code files you worked on (can be shortened with entire packages where suitable)

**You are in charge of the following files:**
- All classes in Navigation package and sub-packages: Navigation, JxMapConvertor, Route, and more...
- NavigationTest
- SpinngWheel
- RatingStar
- GUI of Navigation(part of LocationFrame)
- UserProfileFrame
- I changed a little other classes like: LocationManager, ReviewFrame...

### For each file complete the following tasks 
- [x] Remove warnings  (_hint:`ctrl`+`shift`+`O` removes redundant imports_)
- [x] Auto format  (`ctrl`+`shift`+`F`)
- [x] Spartanize (`ctrl`+`5` on marked code, possibly multiple times)
- [x] Remove comments that you feel are outdated or irrelevant 
- [x] Remove `TODO` marks (should be stored somewhere better)
- [x] Remove deprecated functions and classes
- [x] **Optional:** Add javadoc where you see fit 

_This is also a good time to review the code written and think of changes to make in the future, tasks you think should be done next sprint can be put as a comment to this issue, where you will know to look for them next semester_

**If you have any more ideas as to fixes everyone should make in their code add them to every ones reformatting issue**

**Comment by yaelAmitay** [comment]
Ideas for next sprint:(I'll edit this comments more when I'll have more ideas)

1. show route's manuver to the user - navigation

2. add categories for tests

**Comment by yaelAmitay** [comment]
about the Spartanize, I left little piece of code un-Spartanized because I feel that the specific changes it asks me making the code less readable. can I leave it un-Spartanized ? It's really small piece of code..
@yossigil

**Comment by yossigil** [comment]
Where was this bit?

In general, yes you can: but also, in most cases, there are better ways

**Comment by yaelAmitay** [comment]
In the method showRoute in the file Navigation.java the tip is: "Inline local s into subsequent statement".
And then the spartanizer ask the same tip recursively for the line he changed and the line above.
but this making my code un-readable, in adddition i feel that maybe in the next sprint i would like to make changes to the code but if all the code will be inline to one line it's going to make it harder to change it in the future.
Just to be clear i wouldn't mind one inline but the multiple inline making all the code in one line is going to  be hard to maintain

**Comment by yossigil** [comment]
Good point Yael, but:

- You can disable spartanization is few selected locations.
- The zoomer will help in maintaining the code.
- Our experience shows that maintainence is not such a problem.

**Comment by yaelAmitay** [comment]
mm... so right now leave it that way?

**Comment by yaelAmitay** [comment]
oh and I'v similar situation in the test of navigation as well. the same problem with multiple inlines.

**Comment by yossigil** [comment]
Thanks! Good luck in the exams

**Comment by nwoodthorpe-test1** [comment]
ו̸̙͓̙̝̯̥̗̩̟͈̗̠͐̏ͯ̒̈́̌̿̍̊̿͊̓ͯ̽̈ה̌̿ͩ̽̑͗ͮ̐͞҉̹͈̭̞̫̘͇̱̦̦͍̱́ע̭͈̱̣̤͕͙̹̙̮̲̝ͪͤ͐̿͂ͥ͌ͦͮͪ̕͢͠ב̨͍̹̠̜͙͙̺̝̬̙̯̹͚͊̈̉͌ͥ̈́̇͜ר̵̲̭̘̭̌́̐̚י̨̹̹͔̫̺̳͙̒ͣ̉̾̀̾͗͂̑͐̈̄̃̏̃̃͂͘͜͟ת̸̴̶̨͈̤̘͎̘̫̪̺̱̅͒̓̋͐ͣ ̧̻̤̮̠͛̍ͣ͊́̕͡͡ה̵̸̶̷̧̣͕̘̪̱̘̗̯͍̮͗̑ͫ̓ͧ̿̀ͪ͛̎ͦ̈́ͩו̉̆̈́͋̄ͫ̀̄͋̂͑̽̓̋͐̎̕͘҉̴͎̮̝̥̼͈̝̠̹̤͓̭̗́ק͔̹̰̺͙̔̓͗ͣͦͨ̔̒̇̈́ͪ̅̏͡͡͡͞ל̴̞̳̩̞̻̼͚̜͔͉̮̺̜̩͚̓ͮ̀̌̈́͘ד̴͉͔̗̬͔̑̉̏͌ͯ͜͟ͅͅ ̸̴̺̺͕̗̦̙͇̟̽͐̔̔ͦ͊ͯ̑ͧͪͥ͆ש͗̈ͬͭ̐͏̢̞̻͚̗̖̖̮͔͓͍͖͙̹̗͈͍̠̳͝נ̨̡̰̜͖̰͙̪̺ͫͪ̑̍̎ͯ̿ͣ͒ͥ͊̌͂ͭ̃̐͌̚͜י̵̵̼̙̺͚͓͍̲̝̹̥͍͉̦̻ͥͭ͗ͪ͛̃̄̀͞ו̧̳̙͙̃ͬͭ̓̉̊̾̃ͥ̏͛ͪ̆̊̌͑̽̍͡ה̴̵̨̥͓͖̟͎̞̖ͭ͗͋ͥ̏ͥͮ̆ͭ͝ע̶̶̡̨͉͉̯̲͖͔̠̞͚̺͔͇̪̤̺̻͇̈̈́̋͒͋ͫͦ́̒ͭ͛̽̈̋̓͘ב̛͌̇͋ͪ̽ͮ̉̀ͫ̄̓̋͗̐̆ͣ̃͝͠͠͏̭͎͙̳̫̹̲͖̰̹͔̜̟̭͕̪ר͉̼̘̯̭̙͉̭̬̫̞̗̗̭̯̒ͧͫ͊̾͋̅͗͑̀ͨ͡͠י̡̩̩̟̮̱̍̎̔̔͆̄̅̔̿̒͛͊̉̇̃̆̋̚͘͞ת̽̑͂̊ͭ̀ͦͮ̀ͯ͏̡̫̰͈̭̳͕̣͚̕ ̶̡̦͈̦͎̤̭̤̣̥̋ͥ̽ͬ̿͐̂̉̉͐̔ͪ̇ͧͦ̈́̀ה͑ͦ͐ͤ̑̄͑̓͒ͧͧ͠҉̬͍̣̱̯̬ו̢͕̲̼̠̘̊ͭ́̾̏̈́͘͠͠͡ק̷͍̥̼̳̖̥̦̻̞̦̺̤̠̥͚̥̓̂̐ͨ̚͘͟͠ל̧ͣ͊͆ͦ̓͂ͥ͋͌̄́̓̇̔̆ͦ̊҉̨̮̰̩͙̫̟̰̖̝̺͜ד̷̵̅̿̾͑̊̉͊̈́͞͏̵̰̬̯͍͈͕͎͕̥̥̭ͅ ̜͔̰̭̹͎̪̭͑ͨ̔̈ͨͧ̎̇̋̄ͬ͆̚͢͠ͅש̟̮̗͈̤̜̩͇͓̩̬̈́͒̌̔̔̆̀̚̕͜͝נ̵̴̴͕̳͖̱̪͛ͣͫ̎ͫ̊͒י̵̡͙̯̫͓̹̼̥̥̹̺ͣͭͭͣͥ̂̀͜͞ו̷̨̛̲̹̥͎̗͉͉̘̙̳̬̺̆ͯͣͯ͊̓̈́̑͗̒̅̚ͅה̸̧̘͖͔̻̬ͤ̀͆͂͐ͯ͋͟͠͝ע̢̛͓̱̳͓̐̅̐ͦ͗̓̔͊͂́ͪ̽̾ͪ̃ͮͬ́͘͝ב̢̠̮̦̭̖̤̦̳̲͈͓̈ͯ̄̆ͦ̿ͨ̍̌ͦͬ͐͑ͪ͑ͥ̏̇͜ר̶̸̧̹͇̖̭͖̪̳͈͉̩̤͈̌̑̏̌͋̉̀͝ͅי̷̡̢̧̤̱̗̹͉̭͈̲̳̦͇̰̳͓͚̙̰́̽ͣ̍ͭͧ̍ͦ̈͗̅̽͊̆ͬ̀ͫ̕ת̒̀ͧ̑̔̌̓ͫͩ̚҉̸̡̱̞̤̝̗͈̰ ̷͇̝̤͚̥͈̩͔͔̬͙̱͚͙͓͖̺͈̄͌͂̒́͛ͪ̀́̕͟ה̸̖̗̺̳̝͉̠̥̳͍̮̣͎͇͇͎͈̱͚͑̋ͫ̈ͩ̍̃ͨ̆͆ͣ̀͟͝ו̢̖̺̬̙̺̲͙͇̮̾͆ͨ̅̉̅́ק̡̢̤̬̰̪̬ͮͮ̿̄͂͛ͤͦ̏̃̂ͩ͘͝ל̵̨͖̝͚̙̙̼͔̤̥ͨ̅͌͗̅͂̇͘͞ד̧͇͇̘̘̙̯̲̩̘̠̘͉̣̘̞̞̺̻͊́ͦ͌̐ͤ͗̀̾͂̀̾̑ͨ͞ͅ ̬̦̹̠͖̥̠̰̙̝̼̫̺͕̝̗͉ͫͥ́͗͐ͮ͌̔ͦ̅̂͡͠ש̶̠͉͙̤͎͉͖͕̙̦͙̺͔̘ͧ̍̇ͨ̋ͭ͛ͬ̾ͬ͢נ̡͇̩̫̻̩͍̰̻̼͈͍̲̥̹̖̄͒̓ͭ̀͟ͅי̡̢̝͚̘̝͚͔̹̖̪̙̖͍̎̌͒̂ͧͭ̊̂͊͘͝ͅו̸̴̮̥̜̮̦̟͔͕̰̗̻͓̮̙̗̀ͬ̓ͦͬ̽̿̾ͫ͐̅ͩ̑̒̑̒̏̚͟͢͠ה̷̛̟͖̤̗̮͓̮͈̺̜̺̱̂͊ͨ͒̂̃ͣͫ́͂̔́ͭ͑̓̈̚ע̢̤̫̟̻͎̤ͥͦ͐͆ͯ̾̉̄͜ב̻̮̟̦̱̯̘͉̰̹͖̜̞ͣ͗̽͆͑ͬͬ̓̄̋͌̅̊́̈͋̚̕͞ר̉̊̉̅́ͫ̈́͂̐ͮ̇̾͛ͦ̓̊͏҉̻̰̪͎͔̹̗̝̰̫̣̥̱̟̮̩͢͠י̸̢̩̳̼̫͈̳̫͖̘̯̳͖̫̣̺̰ͮ̎̈́ͬ̓̌̇ͦͦͫ͋̓̄̕͘ͅͅͅתͯ̔̊̒ͥͮ̽ͯ̀́̿̂͊̀̃̐ͦ̚͏̴̟̭̼̞̰̭̘̲̥̙͖̗̩̭͉̪̪͕͖͘͠ ̶̨̮͉̮̼̦̩̱͎͙̳̙͈͚̝̜͖̻ͧ̑̑͐̃ͥͩͬ̄ה̡̧͈͉͈̰͉͈̳̣̫̻̰̝͖͐ͦͬͩ̆̆ͣ̓̾̚̚͝ͅו͚̫͈͖͕̫͚͖͙̺̎̿ͩ̔̂̿̂̒ͩ̋͒̀ק̠͍͖̬͕̫͎͇̘̯̬͎̗̥̞͎͎̺ͯͩ͋̅̊͗́̍͋̀̕̕͡͝ל̩̳̤̼̘̱͕͓͈͓̓͂͂̒ͫ͌ͩ̆̋̇̃̓̀́̚͞ד̴̵͚̗͇̲̝̠̦̓͂̌͐̎ͯ̉̏̉ͫ̆̉̈̓̇͡ ̴̺̻̪̹̣̰̆͑̌̆̓ͬ͗ͧ̉̎̀̇̋ͮ̌̽̅͟͞ͅש̃ͤ͊̆̑̆̌̆ͨ̾ͤ̌̽̿̊͏̖̯̘̥̭̞̠͕͍̻̬̠̜͚̬̫̯̤͘נ̶̢̼̜͓̭͓̤͇̝̲̰̬̙̳͆͒ͩ̇ͮͅי̵̗͉̫̝̝̘̱̟̿͐́̒̌͒̃̄ͧ̈ͫ͒̋̂̓͌͊̈̀͘̕̕ו̶̡̣̲̺̭̱͖̻̙̲̱̱̹ͥ͋̍̓͑ͩ̀̏̐ͭ͋̅ͥ̌ͧ̊̚̚ה̡̨̳̰̖̮͍̟̐͋̓͊̾̍ͥ́ͅע̵̖͔̱̻̼̞̻͉̦ͧ̉̀̀ͣ̊͌̈ͥ́̑͊̊͆̑͗͗͘͡ͅב̴̴̼̖͚̹̯̤̙̹͚͈̽͒ͦ̎̐̓̋ͤͮ͊͌̿͂͆̂̓͘͡ͅר͍͚̺̩̱̩̠͇͓̜ͥ̐̍̐͘י̶̲̱̣̟̳͔͚̙͙̮ͨ̈̌̎̂͒̍̓ͥͮ̾ת̷͉̮͍̥͍̰̮ͣ͊ͪ̿̾̽͊̄ͣ̇͘͠ ̴̞̼̟̤̹̙̻͚͚͚̲̭̱͚͛̌́̐ͫ̑̄ͧ̍͟͢ͅͅה̸̛̞͉͍̼̳̝̼̪̦̅̋ͯ͌̆ͦͥ̐ͥ͑ͪͦ̈ͩ̇ͦ͊̚͘͠͞ו̧̧̛̛̜̜͙̯̤͇͉͖͛͒͑͠ק̽ͬ̍̽ͨ͊͌ͦ͏͏͇̟̱͍̱̝̬̖̟͈̖ͅ
