### ISSUE TITLE
Admin Account exists

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#20]
- An admin user exists to control and modify information displayed to users (delete misleading info etc.)

**Comment by ArthurSap** [comment]
Should we allow admin to edit review's information? e.g editReview(Review r) - we can also automatically add a "Admin edited this review" to the top of it.
What do you say @KaplanAlexander @Kolikant ?

**Comment by kapalex** [comment]
If I recall correctly we said we shouldn't do it last meeting, since it seems to still be kind of interfering with the information the user put

**Comment by Kolikant** [comment]
isn't this issue pretty much done with the implementation of the rings etc?
