### ISSUE TITLE
Your code is not spartanized.

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/SmartCity-Accessibility#202]
![image](https://cloud.githubusercontent.com/assets/12775400/22340399/09dd7194-e3f6-11e6-8989-20afdd6957e2.png)

You **cannot** fix this now.

@TomPalny @idabran @orimarco @AdiOmari @yh-github

**Comment by kapalex** [comment]
A new issue will be opened once we decide what standards we plan on abiding by this semester
