### ISSUE TITLE
change reviews of streets to be on map segment

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#207]
We now using "map segment" in the reviews of **streets** .
background story:
the problem with current state is that the navigation works in resolution of segemenst of the map. meaning that If you do not want the route to pass at some point you will have to avoid the whole segment of the map that include this point. it'll make more sense that the reviews of the streets will be on the whole segment and not on some specific point.
 Meaning that from now on if we have 2 points in the map that are in the same map segment they both will be considered to be on the same map segment. so if we leave a review in the first point it will appear in the second point.
this is only true for streets and not for other locations.
To conclude we need to add the map segment of each location to the DB(add column to location DB)
if the location is not a street then the value of the map segment is not relevent.

**Comment by yaelAmitay** [comment]
I'll take care of this issue when i'll done with some of the ionic part. because the ionic part is more important right now.

**Comment by yaelAmitay** [comment]
@KaplanAlexander 
can I add code to LocationManager?
can I add column to Location Table in the DB?

**Comment by kapalex** [comment]
Yes you can, but I think it would be a lot easier to tell me what it is you want to add and let me do it, as I think you delving into the `LocationManager` code would be mostly time wated

**Comment by kapalex** [comment]
According to what I see, I think a seperate table for map segments might make more sense, but I'd love to discuss it with you

**Comment by yaelAmitay** [comment]
I agree that it makes sense do it in seperate table.
I also think that we need to talk about the reviews because they will need to look for the MapSegments table to show all the reviews of some specific mapSegment.
I'll think more about it...

**Comment by kapalex** [comment]
We can discuss it together if you want to, or if you do decide on exactly what you want, create an issue for me to add it to the db

**Comment by yaelAmitay** [comment]
Okey,

The implementation right now is:
user upload a review to a street. the review already contain the location he clicked on.
user ask to view the reviews of some street. he get only the reviews in his specific current latLan.

What we want is:
user ask to view the reviews of some street. he get all the reviews of that street.

I think that given our implementation a simple solution could be:
-adding a column to the reviews table that include the segmentId for each streetReview.
-when user upload a review insert the segmentId of this location to the table with the review.(we can do it to all the reviews or only to reviews on streets).
-when user ask to view all the reviews of some street. get the location form the review. get the segmentId of this location. find all the street reviews whit the same segmentId.

What do you say?
I know that adding a column is not the best idea. but I think it's the simplest.
I would be happy do implement it myself. but if you prefer to do it that's okey.

**Comment by kapalex** [comment]
I think it makes more sense to put the segmentId in location

The changes i propose (possibly more similar to your original idea) :
- Location gets a field segmentId which is null unless the type is Street
- Location db implementation has a field segmentId
- When Location  Manager restores Location from db, if location is of type Street, gets the reviews of all locations that have the same segment Id

This shouldn't be too hard for me to implement and should be convinient to use

Sounds good ?

**Comment by yaelAmitay** [comment]
If you think it's good then fine. 
Just know that in order to get the segmentId you need to use my function from Navigation:
`getMapSegmentOfLatLng`
and note that this method send a request to a server so it takes time and it might fail duo to networks issues.

**Comment by kapalex** [comment]
The assumption in Location Manager is (and should always be) that it is getting a valid `Location`
Meaning the `Location` should already hold the segmentId by the time it gets to Location Manager

The LocationBuilder is where we are supposed to make sure the location being built makes sense, so I will add a function of `addSegmentId`, and it is the responsibility of the user of said builder to call it in case of street
If he doesn't do so for a Locaiton of type Street, build will fail

**Comment by yaelAmitay** [comment]
So you should tell everybody about it, or at least tell the one that should create the location to use this function.

**Comment by kapalex** [comment]
The locaitonbuilder was in one of the of my explanation issues, but ill tag everyone when i finish and clarify
