### ISSUE TITLE
changing GUI from swing to JavaFX

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#208]
Right now our GUI is based on swing.  Also our gui is very basic and we want to make it better and more advanced. that's why we chose to move to JavaFX. we need to study how to use it and how to apply this to our project.
this issue will probably be split into more issue and more people will be assign to this.(one or two)

**Comment by ArthurSap** [comment]
Also we intend to make these changes on a separate branch and then integrate them all at once (after doing test and etc) as to not harm the current work flow.

**Comment by yaelAmitay** [comment]
this issue is on hold until we decide about Ionic

**Comment by yaelAmitay** [comment]
We are moving to Ionic so this issue is no longer relevant
