### ISSUE TITLE
Vacations 

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#209]
#Everybody choose your vacations if you already know when you want them.

just to remind you, you need 2 weeks not including passover.

| Member  | Week 1 : 20.3 - 26.3 | Week 2 : 27.3 - 2.4 | Week 3 : 3.4 - 18.4 | Week 4 : 19.4 - 25.4 | Week 5 :  26.4 - 4.5 | Week 6 : 5.5 - 11.5 | Week 7 : 12.5 - 19.5 | Week 8 : 21.5 - 27.5 | Week 9 : 28.5 - 5.6 | Week 10 : 6.6 - 12.6 | Week 11 : 13.6 - 19.6 | Week 12 : 20.6 - 26.6 | Week 13 : 27.6 - 3.7 |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Alex |  |  |  |  |  |  |  |  |  |  | 🍁 |  | 🍁  |
| Yael |  |  |  |  |  |  |  |  |🍁  |  |  🍁|  |  |
| Arthur |  |  |  |  |  | 🍁 |  |  |  |  |  |  |  |
| Koral |  |  |  |  |  |  |  |  |🍁  |  |  |  |  |
| Ariel |  |  |  |  |  |  |  |  |  |  |  | 🍁 | 🍁 |

**Comment by kapalex** [comment]
I've added the table similar to the Intellij project to better show the schedule, will add at least one week soon
_The dates in the table are just approximations of "weeks" to include holidays that aren't considered working days._

**Comment by kapalex** [comment]
I've added one off week for me at the end of the semseter

**Comment by yaelAmitay** [comment]
I marked week 11 but the real dates are 16.6-22.6.(for me)
I'll pick the second weak later

**Comment by Kolikant** [comment]
how do you use this? the only way to add a sign for me is editing, and then I can no longer find what I'm looking for

**Comment by yaelAmitay** [comment]
put the icon at some point and then look at the preview and move the icon relative by what you see in the preview.

**Comment by koralchapnik** [comment]
I don't know yet.
Can I mark this in few more days ?

**Comment by yaelAmitay** [comment]
my 2 vections are: 1.6-7.6 and 15.6-21.6

**Comment by koralchapnik** [comment]
My two vacations are : 

- a week from the next week's meeting (cause I can't be physically  at the technion for the meeting so I'll consider that week as a vacation), dates will be updated when the meeting will held.

- I won't take vacation in the last year of the semester, don't know the other week as well
