### ISSUE TITLE
User can leave rating of routes and buildings

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#21]

**Comment by yossigil** [comment]
No progress for six days @assaflu !!!
no description @koralchapnik !
no  milestone @koralchapnik 
wrong label @koralchapnik do not mistake a label for a milestone.

FYI: @zvili @idabran @AdiOmari @orimarco @yh-github

**Comment by assaflu** [comment]
Closed issues, because issues #22 includes it in him.
