### ISSUE TITLE
make search queries accesible to the user for viewing

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#210]

**Comment by Kolikant** [comment]
this is now very obviously just GUI and would be open until we get the new gui in order

**Comment by AdiOmari** [comment]
You should have a function in the service that allows you to get a list of the user queries (as json). You can work on the service+server side for now.

**Comment by Kolikant** [comment]
the function itself exists (not in json), all the services of the features I am not closing since gui is missing have everything ready. I want to finish the features before I start learning how to turn them into services and I still have some features to handle

**Comment by Kolikant** [comment]
this is incomplete as none of the services are and this requires multiple of them
