### ISSUE TITLE
make search queries editable

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#211]
user should be able to change his favourite search queries

**Comment by ArthurSap** [comment]
An idea:
Just like waze/moovit have the options to save frequent search queries as "Home" or "Work" and stuff like that maybe we should add these options to define customized queries a bit better than to simply save addresses of favorite search queries.

**Comment by Kolikant** [comment]
need some sort of selection for the user to do this, good thing we can save these now!
