### ISSUE TITLE
duplicate database/ allow duplication of database as to support multiple disabillites

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#214]
as sugested by adi, we can duplicate our database in a way that each database would be meant for different disabillites thus using our software to support multiple dissabilites with a simple change.

**Comment by ArthurSap** [comment]
Why duplicate and not simply add new column(s)?

**Comment by Kolikant** [comment]
Simpler implimentation. Minimal change incode and in algorithms

**Comment by Kolikant** [comment]
putting Alex on this since he is the one in charge of the db. can choose to just ignore if he wants

**Comment by kapalex** [comment]
Will keep this in mind while working on #218

**Comment by kapalex** [comment]
As we said when planning this, it isn't going to be a feature, but a possibility open for the future.

The way this could be enabled in the database is setting the String `DATABASE_CLASS` in Review Manager.  This could be set after the user logs in for the first time and chooses what type of disability he is interested in.  Every disability will be its own class, and this way we keep separate reviews, but  locations are shared for all. 

This isn't enabled, but could very easily be added in some hypothetical future.
