### ISSUE TITLE
make a clearer interface for jxMapsFunctionality

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#215]
last semester I wrapped jxMaps functionality with another class, that class was being used instead. as adi sugested, we should make an interface class for the usage and inherent from it as to allow a change of jxMaps should we need it, and just to better program in general

**Comment by ArthurSap** [comment]
I can start working on such interface.
Should we have a discussion on what capabilities this interface should allow? As in what methods and etc.

**Comment by Kolikant** [comment]
I am the one who implemented the wrapper, it would be better if I implement the interface. A discussion is always great

**Comment by koralchapnik** [comment]
I also worked with jxMaps so I can help with that

**Comment by Kolikant** [comment]
we have move to ionic and are pushing the work done to be on the server side, so patching up the interface would be unnecessary as we are not planning on using it in the future and what exists already works
