### ISSUE TITLE
figure out why program isn't consistently working

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#216]
program sometimes works and sometimes doesn't. searches and navigation don't consistently end. need to figure out why

**Comment by yaelAmitay** [comment]
I think that location manager is the only thing in common for them. So maybe it's the problem. I'll check this.

Yael

‫ב-24 במרץ 2017, בשעה 12:16, ‏‏Ariel Kolikant ‏<notifications@github.com> כתב/ה:‬

**Comment by yaelAmitay** [comment]
Should we close this issue now that we are moving to ionic?

**Comment by kapalex** [comment]
With the new Ionic gui and DB implementation this is mostly irrelevant, so closing
