### ISSUE TITLE
Choosing a logging framework

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#217]
In order to be better able to analyze error and bugs, we want to add some logging framework to log the flow of the code

After some research I think the following solution will work :
- [Logback ](https://logback.qos.ch/) seems like a good logging implementation for java
- [SLF4j](https://www.slf4j.org/) is a popular logging facade for java.  A logging facade allows us to wrap the use of a logger with a generic interface, which will allow us to switch loggers seamlessly if the need for it ever arises.
- [graylog](https://www.graylog.org/) is a simple open source server that can put together logs from all users of the application, thus allowing us to view logs more conveniently (with the graphic viewer) and follow up on common crash that happen to multiple users.

@Kolikant @koralchapnik @ArthurSap @yaelAmitay 
What do you think?

**Comment by ArthurSap** [comment]
I'm familiar with log4j and its pretty cool (and isn't on the list).
graylog sounds nice but I think it could be an over-kill since we don't really have users on our system.

**Comment by kapalex** [comment]
logback is supposed to be the successor to log4j so I thought it might be better, if we decide as a team log4j is better for us I have no objections to it
In anyway with SLF4j it won't be a problem to use either

Graylog is definitely more of a "nice to have" than a must

**Comment by Kolikant** [comment]
I am a on team logback
And team Edward

**Comment by koralchapnik** [comment]
I also think log back is the best option.

**Comment by yaelAmitay** [comment]
I also think that logback sounds good.

Yael

‫ב-24 במרץ 2017, בשעה 23:35, ‏‏koralchapnik ‏<notifications@github.com> כתב/ה:‬
