### ISSUE TITLE
add estimate time of route and distance of route

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#221]
the user can view an estimation of the walking time of the route.

**Comment by Kolikant** [comment]
we discussed this at meeting today. we are all in favour of this feature (ripping off waze is not something we've been in any waze (see ehat I did there?) concealing) the discussion was, while google maps gives us estimaed walk time for a non-handicapped person, we need to take to consideration that the users are handicapped and will need more time. 

the agreement was having a constant multiplier of time, changeable by the admin, to be multiplied with the result given by google maps, thus allowing a more relevant time. 
I will open the issue and point it here

**Comment by yaelAmitay** [comment]
Can I close this issue for now? I think we should focus on moving to ionic.

**Comment by kapalex** [comment]
Leave it open, and put milestone as Sprint 2, we'll decide by then if we want to focus on it

**Comment by yaelAmitay** [comment]
also add distance of route.
