### ISSUE TITLE
add multiplier to route time, editable by admin

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#226]
as discussed today and explain in #221

**Comment by yaelAmitay** [comment]
wouldn't it make sense that i'll do it? If you want to add this feature I'm fine with that just let me know where can I find this constant.

**Comment by Kolikant** [comment]
I'm just putting all issues I open under myself since it was told not to have any "unmanaged" issues (all the issues I open except one are under me). it was what we agreed on in the first meeting, open up issues, put them under yourselves and then see who should do it in the next meeting.

**Comment by Kolikant** [comment]
oh! forgot to add the entire "editable" issue, with only the innerest of the ring able to edit it

**Comment by ArthurSap** [comment]
I was in charge of the Admin class last semester so let me know if you need some help here @yaelAmitay

**Comment by yaelAmitay** [comment]
Ok but let's talk about it to make sure we are on the same page

Yael

‫ב-3 באפר׳ 2017, בשעה 10:17, ‏‏Arthur Sap ‏<notifications@github.com> כתב/ה:‬

**Comment by yaelAmitay** [comment]
i'm closing this issue and #227 because they are not important and not so usefull and we have more important tasks.

if time allows I'll reopen them...
