### ISSUE TITLE
option to edit the time multiplier of routes, only for innermost ring

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#227]
only municipal employees should be able to do it, and it should be in an obvious gui interface for them as well #226

**Comment by ArthurSap** [comment]
I was in charge on Admin class last semester, do you want me to do it? @Kolikant

**Comment by Kolikant** [comment]
Sure
Assign yourself and deassogn me

**Comment by yaelAmitay** [comment]
How is it different from #226 ?

**Comment by Kolikant** [comment]
That one is gui, i think i had more differnces planed, but doesn't seem to be that different

**Comment by yaelAmitay** [comment]
Nevermind I moved it to the next sprint, we will talk about it later

**Comment by yaelAmitay** [comment]
I'm closing this, see reason in #226
