### ISSUE TITLE
Create skeleton

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#23]
Create stubs, classes and interfaces.
Shared with all the group members.

**Comment by kapalex** [comment]
Planned for next meeting Monday 5.12 14:30

**Comment by kapalex** [comment]
Delayed to 6.12 16:30

**Comment by yossigil** [comment]
You cannot have six assignees to one vague issue. I am closing this. This is too vague.
You can assign a specific issue to one/two people.

You cannot postpone planning to sprint 2. #11 

@idabran @zvili @yh-github @orimarco @AdiOmari
