### ISSUE TITLE
Database class rewrite

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#230]
I propose the following changes in design :
1. Interface `Database` to be created.  The interface will hold all the functionality that we require from our database, the following functions are what seems necessary to me
1.1. `Map<String,Object> get(string class, string id)`
1.2. `List<Map<String,Object>> get(string class, Map<String, Object> m)` get by matching fields
1.3. `List<Map<String,Object>> get(string class, latlng loc, double radius)` get by location, if no location for this class return empty
1.4. `List<Map<String,Object>> getAll(string class)
1.4. `string put(string class, Map<String,Object>)` return the id or null
1.5. `boolean delete(string class, string id)`
1.6. `string update(string class, string id, Map<string, Object>)`
2. `ParseDatabase` will implement the `Database` interface for our database
3. `DatabaseManager` to be removed
4. `ReviewManager`, `LocationManager` will be singletons that will use DI to accept `ParseDatabase` as the database object. 
5. All function within the managers will be implemented with RxJava to manage background operations more effectively.
6. The managers will all receive some sort of `onFinish` function in them, if the function received is null the operation will be blocking, otherwise it will run in a background thread.
7. `UserManager` may be left the same since it uses a different functionality of Parse, or we could create a separate management interface and specific parse class to accomodate this use case.  Since @Kolikant worked on it, you should decide how it should be done.

The new design offers a few advantages over the old one :
- Much more testable as the database is an interface that is injected, so when testing we can inject a mock database to test without connectivity to the database, which is quicker and more reliable.
- Allows us to change databases if we ever so choose
- Manages the background vs foreground thread work better
- Possibly a design separation between the database and user management, which I think would be good

Thoughts and change proposals welcome

**Comment by Kolikant** [comment]
All databases should have similar interface. since user manager is going to be used a lot woth the way we are taking the project this semester, it would have to be improved ad well, with your suggestions.
Making a different yet similar interface would be the way to go.

**Comment by kapalex** [comment]
I'm thinking of some `UserDatabase` interface that has functions such as `signIn`, `signOut`, `signUp`,`find`, etc. to fit the `UserManager's needs
We'll see if anyone else has any suggestions about this and I'll create issues to get this going

**Comment by Kolikant** [comment]
I may have misunderstood. User manager is not the interface for the user database? There is user database and above it the manager?

If that is so, sincei implemented user manager as usong the parse database, i could change that interface to match the database interface thus lowering needed change.

So i will justneed to reinterface witht he new database class that you would open, yes?

**Comment by kapalex** [comment]
When I wrote `UserManager` I meant the current implementation as is.
It uses function from the parse server directly such as sign in and sign up to manage the users, and I think rightfully so.
While _our_ database and user management system are one and the same, this is not true in many cases. In addition user management does in fact require different functions to operate well, without re implementing elements that already exist.

So what I propose for users is that we have a similar but separate interface for `UserDatabase` that exposes the required function as mentioned above, which will be implemented by `ParseUserDatabase`, which can then be used by the adjusted `UserManager`(I think of the managers this one probably requires rewriting the least, thus the question of whether or not to do it at all) or used directly (preferably the former for lower coupling)

**Comment by Kolikant** [comment]
I still don't believe i fully understand you, we will have to talk in person

**Comment by Kolikant** [comment]
Oh
So you want a parseUser to be used by parse manager to be used by user manager to be used by application?

**Comment by kapalex** [comment]
More or less
Basically an interface that has the functions of a generic user management system
An implementation of such an interface for a parse server
The usage of such an implementation by us = UserManager
and so on

**Comment by Kolikant** [comment]
well, working on similar interfaces for all of the database is the good design choice.

however, since userManager does all the usage of parse. and if I understood correctly the option we have is to move THAT usage to the jurisdiction of a parseServer class (implementing the usermanagement interface which would be another interface like all the other database, but with different functions outside because of user's uniqunes) and then use that parseServer. it seems to me like a bit of a hussle, if we are using the same parse server regardless. 

just changing the interface itself, as to have similar names, to be more intuitive with the change of the other databases, should do the trick. 

if I am completely off to what you were saying, we should postpone the decision until next meeting (have I ever mentioned oh how I loath texting communication? it's like trying to sew using a very rust axe)

**Comment by yossigil** [comment]
Keep up the good work

**Comment by kapalex** [comment]
Since usermanager does work well (unlike many other parts of the database) it isn't necessary to change, so I agree with you it can be just minor name changing
The change would provide better test ability but since it's not reusable there is not much gained here otherwise

**Comment by kapalex** [comment]
Well the discussion seems to be done, so I'm closing, actual implementation issue is #218
