### ISSUE TITLE
auto delete irrelevant sessions of parse

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#233]
not a bug per se, but is something I was struggling with from day 1 of the project last semester. 
each time a login occurs, a session is started, each time a logout occurs a session does not stop... and since we have periodic testing of our work, these open sessions accumulate to reach hundreds and thousands of useless sessions. hard to determine which are closed and which are open.

Parse auto deletes sessions that are X days old, thus not allowing an explosion, but it's still something that is wrong to leave as is. 

I however have no idea how to stop it and would love some help

**Comment by ArthurSap** [comment]
As we are refactoring the databases and move into Ionic shouldn't we wait with trying to solve this? It might disappear as changes occur

**Comment by kapalex** [comment]
The changes planned are do not involve UserManager so this is unlikely to be resolved with the refactoring @ArthurSap

**Comment by Kolikant** [comment]
This has to do with login, somehow i would need to track down what causes the explosions, being able to stop jenkins from running usermanager tests (which is an abillity we now have) should help out in containing it and finding out what is exploding and why

**Comment by Kolikant** [comment]
repeatadly unable to figure out what is causing this explosion of sessions, as all sessions done in tests have been closes, was unable to recreate an explosion. a script on parse should be the solution, once I figure that out

**Comment by Kolikant** [comment]
well, having talked to all members about this in numerous occasions (though never discussed in an actual official meeting and thus not recorded) it seems that all agree that this is not an important problem, so I am closing the issue until it proves itself otherwise.
