### ISSUE TITLE
Considering comment's like/dislike

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#236]
In the calculation of best reviews and the appreciation of the user's activity in our app, we should consider the number of likes and dislikes the user's comments have.

**Comment by AdiOmari** [comment]
What is a user review, is it +1 or -1 (like/dislike)? or is it a score. One (possible additional) way to weight the user is his representatives of the majority.  Or in other words: how much of the time does he agree with the majority of the voters on each location.

**Comment by kapalex** [comment]
The review is a 1-5 star rating + free text, so this wouldn't be as easy to implement

**Comment by koralchapnik** [comment]
I think that it is like considering the number of likes/dislikes the user's comment got, or deciding that if user likes some other user's comment, they agree.

**Comment by Kolikant** [comment]
notice that I added the "user monitoring" label for all issues regarding user monitoring

**Comment by koralchapnik** [comment]
Thanks

**Comment by ArthurSap** [comment]
Should we take amount of comments on review as consideration as well?

**Comment by koralchapnik** [comment]
There is consideration in the user's comments likes/dislikes, more details in issue #228
