### ISSUE TITLE
Ionic and web services

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#238]
As I wrote in the previous issue about Ionic and Maps( #223 ) we need to create web services for each of our functionalities. for example we need to create a web service that allow the user to login/logout.
I chose to create REST web services because REST web services are simple, easy to undesrtand and work good with Ionic.

# Rest Web Services
##Rest
REST is a way to communicate between a server and a client. the client can ask for specific value form the server using URLs and he can also change value on the server using URLs.
If you don't know anything about rest I suggest you read about it over the internet.
we hae 4 operationa:
- GET - > get data from the server (access the value by some URL)
- POST -> add value of the server (access the value by some URL)
- PUT -> update value of the server (access the value by some URL)
- DELETE -> delete value of the server (access the value by some URL)

## Create a REST WebService
Let's start with creating a simple webservice and then we'll use this web service from our Ionic application.
We'll use Spring Framework. add the following code to your` pom.xml `file:
```
<properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	<start-class>rest_test.Application</start-class>
</properties>
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.2.RELEASE</version>
</parent>
<dependencies>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
</dependencies>
<build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>2.3.2</version>
			<configuration>
				<source>1.7</source>
				<target>1.7</target>
			</configuration>
		</plugin>
		<plugin>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-maven-plugin</artifactId>
		</plugin>
	</plugins>
</build>
<repositories>
	<repository>
		<id>spring-releases</id>
		<url>http://repo.spring.io/libs-release</url>
	</repository>
</repositories>
<pluginRepositories>
	<pluginRepository>
		<id>spring-releases</id>
		<url>http://repo.spring.io/libs-release</url>
	</pluginRepository>
</pluginRepositories>
```

In addition create a package named 'rest_test' then  create 2 files in this package:
1. file named Application.java with the following code:
```
package rest_test;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

2. file named TestController.java, with the following code:
Note: we are not going to specify the type of the resquest so you can use GET/POST/etc' but you should specify it in the your code.
```
package rest_test;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
@RestController
public class TestController {
    @RequestMapping("/test")
    public int test() {
    	return 42;
    }
}
```

now run the file Application.java(you should make sure you don't already  have an application that  running on port 8080). go to your favorite browser to : http://localhost:8080/test
You should see the number 42.
**make sure to terminate the application before running again because you need to free the port 8080**

now we have a webservice. 

## Add JSON to your web service
Json is a format for transferring data between servers and clients.
from Wikipedia:
> an open-standard format that uses human-readable text to transmit data objects consisting of attribute–value pairs. It is the most common data format used for asynchronous browser/server communication

We are going to transfer data from our webservice to our application and we are going to do it with JSON. 

1. First of all we want our webservice to return some data from some class.
add a class named Test.java with the following code:
package rest_test;
**Do not forget the getters and setters!**
```
public class Test {
	public String str;
	public Integer num;
	public String getStr() {
		return str;
	}
	public void setStr(String str) {
		this.str = str;
	}
	public Integer getNum() {
		return num;
	}
	public void setNum(Integer num) {
		this.num = num;
	}
}
```
2. change the TestController.java to:
```
package rest_test;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {
    @RequestMapping("/test")
    public Test test() {
    	Test t = new Test();
    	t.setNum(7);
    	t.setStr("Green");
    	return t;
    }
}
```

3. now run the Application.java, go to the browser to: http://localhost:8080/test
you should get:
`{"str":"Green","num":7}`

you can see yourself how the class Test transferred to text data that you can easily understand.

the next step is to use this server with our Ionic application and display the return value.  look at #243.
have you always wished to test your rest code? look no further #297

**Comment by kapalex** [comment]
updated your formatting, use 3 ` for code block

Great job on the explanation

**Comment by AdiOmari** [comment]
Great job Yael!

**Comment by yaelAmitay** [comment]
I update this issue to include Json and the next issue in this series is about using this webservice from the ionic app #243 .

**Comment by AdiOmari** [comment]
@AmitOhayon @geniashand  Amit and Genia, I think this tutorial and example by Yael is helpful for services creation and will save you some research.

**Comment by Shahar-Y** [comment]
Hi Yael, @DavidCohen55  and I tried following your guide of creating REST webservice in our project and encountered these problems:
![image](https://cloud.githubusercontent.com/assets/23077804/24744025/373cf08e-1ab9-11e7-8a46-b40b89168fba.png)
We haven't been able to fix it. do you have any idea what to do with it?
Thanx

**Comment by yaelAmitay** [comment]
I didn't add this dependecny, was is on your project before?

**Comment by DavidCohen55** [comment]
We already had this dependency in our project like few others that we getting warnings about,
it seems that there was a problem when we tried to add this to our pom.xml file and we don't know how to figure it out...

**Comment by yaelAmitay** [comment]
I think you can ignore this warning(there is a way to suppress a warnings in the pom file).
(from what I see from online search about this warning)

**Comment by Kolikant** [comment]
can you add a post, put, delete example?

**Comment by yaelAmitay** [comment]
POST example: /login?name=BLABLA&password=BLABLA
```
@RequestMapping(value = "/login", method = RequestMethod.POST, produces = "application/json")
	@ResponseBody
	public Integer login(@RequestParam("name") String name, @RequestParam("password") String password) {
		.....
              }
}
```

**Comment by yaelAmitay** [comment]
Do you want example for PUT and DELETE too? It's the same

**Comment by AdiOmari** [comment]
@MosheEliasof take a look at this issue, it can help you with the creation of the web services.
