### ISSUE TITLE
Review contains User

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#239]
In order to consider the helpfulness in the calculation of the best reviews, I want to get an User object from
the Review class.
Last semester, Assaf asked me that the Review will contain only the user name and not the user object.
Do you have any objection that the Review class will contain the user itself and not only it's name?
@ArthurSap @yaelAmitay @Kolikant  and especially @KaplanAlexander (who is responsible for the Database)?

**Comment by Kolikant** [comment]
The trouble was the inabillity to stpre complex classes in database, this save would be duplication and is unadvised since updating users would require updating all the reviews who will now save invalid users.
Using a name allows you to get the user object from the user Manager

**Comment by koralchapnik** [comment]
Ok, thanks

**Comment by yaelAmitay** [comment]
" updating users would require updating all the reviews who will now save invalid users." why? we use pointers.

**Comment by yaelAmitay** [comment]
Nevermind I see you closed this issue

**Comment by koralchapnik** [comment]
I am joining to Yael's question..

**Comment by Kolikant** [comment]
We dont bring all the database to memory :0

The users and reviews are stored in the database, pointers in this case would indead just be the names, for user manager to find them

**Comment by kapalex** [comment]
I wasn't in charge of this part in the database last semester but I am planning on rebuilding it
I definitely think you can put a user in the review.
The implementation in the database should be as follows :
- User A is stored in DB
- User A writes review B
- When storing B in DB we will store in column user the unique id of A in the DB 
- When retrieving the review we will retrieve the user from the DB as well

as long as the user implementation doesn't depend on review (as to not create circular dependency) this should work in my opinion

**Comment by koralchapnik** [comment]
Thanks @KaplanAlexander , I think I will do that change

**Comment by Kolikant** [comment]
Users now change, with monitoring, more than before.
Having user in multiple reviews would mean having different information in each at every time.

Saving a copy, or picture is possible, but after a change by a different review it is meaningless

You can instead save information you need to find user and have a way of accessing it theough the database, offering a single coherent user

**Comment by kapalex** [comment]
@Kolikant  I'm not sure I understand your concern
A review in the DB holds a unique id of the user
If the user changes the id is still the same, and many reviews can use it
The id _is_ the easiest way to find the user

**Comment by Kolikant** [comment]
Exactly
I keep saying that name or id is just fine.
But they are suggesting saving the User, all of it, a copy, that is what I am against

**Comment by kapalex** [comment]
No, what they are saying is that the **client** side review will hold a user.
In the DB, the review will hold an id
In the client, when restored from the db, that id will be restored and return a user, so the client can see a review containing a user.

**Comment by Kolikant** [comment]
If you are bringing it from the database using userManager, and work with that one, remmembering to update the user with userManager when finished it is absaloutley fine, but undifferent from what exists today though.

No reason not to allow it excpet synchrony which we decided to disregard long ago (last updater ftw)

**Comment by AdiOmari** [comment]
I see that you agree, the review object should contain the user object (reference to it), but in database the review should contain only the key field of the user.

**Comment by Kolikant** [comment]
If you want a field for user for convenience rather than refetching each time, it would hurt synchrony

For updating a user means putting a user version to overrode the older one, so two reviews updatimg will delete rather than add on

If a user field is significantly more convenient that fetching updated version each time you should do that and we would deal with synchrony later (or ignore it)

**Comment by Kolikant** [comment]
We will have to deal with synchrony regardless, for this change just makes it more frequent on an existing problem.

So I take back all I said, I didn't understand you untill now and you should deffinetly add a field to user side revoew to be read once and put under usermanager the issue of synchronising these updates

**Comment by kapalex** [comment]
Assuming only the user himself can change data that is saved in the user class (as should be the case), we can enforce a single log on requirement, so a user can't log in from two different places.
This way we have only one source for writes, and other users accessing the user info with the review, shouldn't be able to edit it so they only read.

**Comment by kapalex** [comment]
Wait, never mind, with the new features you are right and he won't be the only writer, so yes, we should concern our selves with the synchronization problem, or redact the user score feature

**Comment by Kolikant** [comment]
That was the case so far, but likes on reviews by user change his helpfullness, meaning a change in his info needs to occur, made by ither users.

**Comment by Kolikant** [comment]
Gott love text communication

**Comment by kapalex** [comment]
Well we got there eventually 🥂

**Comment by koralchapnik** [comment]
I can use the user manager,  it's not really a problem

**Comment by koralchapnik** [comment]
Decided to insert the user object to the Review.
Thank you all
