### ISSUE TITLE
Ionic and maps

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#242]
in the previous issue (#223) we talked about ionic in generally . In this issue i'll explain how to display a map with your current devices location. (This is a better explantion than the one that appeared before I suggest you follow this one)

**First of all, these instructions are based on this link:
https://www.joshmorony.com/ionic-2-how-to-use-google-maps-geolocation-video-tutorial/
but It didn't work for me so I made some changes and wrote it all for you here.**

1. create an Ionic project:
```
ionic start maps blank --v2
cd maps
```

2. get a googleMap key from https://developers.google.com/maps/documentation/javascript/ click the "get a key" button. keep the key you will need it in a few minutes.

3. add the following line to file: src/index.html:
`<script src="http://maps.google.com/maps/api/js?key=YOUR_KEY"></script>`
put it before this line:
`<script src="cordova.js"></script>`
**please note to insert your key here.**

4. go to the page you eant to add the map to. If you didn't create page just go to src/pages/home/home.html:
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Map
    </ion-title>
  </ion-navbar>
</ion-header>
 
<ion-content>
  <div #map id="map"></div>  
</ion-content>
```

5. go to the home.scss in the same folder as before and add the following code:
 ```
  page-home {
      #map {
        width: 100%;
        height: 100%;
      } 
    }
```

6. go to home.ts in the same folder as before and add the following code:
please note: this file is different from the link above!
```
import { Component, ViewChild, ElementRef } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Geolocation } from '@ionic-native/geolocation';
declare var google;
 
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
 
  @ViewChild('map') mapElement: ElementRef;
  map: any;
  geolocation: Geolocation
  constructor(public navCtrl: NavController) {}
  
  ionViewDidLoad(){
    this.loadMap();
  }
 loadMap(){
	this.geolocation = new Geolocation();
	this.geolocation.getCurrentPosition().then((position) => {
        let latLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        let mapOptions = {
            center: latLng,
            zoom: 15,
            mapTypeId: google.maps.MapTypeId.ROADMAP
         }
        this.map = new google.maps.Map(this.mapElement.nativeElement, mapOptions);
       }, (err) => {
           console.log(err);
       });
  } 
}
```

7. now go to your console and insert the following commands(afirst go to the project folder):
```
ionic plugin add cordova-plugin-geolocation
npm install --save @ionic-native/geolocation
```

8. insert the following line to your console in order to view the app in your browser:
`ionic serve`

You now should be able to view the map and the map should point to your location.

See #238 to learn how to create your web services

**Comment by koralchapnik** [comment]
Great job!
