### ISSUE TITLE
Ionic USE Web service in Ionic app

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#243]
In the previous issues we learned about Ionic( #223) , and we displayed maps( #242 ) and create web service( #238 ).
In this issue we'll use the Web Service that we create from our Ionic app.
___________________________________________
UPDATE: I forgot to add this step:
*Insert these lines to the cmd:
```
ionic plugin add --save cordova-plugin-http
npm install --save @ionic-native/http
```
_____________________________________________
1. create a new service by using this command:
`ionic g provider LoginService`
I named it LoginService but it won't do login right now it's just an example.
Note: after this command you'll have a new folder in your project named "providers". In this folder you'll have a new file named "login-service.ts"

2. change "login-service.ts" as follows:
```
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';
import {Observable} from 'rxjs/Observable';
import 'rxjs/Rx';
@Injectable()
export class LoginService {
  constructor(public http: Http) {
    console.log('Hello LoginService Provider');
  }
  callHttp() {
    return this.http.get('http://localhost:8080/test').map(res=>res.json())
	.catch(this.handleError);
  }
   handleError(error) {
        console.error(error);
        return Observable.throw('Server error');
    }
}
```

3. In your page(if you didn't create a page then do it in home.ts but you should learn how to create pages) add the following code that use the service:
```
import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';
import {LoginService} from '../../providers/login-service';
@Component({
  selector: 'page-login',
  templateUrl: 'login.html',
  providers: [LoginService]
})

export class LoginPage {
    str: any;
   num: any;
   serve : any;
  constructor(public navCtrl: NavController, public navParams: NavParams,serve: LoginService) {
	this.serve = serve;
  }
  ionViewDidLoad() {
	this.serve.callHttp().subscribe(data => {
        this.str = data.str;
	this.num = data.num;
    });
  }
}
```
**Note** that here we know that the json that will be return has 2 attributes: "str" and "num" So we asked for their value.

4. By now the values from the http call are in the variables "str" and "num" we want to display them. So add the following code to your html page(if you didn't create a new page then do it in "home.html"
```
<ion-header>
  <ion-navbar>
    <ion-title>login</ion-title>
  </ion-navbar>
</ion-header>
<ion-content padding class="login">
	<p>{{num}}</p>
       <p>{{str}}</p>
</ion-content>
```
5. go to src/app/app.module.ts and add the service to the providres:
*you might not need it but do it just to make sure
**you should only add the name of the service to the provides that already exist. meaning add only "LoginService"
```
...
 providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
	**LoginService**,
	NavigationService
  ]
...
```
and import the service:
`import {LoginService} from '../pages/login/LoginService';`

6. now insert `ionic serve` in the command line and you should see "7" and "green". this is the data that came from our webservice.

**note: you might have CORE ptoblems(as we had) which mean you don't get a response from the servers. In that case take a look the #287 . the last commit in this issue solve this problem.**

**Comment by AdiOmari** [comment]
Nice explanation Yael.
@TomPalny @tanyabrokhman @yossigil @idabran this can be useful to other projects as well (that use ionic). It is referenced in the main ionic issue.

**Comment by yaelAmitay** [comment]
I updated this issue
