### ISSUE TITLE
implement new feature issues in gui

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#245]
i have had a few of the new features that I made (and you guys too probably) remain in open issues, despite the only thing missing being the gui, which since the gui is being remade completely and still in progress for the basic, mens they are open purposelessly. so I am pointing through this issue to all the finished features that just need GUI, so that I could close them, you can do the same, if you want

**Comment by Kolikant** [comment]
#211 #212

**Comment by ArthurSap** [comment]
Is this still relevant? @Kolikant

**Comment by Kolikant** [comment]
this includes all the features we made (so far added here are the ones that I made) when we were on the fence about ionic, so none of them have gui. it is still relevant as they now don't have any gui either and I will close it when it's done, don't worry

**Comment by Kolikant** [comment]
this has basically become now, allow naming search queries. since it is the only feature i implemented server side on queries that deosn't yet have an issue. it will be attempted to be completed with the others
