### ISSUE TITLE
project not running (nor tests)

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#246]
i did the pull as instructed, but the tests and the application itself no longer run. can anyone help me?

@KaplanAlexander @ArthurSap @koralchapnik @yaelAmitay

**Comment by Kolikant** [comment]
not a bug or compilation error, just doesn't run because of...unrecognized issues

**Comment by kapalex** [comment]
You need to run it from the server-side directory
It's working on my pc and in jenkins

**Comment by Kolikant** [comment]
I am. 
I'm calling you

**Comment by Kolikant** [comment]
Yael helped me.
anyone else having this problem, should (after pulling) open a new workspace, import maven project the thingy, update maven. and then close and reenter eclipse.

we are no sure why this helps, but it has got something to do with dark vodoo magic for sure
