### ISSUE TITLE
three steps solution

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#247]
seeing as that @yaelAmitay was able to prove the ability for us to switch to ionic while mainatining use of jxMaps, and by the assessment that ionic and it's interface would take a big portion of our work this semester. and seeing as we started the semester coming up with new features for us to implement (before offered to use ionic) and thus have both new features and the switch to ionic; 
here is what I propose in terms of milestone: Alex and Yael continue the good work on the inestracture and ionic,  but the rest
milestone one: close all the new features (all of them; all those not done by it could be left if time exists but would be lower in priority)
milestone two: provide all features as services for ionic
milestone three: work on ionic

this should allow us a clearer picture of what we are doing at any given time and allow us to move faster to all work on this new framework that would be the majority of the project, while not neglecting the features we want to add.

opinions? @yaelAmitay @koralchapnik @KaplanAlexander @ArthurSap

**Comment by ArthurSap** [comment]
I can't fully agree with you about step 1 - if we implement new features right now without regarding the ionic framework we might have to do extra work later to convert them to properly work with ionic (hence doing extra work for nothing). I think we need to give @yaelAmitay a hand to head-start ionic faster so we would have some basic infrastructures to work with and only then implement new features.

**Comment by yaelAmitay** [comment]
I think he meant that some people will work on the server services(interfaces) and the others will work on the ionic.
I think we should decide togather on the URL of the interface. 
and create stubs for the webservices interfaces as soon as we can

**Comment by Kolikant** [comment]
These features are wholy and completely within the server side of what would be the new project.
Think of all previous semester other than gui, as the server side.

All the features we have given this semester are server side as well, implementing them would not intervee at all, and is not a consoderation ionic would have in interfacing

**Comment by yaelAmitay** [comment]
and create stubs for the webservices interfaces as soon as we can

**Comment by Kolikant** [comment]
We should finish the server side as there are not a lot of features left, so we can all continue to work on ionic.
Obviously if more server side feature come up, we can always change, but as to make the transition to ionic as our main concern, these three steps (milestones) would get us organized about it

**Comment by kapalex** [comment]
I agree with @ArthurSap in the thought we should focus on ionic first.
Even though our project is split into server side and client side, we might still find better ways to implement new features once we start working with the new design (services), and this could affect the way we implement features.

My opinion is that the first sprint should be entirely dedicated to ionic + database features (I could work on the database, and the 4 of you could work on ionic client side +services, or some other division of work) while also fixing issues raised by SonarQube (some will be deleted together with old code, but some we will have to take care of manualy)
Then in the second sprint we could continue adding the features we discussed.

**Comment by Kolikant** [comment]
The point is to have order in work, because now most people dont know what to do. "Help with ionic" is ill defined right now and Yael if I understood her correctly wants to finish more before we can start with using the services.

By first finishing what we know and understand, moving to something else we can learn we would be able to all get to ionic with a working system and understanding of our work all the way.

If you want to start with ionic, it would mean that mostly people would just study ionic and then wait for Yael.

Regardless as long as peoole know what to do i care little as to what order it should be done.

If you want to start with ionic, open issues as to what that means, otherwise it means most peoole dont work

**Comment by kapalex** [comment]
We have until the end of the sprint to define the exact work that should be done with ionic, while this sprint is the exact time to study and plan what we want to do with it.
In my opinion two people should be put on the gui part of it, which would involve learning to work with typescript, html and such that are required by ionic, and implementing a good looking interface, while two others can work on the services .  A service should be created for most packages from the current project, so plenty of work can be defined here.

**Comment by Kolikant** [comment]
That is too much in the air. If you want everyone to first work on ionic, let us make plans to bring everyone to do just that.
We need to bring everyone to understanding how what and where
Have the option to do so in the project itself
All that before, it all needs to be defined soon.

In the meantime, we should work on the small features that we all opened.

Here are the issues we ahould open:
1) everyone runs their own ionic example as instructed by yael
2) everyone outsources one service.

Open that and have everyone assigned to it, to be conpleted soon and we could all be alligned, if you want to move to ionic before the features

Sound good?

**Comment by kapalex** [comment]
That issue sounds like a good idea, although i'm not sure what exactly it should be. 
You're welcome to open the issue

About more concrete issues, I agree. those should be defined by the end of the current sprint, during this week we should start thinking of which services we want to expose, and open issues to implement them
@yaelAmitay @ArthurSap @koralchapnik

**Comment by Kolikant** [comment]
Obviously all issues given as gui, I suggest the next (if possible) to make an annotation of `@service`
For us to mark methods that should (more ot less) be services, and for everyone to pass on their classes and mark

**Comment by kapalex** [comment]
I think it would be better to create a discussion issue to talk about which services we need, in code would be hard to find
I'll open it

**Comment by Kolikant** [comment]
Again, all the gui,
The discussion will not cover all the methods we need, or even all the conseptual methods we need but still a good start

**Comment by ArthurSap** [comment]
I think deciding the services would be a lot simpler and quicker if we would meet up and discuss it.

**Comment by Kolikant** [comment]
EVERYTHING would be a lot easier if we could meet and discuss it.
I am always in favour of THAT

**Comment by kapalex** [comment]
All in favor but until that happens, some discussion still needs to happen as the next meeting is very much near the deadline

**Comment by Kolikant** [comment]
Yes
A fot discussion is the minimum amount of work we can do for this, so we should atleast do that

**Comment by yaelAmitay** [comment]
So we decided to talke about the services on #250 , right?
Hopefully this week we also open issues for the Ionic parts
So by the end of the week everybody will be able to start working.

**Comment by Kolikant** [comment]
Yes.
Hopefully
