### ISSUE TITLE
Choose and Calculate best n reviews for rating

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#25]
Given a point in the map the user can get the best n reviews and see the total rating of the point.
(Decide n's value by the issue's assignee)

**Comment by koralchapnik** [comment]
what do you say about unique class that responsible for calculating the best x reviews that exports diverse methods for choosing the best x reviews rather than one method responsible for that ? 
@yaelAmitay @assaflu @ArthurSap @KaplanAlexander @Kolikant

**Comment by Kolikant** [comment]
no need.
as the planning stands the social network supports nothing other than free text and like/dislikes.
there is no purpose in anything elaborate to it. seems like a method

**Comment by koralchapnik** [comment]
Well, I decided to dedicate a class for that

**Comment by yossigil** [comment]
I would change to 'n' reviews. 'x' may sound promiscuous...

**Comment by Kolikant** [comment]
in Review, you have said that the review is on routes, note that Reviews should be on Locations,
also the constructor of a review should set it's rating to zero

**Comment by koralchapnik** [comment]
It's on routes and also locations.  I am waiting to the class location to be built and then I'll change it

**Comment by koralchapnik** [comment]
after i'll add the class Location i'll change it.

**Comment by Kolikant** [comment]
class Location has already been added by me (I needed the stub) but you should assign it to yourself
