### ISSUE TITLE
get understanding of ionic for work

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#251]
we decided at #247 to rush as fast as possible to work on ionic, even before completing the new unfinished features.
thankfully, @yaelAmitay supplied us with tutorials to get to a good level of understanding.

everyone planning to work on ionic needs to complete these tutorials before the sprint ends

more issues as to learning and defining work on ionic would probably come after people know what it is

her toturial starts here:
#223 

- [x] Kolikant
- [x] koral
- [x] athur

**Comment by yaelAmitay** [comment]
can we close this issue?

**Comment by koralchapnik** [comment]
yes

**Comment by Kolikant** [comment]
No..... I havent done it someone marked it for me
