### ISSUE TITLE
server side login

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#253]
create a service that support a login from user.
this is going to be in the next url:
localhost/login?user=NAME&password=PASSWORD

the server should remember the login for X=10 minute.
the server should return a token not a cookie. 
whenever someone want to send a request he need to add the token. 

Everybody pay attention to this: @Kolikant , @KaplanAlexander , @koralchapnik , @ArthurSap 
**add the token to your requests in the  header.(client side)
in your server side always check if the token in the header is valid.(server side)**
for code example look at NavigationService.ts and NavigationService.java

client side #252

**Comment by Kolikant** [comment]
I dod the login las semester, i would like this issie as well

**Comment by yaelAmitay** [comment]
I already start working on it? do you mind if I keep it?

**Comment by yaelAmitay** [comment]
Right now when someone send a login request I just create a new User and him to the sessions map.
But I'll change it to check if the user really exist

**Comment by Kolikant** [comment]
It has been a chunk of my work last semester
And it leaves me with nothing to do this semester

Not untill we have the discussion i wanted to solit the work.
But since it seems we are all coding now, I will need to either continue loging and user management or be suggested something else to be under me

**Comment by yaelAmitay** [comment]
As you can see I already start working on it, so i'll keep it.
BUT don't worry we have a lot of work to do.
please note that you have #257 .

**Comment by yaelAmitay** [comment]
as we said in #269 we should keep a mapview for each session.

**Comment by yaelAmitay** [comment]
I'm closing this issue, I'll open more issue if needed that are more specific. 
BUT everybody should take a look at this issue and add the token to the header of their requests!
