### ISSUE TITLE
client side leave a review on location

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#254]
1. user click on location on the map
2. a small window is open the user leave there the review and send it to the servers.
3. if there already other reviews on the location the user can view them.

In the future the user will be able to choose if the location is a street or some type of location.

server side #255

**Comment by ArthurSap** [comment]
But it's still not perfect :(

**Comment by yaelAmitay** [comment]
oh sorry, you can reopen this or create issue with the specific things that missing
sorry again :|
