### ISSUE TITLE
server side search(simple search)

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#258]
create a webservice that support searching a location
localhost/search?query=BLABLA
should return the latlng(and maybe more data).

Accept the requesr iff the token is valid.

client side #257

**Comment by yaelAmitay** [comment]
@Kolikant  do you want this issue and issue #257 ?

**Comment by Kolikant** [comment]
Assign me
I wont reach a computer for a long time now

**Comment by Kolikant** [comment]
need to figure out how to add the actual query text to a variable of the rest part (which is what I assume is so great about rest)

**Comment by AdiOmari** [comment]
Oh I forgot to add " and we are not sure its implementation is thread safe"

**Comment by Kolikant** [comment]
@AdiOmari I don't think I understand what you are referring to

**Comment by yaelAmitay** [comment]
>  need to figure out how to add the actual query text to a variable of the rest part (which is what I assume is so great about rest)

@Kolikant , did you figured it out? I see you closed the issue so I assume you did, let me know if you have problems

**Comment by yaelAmitay** [comment]
@Kolikant 
accept the request only if the token in the header of the request is valid
look at NavigationService.java for example.
