### ISSUE TITLE
How should we display review adding?

### ISSUE THREAD

**Issue by ArthurSap** [TechnionYP5777/SmartCity-Accessibility#260]
Upon pressing a location on map and choosing to add review - should we open a whole new window for the user to add the review in it? Or a mini window (without shifting to a new screen) and the user could add the review there (i.e tiny pop-up window while still displaying the map in the background)?
For now I started to implement it as a whole new page, worst case we'll switch to the mini window.
Opinions?
@Kolikant @KaplanAlexander @koralchapnik @yaelAmitay

**Comment by yaelAmitay** [comment]
I think it should be on a new page

**Comment by koralchapnik** [comment]
I also think it should be in a new page, and indicating the location which the user reviewing

**Comment by Kolikant** [comment]
Mini window seemsto ne more intuitive, but it hardly matters

**Comment by yaelAmitay** [comment]
the user need to write about the location I think that mini window is too small. But I also think that it doesn't matter as long as it works

**Comment by ArthurSap** [comment]
For now we'll go with a new page. If we'd want to change this is the future we'll re-open this issue.
