### ISSUE TITLE
JBoss - eclipse plugin for easier development with Ionic

### ISSUE THREAD

**Issue by ArthurSap** [TechnionYP5777/SmartCity-Accessibility#262]
## JBoss
JBoss is a plugin for eclipse that help with web developing (among the rest) and hybrid mobile development (using Ionic and Cordova!)
### IMPORTANT NOTICE:
This plugin **helps** developing so some features are still missing!
If you want to create a new page, a new provider and etc. you still have to do it form the cmd (as explained in Yeal's guides).
This plugin helps creating the pages using a mechanism similar to drag and drop. E.g - you want a list? Drag it to where you want it to be, define what it will show and the plugin will inject the appropriate code.

### Installing:
Simply install it into eclipse from [here](http://tools.jboss.org/downloads/devstudio/neon/10.3.0.GA.html#marketplace)

### Importing the project
You must first need to have the project itself in your work-space (if you want it to be connected with the git that is), so if you hadn't cloned the client-side folder yet - do it.
Next make sure **ALL** the files are in there (when Yeal originally pushed the project git automatically ignored most of the files):
![image](https://cloud.githubusercontent.com/assets/15543389/24755868/7bb45cae-1ae4-11e7-8469-57d1343b7416.png)
After you made sure you have all these files do the following:
In eclipse: File -> Import... -> Mobile and choose the only option
![image](https://cloud.githubusercontent.com/assets/15543389/24755946/b2a06898-1ae4-11e7-97e0-12e3b2366e74.png)
Select the `client-side` directory and check the `mapapp` box
![image](https://cloud.githubusercontent.com/assets/15543389/24756032/09b024b6-1ae5-11e7-99b4-e5839b4c8824.png)
And that pretty much it.

### Small example

As I said before - if you want to add a new page and provider you still need to use the regular cmd procedure, but if you want to add a text box for example..
Choose your page, go to "Palette" tab, and click it!
![image](https://cloud.githubusercontent.com/assets/15543389/24756172/868fb104-1ae5-11e7-8787-bc30c3bfd521.png)
Define whatever you want
![image](https://cloud.githubusercontent.com/assets/15543389/24756213/ac1b2b10-1ae5-11e7-8af2-f68a335b461f.png)

And you're done! You got yourself a nice customized text box (or whatever you want).
![image](https://cloud.githubusercontent.com/assets/15543389/24756259/c734be34-1ae5-11e7-927b-0508ff7fb553.png)

I'd be happy if you tried using it to see if I was simply lucky to have it easily installed or if I missed something,
@koralchapnik @Kolikant @KaplanAlexander @yaelAmitay

**Comment by koralchapnik** [comment]
Thanks!  I'll try it today :)
