### ISSUE TITLE
Change Review to contain the user itself instead of the user name

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#263]
we decided on issue #239 to replace the user name in Review class with the user object

**Comment by koralchapnik** [comment]
@KaplanAlexander Can I do the change and you'll do the relevant changes in the DB ? 
which means I will put the relevant code in LocationManager in comment

**Comment by kapalex** [comment]
Yes it's fine if you change it, I'll work on the DB on a separate branch anyway

**Comment by koralchapnik** [comment]
Ok, so I am putting the relevant code in the Location Manager and it's tests in comment

**Comment by Kolikant** [comment]
This has a lot to do with the user db synchronizyion, remmemberto update the user information at the db every time you alter it

**Comment by koralchapnik** [comment]
For that I need the DB to be implemented.
whenever the review is updated in the DB it should update the user too.
it's under the DB responsibility

**Comment by Kolikant** [comment]
No
You took the user as a field and are updating it
The user is not under review jurisdiction

If you alter it and want it saved, you save it

The review db stores and takes care of onky the reviews

**Comment by koralchapnik** [comment]
I am not altering the user inside the Review class.

**Comment by Kolikant** [comment]
Oh, okay then.
