### ISSUE TITLE
maintain running mapView in server side?

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#269]
the entire functionality of jxMaps needs a "mapView" which is the prerequisite of everything.
last semester I managed to wrap and maintain one mapView to be used in every functionality, since all we needed it for was functionality and they take a long time to load.

in ionic, everytime functionality is made, it seems that we need a mapview, but there is a need to re-wrap it, meaning, that the mapView should already be running and accessabele when the client wants functionality.

I have a general idea as to where to put this, but maybe someone simply knows it and I needn't bother

**Comment by Kolikant** [comment]
feel a bit silly for opening this issue, one second later I solved it, but maybe the solution is bad, so I leave it open.

a mapView is instantiated with the application as a static field (same as our application last semester) and is accesable by all services who need jxmaps functionality

**Comment by AdiOmari** [comment]
@Kolikant <https://github.com/Kolikant> Make sure the access to this static
field is synchronized (because it may be accessed by multiple server
threads, each dealing with a different user request and we are not sure whether it is thread safe or not).

**Comment by Kolikant** [comment]
I will open an issue about this as I am not sure which would be the best way to access it.

since the static field exists just because that building the mapview takes a long time, maybe adding synchronization overhead simply wouldn't pay off and we should just create it each time we want a service

**Comment by Kolikant** [comment]
let's discuss it the,
@yaelAmitay (I know it's sabbath, when sabbath is over, no rush) @koralchapnik @KaplanAlexander @ArthurSap

**Comment by Kolikant** [comment]
to sum the question up: we need a mapview each time we want to activate jxMaps functionality, these take a few seconds to build. do we:
1) build one for our server when it starts and synchronise it
2) build one each time a server is required
3) any other idea

**Comment by AdiOmari** [comment]
I will leave the discussion for you guys, but I don't think the synchronization overhead is more than the "long loading time" of the jxMaps. This is a minor issue, you don't want to spend a lot of time on it.

**Comment by koralchapnik** [comment]
I think the synchronization is fine and will take less time than building a mapView each time we want to activate jxMaps functionality, cause it is probable that we will use this functionality a lot, and I think that synchronization at this case could be more beneficial.

**Comment by kapalex** [comment]
The synchronization seems like a bad idea.  Even if we will have 100 users try to use it simultaneously, they would get queued and have to wait to use the mapview one at a time.  This design doesn't seem to be scalable at all.

In my opinion each client(i.e. person using the app, not necessarily registered user) should upon connection have his own MapView created, and said mapview kept in memory while the client is connected to avoid recreating for every request

**Comment by Kolikant** [comment]
I like your idea, Alex, it seems like the tight way to go.
The login already takes as long as creating mapview, we can do them together

**Comment by ArthurSap** [comment]
I agree with Alex. Once the user logs out we can simply terminate his mapView session.

**Comment by Kolikant** [comment]
We should wait for yael to weight in (sabath etc) and if she adrees ill add this to the issu of login

Regardless umtill the ionic login exists, the static field would remain just so we can test and run the functionality

**Comment by AdiOmari** [comment]
If you want to do it right, then the right implementation is to use a **queue of mapViews** , the synchronization is on the queue. Every thread that needs a mapView object locks the queue and gets a mapView object,and gives up the lock, and when it finishes it locks and queues it back.  
If the queue is empty then there are two options  for dealing with this case: 
1) [wait on the queue object](https://www.tutorialspoint.com/java/lang/object_wait.htm) (more professional) and let the thread that finishes and queues a new thread to it notify the waiting threads  , OR
2) Give up the queue (because all of the mapView objects are used) and only then create a new mapView object.

Creating a new object for every user affect the memory usage, but still acceptable solution of you think it is easier.

**Comment by yaelAmitay** [comment]
I'm doing the Login and I keep a kind of list of UserInfo I can keep there the MapView of each user.
I'll load the server code today, though I'm still working on it.
So everything you to keep in the user session keep it there.(I'll load it in a few mintues)

**Comment by yaelAmitay** [comment]
oh now i see Adi's comment, so do we want to keep mapview for each user or not?

**Comment by Kolikant** [comment]
The login itself to the parse server is already taking as much time as creating the mapview

The login in usermanagment is in the backgrounf aswell

You can do them both at the same time

**Comment by yaelAmitay** [comment]
@Kolikant  I didn't understand you
what do you mean?

**Comment by Kolikant** [comment]
Login, in usermanagement that i implemented, does the login to parse and it takes some time.
In that time, create mapview
