### ISSUE TITLE
The change in Review and the DB

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#270]
As you know, we changed the Review class to contain a user object instead only the user name.
this change creates changes in the DB that are necessary for the project to work.
**The tests that were affected by this change and were ignored are:**

- NavigationTest - displayMap()

- LocationManager - is in comment, each time instantiating a review, we should create a user instead only putting the user name.

- ReviewManager - the same as LocationManager

**In LocationManager some lines were put in comment in order to not make any compiling errors** : 

- in method getLocation(LatLng point, Location.LocationTypes t, Location.LocationSubTypes subtype):
`	FindCallback<ParseObject> callBackR = new FindCallback<ParseObject>() {

			@Override

			public void done(List<ParseObject> arg0, ParseException arg1) {

				if (arg1 == null && arg0 != null)

					for (ParseObject ¢ : arg0)

                          //	$.add(new Review(new Location(point, t, subtype), ¢.getInt("rating"),

                        //     ¢.getString("comment"), ¢.getString("user")));

				synchronized (mutI) {

					mutI.set(1);

					mutI.notifyAll();

				}

			}`

- in method getLocation(LatLng point, LocationListCallback c):
`		DatabaseManager.queryByFields("Review", valuesR, new FindCallback<ParseObject>() {

			@Override

			public void done(List<ParseObject> arg0, ParseException arg1) {

				if (arg1 == null && arg0 != null)

                          //for (ParseObject obj : arg0) {

                         //Review r = new Review(obj.getString("locationID"), obj.getInt("rating"), 

                       //obj.getString("comment"), obj.getString("user"));

                      //if (obj.getInt("pined") == 1)

                     //try {

                              //r.pin(new UserImpl("db", "123123", User.Privilege.Admin));

                    //} catch (UnauthorizedAccessException e) {

                           //System.out.println("someting went worng loading reviews to location");

                        //}

                    //reviews.add(r);
 
                   //}

				DatabaseManager.queryByFields("Location", valuesL, callBackL);

			}`

i.e the code that were put in comment were the code that deals with Review.
I didn't change anything except putting some code in comment because I wasn't in charge of the DB and doesn't know all the implications of changing the code there.

@KaplanAlexander after the LocationManager will be re-written we can rerun the ignored tests

**Comment by koralchapnik** [comment]
Right now I removed the code I've put in comment in LocationManager and added two useless constructors to Review for LocationManager will compile.
After the new DB will be ready I'll delete those constructors

**Comment by koralchapnik** [comment]
@KaplanAlexander @Kolikant  is that OK that I've put DeleteReviewsTest and ReviewManagerTest and UserManagerTest  and DatabaseManagerTest in ignore annotation?
right now the current DB doesn't working well because the change in the Review class of putting the user object instead of the user name.
I don't think we shall spend much time on passing those test because we will have new DB which we will test

**Comment by kapalex** [comment]
It is ok but `UserManagerTest ` should pass as `UserManager` isn't being changed

**Comment by koralchapnik** [comment]
It doesn't pass because the delete review doesn't work well

**Comment by kapalex** [comment]
How is delete review related to `UserManager` ?

**Comment by koralchapnik** [comment]
I don't remember I think the test contain this method but I am not near computer,  later on I can check this again

**Comment by Kolikant** [comment]
User manager is probably failing because of the changes done to the user class itself, as it does not save nor load helpfulness which might be expected in the new constructors, I donot beliebe i tested delete review in it
