### ISSUE TITLE
Login: when user login we keep a map view for his session

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#284]
when user login we keep a map view for his session. any request he might have will be on his copy of map view. 
the copy of the map view will be destroy when the session is over.

**Comment by yaelAmitay** [comment]
@KaplanAlexander , @Kolikant , @koralchapnik , @ArthurSap 
so in #269 we decided to keep mapView for each user when he is logging in. but search and navigation should be available to users even if they don't login so all the users that are not logged in will use the same mapview? (and then we need synchronization). if so, then what is the reason to keep mapview for each user? only the search need it.

maybe we should make the search and navigation available only to logged in users.

**Comment by ArthurSap** [comment]
If we look at Waze - you need to be logged in to use it, but Google Maps doesn't require to be logged in. Personally I think we should make search and navigation available to all users (and not logged in) and create a mapView for each user that's not logged in as well (so to save synchronization). If this is far too complicated or time consuming we could use Waze's model and allow only logged in users to use the app.

**Comment by yaelAmitay** [comment]
we can't create a mapview for anyone who use our app it's time consuming.
But we navigation doestn't need mapview so we can make navigation available for everybody and search only to logged users

**Comment by Kolikant** [comment]
The default user is a user for everything, if someone isn't logged in then they are the default user, so synchronization on his mapview should be the way.

Its consistent with our implementation and incourages users to log in (otherwise they get alower service)

**Comment by koralchapnik** [comment]
I also think we should make the search service available for everyone, thus synchronization is needed

**Comment by yaelAmitay** [comment]
I disagree I think that synchronization on one mapview is not a good idea.
but if thats what you all want then fine.

**Comment by yaelAmitay** [comment]
@Kolikant  , @koralchapnik  
In the searches you should always check if there is a token and check if the user is logged, and if so you should access the mapview of the user from the userInformation.  
In order to access the map view do as follow:
```
UserInfo userInfo = LogInService.getUserInfo(token);
ExtendedMapView t = userInfo.getMapView();
```
you can also get the user from UserInfo.
If the user is not logged in you should access the global map:
`Application.mapView`
in this case synchronization is on you. On every operation use mutex.
@ArthurSap :
you'll probably need the user in the review in this case do:
```
UserInfo userInfo = LogInService.getUserInfo(token);
User u = userInfo.getUser();
``` 

**vary important!!!!!!**
the function LogInService.getUserInfo(token) will also check that the user is logged you don't need another function to do it.
