### ISSUE TITLE
Change to User database storage

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#291]
While working on some of the changes to the database class ( #230 ) I've ran into a problem with the current User representation.

The way we have implemented the user, the `User` class contains all the information about the user, both public (helpfulness, username) and private (password, favorite queries)
The issue that follows is that when user A wants to see the helpfulness of user B, he cannot do that without his password because all the user data is stored in the parse database under the regular user class (which can only be accessed by logging in with a username and password).

I propose the following change :
1. The `User` class will contain all the private parts of the user and will be stored on the database the same way it was so far, using `UserManager`
2. The `UserProfile` will hold the public information and will be restored using a new `UserProfileManager` which will only require the username to restore.
3. The review class will hold the `UserProfile` class instead the `User` class as discussed in #263 

Thoughts ?
@ArthurSap @koralchapnik @yaelAmitay and mostly @Kolikant

**Comment by koralchapnik** [comment]
I think your offer is fine

**Comment by yaelAmitay** [comment]
that's fine with me, but I would like to know why can't we just access the DB with out the user password, it's weird.

**Comment by kapalex** [comment]
Parse actually combines both a user management system and a database.
The database is accessed with `ParseObject` and the user management part with `ParseUser`.  Since the user is stored within the user management system the info stored is considered to be private, thus should only be available to the user himself - meaning he needs to be authenticated with a username and a password and cannot be accessed directly like the rest of the database.
This actually makes a lot of sense, other wise the users info would be easily obtainable by anyone.

**Comment by Kolikant** [comment]
that is actually, really good design. might be tricky changing usermanagement for it though

**Comment by kapalex** [comment]
It will take a small adjustment to UserManagement(mainly restoring the profile from a seperate class), and I will take care of it as part of the database refatoring

**Comment by kapalex** [comment]
We seem to be all on board so I'm closing this and opening an issue to actually due it
