### ISSUE TITLE
Testing the webservices -  server side

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#297]
## How to test your webservie?

1. notice I added a file named `ServiceTest.java` it contains the setting of the mock we need. you can ignore this file just know that it's there.

2. create a test file for your sevice, for example `NavigationServiceTest.java`. **extend** the class `ServiceTest` from above:
`public class NavigationServiceTest extends ServiceTest {...}`

3. for request that need login add the signup and the login to the setup and keep a token, as follows:
```
	Token t;

	@Before
	public void setup() throws Exception {
		this.mockMvc = webAppContextSetup(webApplicationContext).build();
		mockMvc.perform(post("/signup?name=me&password=1234"));
		mockMvc.perform(post("/login?name=me&password=1234"));
		this.t = Token.calcToken(new UserImpl("me", "1234", null));
	}
```
 now when you need to send the token you have it in the `t`.
*note: This is usually done differently. But for the simplicity of the code this is what we are going to do.
**note: you need the setup any way for:
`this.mockMvc = webAppContextSetup(webApplicationContext).build();`
4. testing:
There is a wide range of options  for checking the code. 
For example, checking that unauthorized access is blocked. We expect to get an error.
```
	@Test
	public void navigationUnauthorized() throws IOException, Exception {
		mockMvc.perform(post("/navigation" + "?srcLat=0.0&srcLng=0.0&dstLat=0.0&dstLng=0.0&accessibilityThreshold=0")
				.header("authToken", "lalal").contentType(contentType)).andExpect(status().isUnauthorized());
	}
```
you can check online, or jsut play with eclipse in order to find other checking option.
more example can be found in LoginServiceTest, more than the navigation

**Comment by ArthurSap** [comment]
Is this supposed to be a wiki thread ("study and explain")? Or just force us to do tests on stuff?

**Comment by yaelAmitay** [comment]
a wiki thread,
We can add test issues later.

**Comment by yaelAmitay** [comment]
@ArthurSap , @Kolikant  , @koralchapnik , @KaplanAlexander 
please note I updated this issue and now it contains a small guide on how to test the webservice. 
from now everybody should test their webservice.
please let me know if you have problems.
