### ISSUE TITLE
publish new interfaces for DB 

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#300]
As we have already said (in person): 

publish an API to the new DB's manager.

we need this in order to test our code with mocking.
and in order to avoid delays in progress of the other parts of the project.

**Comment by kapalex** [comment]
@yaelAmitay @Kolikant @koralchapnik @ArthurSap 
# Important Info
1. I've created files in the master branch that provide the entire interface for review and location database managers, they are under `AbstractReviewManager` and `AbstractLocationManager`
2. Both managers allow blocking and non blocking calls with `ICallback<T>` interface (note `T` is the return type of the interface.
For example calling 
`String res = AbstractLocationManager.instance().uploadLocation(loc, null);`
will be a blocking call which will return the id of the location stored, on the other hand calling 
`String res = AbstractLocationManager.instance().uploadLocation(loc, (s) -> {});`
will happen in background  and **WILL RETURN NULL IMMEDIATLY**
Note that the `ICallback` interface can and should be used with lambdas, such as 
`AbstractLocationManager.instance().uploadLocation(loc, (s) -> System.out.println(s))` or 
```
AbstractLocationManager.instance().uploadLocation(loc, (s) -> {
 doSomething(s);
 doMore(s);
});
```
3. For testing purposes you can and should use mocks of the abstract classes.
For example :
```
mock = Mockito.mock(AbstractReviewManager.class);
// Set returns for mock
AbstractReviewManager.initialize(mock)
```
After the call to initialize, `AbstractReviewManager.instance()` will return the mock across the app
4. If you need more functions add them to the Abstract classes and add them as an issue for me to implement
5. Note that the way to access reviews for a location is to restore the location with `AbstractLocationManager` and access the field of reviews in location
Using the `getReviews` of `AbstractReveiwManager` will return the list of locations but the `location` field for each of them will be empty, this to avoid a loop with the implementation of review and location containing each other

**Comment by yaelAmitay** [comment]
Does this mean that my class(for example navigation) should get instance of the manager(for example AbstractLocationManager)  and when i want to test my class(the nvaigation) I'll give it mock of the manager?

**Comment by kapalex** [comment]
When you use in regular code you will call
`AbstractLocationManager.instance()` which will be initialized with the app 
When testing, the `@Before` or `@BeforeClass` function should create a mock of `AbstractLocationManager` and call `AbstractLocationManager.initalize(mock)`
Then all functions calling `AbstractLocationManager.instance()` from the test will get the mock
