### ISSUE TITLE
Location contains LatLng object rather than Lat and Long

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#302]
which was probably good design before we needed the actual Lat and Long in the pages. no search can't acess them.

in the refactoring of location we discussed (as soon as we get the database's interfaces) we need to make sure that Lat and Long would be int's or strings as to be able to get them in Json with the location. 

notice we cannot have services return theses lat and long as search for they are ambigous, locations are latlong, type ans subtype.

can also make a different service for taking locations ans returning their latlongs, just unsure as to how silly that would be. @yaelAmitay make another service for it?

**Comment by yaelAmitay** [comment]
no,
that's okey if the LatLng in Location is an object and not integer, JSON can deal with that just fine.
The only problem is that the LatLng in Location belongs to JXMaps and we should not return this object to the client.
Location should include LatLng object of our own.(we already have LatLng of our own in Navigation package, we can use it.)
this need to be done wisely.

**Comment by Kolikant** [comment]
I was unable to get LatLong's actual information from location. it should be data.coordinates.Lat/lantitude but it just says undefined. if we are not opening a service (great, I thought we shouldn't) than I need to wait for the database so we can change server side, becuase I cannot get the actual information from the LatLng object

**Comment by yaelAmitay** [comment]
look at the json that the server returns. (using postman, browser ,etc') and then look if: data.coordinates.Lat/lantitude  is defined or not. one possible problem is that the LatLng of JXMaps can't be converted to JSON. which is one of the reason why I rather have our own LatLng class in Location.
if this is the problem then we should wait.

**Comment by Kolikant** [comment]
great, so you agree with me

**Comment by yaelAmitay** [comment]
yes just please make sure that this is the real problem, by checking the json

**Comment by Kolikant** [comment]
I double checked since you insisted on it, and it seems that indeed my bad,
it seems indeed that you can get it, probably just made some mistake earlier. no need to change

**Comment by Kolikant** [comment]
no wait!
that was why I opened it... I can get it from the service. but if I have the location from the service I can't get the lat lng

**Comment by Kolikant** [comment]
ok, yeah, managed to access it, so no changes needed. go us
