### ISSUE TITLE
view location server + client

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#303]
there is no location frame existing yet or an issue discussing it, we need to add the option to view a location.

**Comment by yaelAmitay** [comment]
there are already planty of issues about this: #254 , #278, #256, #266, #264

**Comment by Kolikant** [comment]
this is an issue about the actual screen of the location, not touched directly by any of what you mentioned, but required by all of them, resulting in the opening of this issue

**Comment by yaelAmitay** [comment]
I don't understand, What functionality does this issue relate to?

**Comment by Kolikant** [comment]
the actual page of a location that was searched for or clicked, allowing for the functionality to be used

**Comment by yaelAmitay** [comment]
oh okey.  can you please add to this issue what should this page include?
right now when someone clicking on some point a small window is open and the user can choose to add/view review and to navigate to this location. so isn't this the same as the Location page you want?

**Comment by Kolikant** [comment]
I want to build on it, add information about the location. so its a good start, we also need that the click would also get the location etc.

**Comment by yaelAmitay** [comment]
okey so just keep in mind that we have this window so we don't have duplicatios. and I think it'll be good if you elaborate on what this issue include.

**Comment by yaelAmitay** [comment]
I'm just worried that this issue is a duplicate. I don't understand what job need to be done here.
please make sure you are not taking someone else's work.

**Comment by koralchapnik** [comment]
Last semester we had a lot of problems regarding doing things that other people have already done, 
and a lot of misunderstanding regarding what each of us is doing.
I don't want us to repeat our mistakes so we have two options:
1. before someone opens new issue he goes over everyone's else issues and make sure he didn't take someone's else work.
2. all the work will go through one person, something like Ionic Manager, to make sure that everyone has equal work and no one is taking someone else issues.
What do you prefer ? @Kolikant @yaelAmitay @ArthurSap and @KaplanAlexander , what do you think  ?

**Comment by Kolikant** [comment]
I went through all of the issues before opening this one and saw it necessary. I believe that the misunderstaing is due to the fact that textual communication is the worst communication possible other than maybe miming, so if you want I can explain again over the phone or when we meet.

Koral, I only recall once when what you said happened and not that it was a recurring problem.

placing someone in charge of ionic issues would have been a good idea, were it not the focus of the entire semester, thus dissallowing people to dynamicly change their work meaning that they can't work freely is not a good idea to me.

the way to stop taking people's work (which i was not aware has been recurring is to have people read the issues, like yael just did).
 but I truly think that this is an issue by itself which is why i opened it after reading everything

**Comment by koralchapnik** [comment]
Last semester Alex managed the issues and the conflicts we had and knew the responsibilities of each one.
I think it will get messy here with absence of some Ionic manager of this project just to keep that things are going well and each one is have work and don't mess with other people work.
I don't think that having a manager for the Ionic part means that you won't open issues.
It means that each one will know his responsibilities and we won't have problems or argues cause we don't have time for that.
With manager the work will be much more clear and not messy, and will raise our effectiveness and reduce the misunderstandings or double work which it cause.

**Comment by Kolikant** [comment]
after talking with Yael, it seems that even though no single issue regarding the location frame exists, the issues that she mentioned add up to a single working one explaining what it should be. I thought that we needed to have plans for what the viewing of the location should have, but if we have a lot of single issues establisghing fragments of it, this would make this one unnecessary.

having a manager seems like a bad idea for me, but I don't mind if that's what you want (less things to worry about if just one person does the thinking)
