### ISSUE TITLE
client side: AddMarkers function

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#304]
the complex and simple searchs need to add markers to the map.
they should use this method.

the function is in `mapview.ts` the name of the function is: `addMarker`.
the input is: array of latlng objects.

**Comment by Kolikant** [comment]
oh, you're implementing it? was just about to start trying. wanna pass it to me?

**Comment by yaelAmitay** [comment]
I already start working on it, it's relate to the map I thing it's better if I take care of it.

**Comment by Kolikant** [comment]
I'm using it ans it seems to not add markers, so could you re-explain interfacing with this method? couldn't find an example  what I did was:
	var longitude = data.coordinates.lng;
			var latitude = data.coordinates.lat; 
			this.addMarker([new google.maps.LatLng(latitude, longitude)]);

and nothing happens with it

**Comment by yaelAmitay** [comment]
I'll check it out right now

**Comment by yaelAmitay** [comment]
you should have use it like this:
```
var longitude = data.coordinates.lng; --> remove this line
var latitude = data.coordinates.lat; --> remove this line
this.addMarker([data.coordinates]); --> line changed
```

note that i changed your code, please also note that you need to change the center of the map when you search, I can do it for you if you want.

**Comment by Kolikant** [comment]
No thanks, I will do it
Thanks for the explanation
