### ISSUE TITLE
clicking on markers, pops location menu

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#307]
** assigning to myself per the instruction that all issues must be assigned, the assignment is debatable **

clicking on the map opens a menu that allows us to interact with the coordinates, however, since most usages of clicking on the map would be done AFTER searching on not by clicking on latlng's, clicking on markers should also open a menu similar to that of clicking on the map.

I said similar, for the reason clicking on the map even opens a menu is due to the fact that we want to allow users to add locations, as juust random latlngs everywhere is unhelpfull, so in principle the menu for clicking on the map (inorder to add locations and then using them) should be different but similar to clicking on a marker (in order to use a location) but... if the marker is also not yet a location we still need to maintain consistency, meaning. that we need to MAKE BELIEVE that locations under markers found by type search (called complex search in git for some reason) would LOOK like they are locations where they might not be.

the last paragraph is just a principle for design, we can ignore it and just have the same menu pop up with exceptions should the user try to add all ready existing locations,

**Comment by yaelAmitay** [comment]
I think it should be the same menu.
and i don't see any exception...

**Comment by Kolikant** [comment]
One example, if you were asking, is If the user wants to add a location of an already existing in a latlng. This would be allowed on gui, but not in the logic.
We can just ugnore that request as an implementation, but we DO allow this in gui to be ognored. But if the user was genuinley....special enough as to do that, he will probably not understand why it isn't working. So we need an exception of "location type allready exists here".

I beleive over exceptions should be taken into account as well

**Comment by Kolikant** [comment]
Besides, as i have mentioned before. The only reason users can even click on the map is in order to add locations, since if they click they would most definetly miss and not hit any actual location.

So i believe as before that clicking on the map should raise only the not yet implemented "add location"
And clicking onmarkers should open the location menu.
Rhis would be a much more coherent and clear interface.
Of course offering the user the same inboth would still work but would offer a very frustrating interface.

**Comment by yaelAmitay** [comment]
First of all tomorrow we have a meeting so let's talk about it face to face cause' I'm not sure I understand you.

However, when the user click on the map(marker or just point) we should ask him what is the type of the location he want. and then we allow him to add review or view the review and etc.
if the location doesn't exist in our DB he won't see reviews. in this case if he'll add a review the location will be created. 

so I just can't understand the problam you are talking about.
but as i said we can talk about it tomorrow .

**Comment by Kolikant** [comment]
I am constantly asking to have all disscussions in the meetings, have made a special effort to the issue here as per your request. 

It goes without saying that i would prefer face to face, in any occasion in the future

**Comment by Kolikant** [comment]
The point is, i try once more, that "clicking" is ridicolously inaccurate, as each pixel is a different latlng.

So "clicking" as per finding locations is a frustrating interface, for it would likely miss anything and if we choose to have a circle it would be on some ocasiins ambigois.
The reasonclicking even exists as a feature is for users to add locations.

The correct and non-frustrating interface is as such:

1) searching pops markers and those markers are un ambigous as per what the user wants, clicking onthese should show the location menu.this is what as you mentioned we ask him about which location he wants from that latlng, or even conclude from his search.

2) since google maps does not contain all locations, clickin gon the mapallows adding locations. So since we don't have a choice and NEED users to add locations, by clicking they can.

The scenario inwhich clicking on locations allows adding and viewing qould result in duplicates and in users not finding what they want. The way to find locations should be with search, it is why its there, bypassing search or allowing a bypass offers users the illusionof convenient interface which would actually be them clicking around the map not finding what they want.

Splitting to add(click) and see(click on marker) seems a logical choice to me. Even a necessity.

But on that we will talk tomorrow

**Comment by Kolikant** [comment]
so as decided in today's meeting, there would be the same interface in both marker and click BUT it would be a different interface than exists currently, which would be explained later, meening that this issue, regards only in giving a click event on a marker the same result as a click on the map.

**Comment by yaelAmitay** [comment]
we decided that I'll do it right?

**Comment by yaelAmitay** [comment]
To sum up:
1. user click on the map
2. small windows open with 2 option: (1) get list of nearyby location(within small radius), (2) navigate to location.
3. when user click on get nearby location a small window with the beaerby location is open. when he click on some location he another window is open. this window right now has 2 features: (1) add review (2) get review.

@Kolikant , I changed the menu to have two option.(as explained in 2 above and as you asked for) I created a page named "LocationListPage" it's now **your** page you should access the locations in the radius of the latlng.(I sent the latlng in the params) and display them as a list of location.

when someone finally pick a location we should move to another page, is it alright if this page would be mine? It'll just have 2 option right now: adding and viewing review which is done by koral and arthur. I'll only warp these options in a page.

**Comment by Kolikant** [comment]
(y)

**Comment by Kolikant** [comment]
Oh, i thought that does a thumbs up, yeah, sure. Good work
