### ISSUE TITLE
Admin define an unexpected event as a constant.

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#31]
The admin user can set a reported incident to become a constant review of a location.
This means the incident is no longer temporary (wont be removed after an expiration time, cannot be reported as irrelevant by users)
The admin should have an interface to do this action.
Relates to #26 

_moved out of sprint 2 and is closed until relevant again_

**Comment by yossigil** [comment]
I am not sure I understand what the deliverable here is...

**Comment by kapalex** [comment]
This issue was part of a bigger feature that was moved out of spring 2 and this issue was support to be closed for now

**Comment by yossigil** [comment]
I still do not understand this issue.

**Comment by kapalex** [comment]
Added additional info, the issue was overlooked as we were focusing on the current sprint
