### ISSUE TITLE
Admin "update latlng" interface (server side)

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#311]
one of the reason admin exists is because admin (municipal representative) has the authority to change the latlng of location added by users. but for him/her to be able to DO that, he/she needs to know what are the new locations. 

agregating theses locations that are "pending" admin authentication or update, could be a neat feature. all of this should exist already at the server side in a way, butfor it to be much more logical and conveneint, it must be made a new.

**Comment by koralchapnik** [comment]
Science I am responsible for admin and you're for the regular user,
Can I close this issue and open my own issues regarding the admin page?

**Comment by Kolikant** [comment]
You can assign this issue to yourself, no?
