### ISSUE TITLE
admin update latlng (client side)

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#312]
** assiging to myself as per the demand that all issues be assigned, this assignment is debatable ***

as described in  #311 but with the client side instead

**Comment by koralchapnik** [comment]
Science I am responsible for admin and you're for the regular user,
Can I close this issue and open my own issues regarding the admin page?

**Comment by Kolikant** [comment]
Why not assign this issue to yourself?
