### ISSUE TITLE
Uploading reviews to the DB - need to check existence?

### ISSUE THREAD

**Issue by ArthurSap** [TechnionYP5777/SmartCity-Accessibility#313]
Before uploading, do I need to check if the current review exists in the DB and use the update method or does is happen by itself and I can simply use the upload method?
@KaplanAlexander

**Comment by kapalex** [comment]
The flow should be as follows :
- When user creates new review upload (no need to check anything)
- When user edits update (if this functionality even exists?)

There shouldn't be a case in which a review might exist

If we want to limit reviews one per user per location, then I can add a method that gets a user and a location and returns true or false if he has a review on it already (this will be a separate method, not part of upload)

**Comment by kapalex** [comment]
Rethinking it I realize at the point you are adding a review to a location you have already retrieved the location from the DB with all its reviews
Meaning it would be quicker (local vs online) to simply check the list for a review by the user, and only creating a new one if such a review doesn't exist
We are assuming a user can only login once at a time so he cannot post two reviews simultaneously.

Closing
