### ISSUE TITLE
Welcome (UserName)

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#314]
mostly a training exercise for me to use the userinformation in the client size, but also a good feature.

in the user profile, it should say "Welcome, (Username)"

**Comment by koralchapnik** [comment]
The user profile is assigned to someone else.
We talked about not taking someone else job.
You have the features you added to exercise on the client side

**Comment by Kolikant** [comment]
this seems to be a deeper issue than I thought as it seems that there is currently no option of accessing the information of a user at all. working on allowing it

**Comment by koralchapnik** [comment]
Of course there is no such option, because I still didn't start working on that.

**Comment by Kolikant** [comment]
point me to the issue where you are in charge of the server side user management and to solving the fact that userinformation is not accessible for us in the client side.

while working on my assignments I reached a dead end as these are missing and seeing as noone regarded the problem before I started working on this

**Comment by koralchapnik** [comment]
When we first split the job we talked about doing things from end to end : client and server side.
The user profile is under my responsibility, and therefore its client side and server side.
Last meeting you said you don't want to do the client side so that Yael is responsible for the client side of your features, and you for the server side.
That is what I talked about when I said that things are getting messy and double work is done.
Anyway, we'll talk about that on today's meeting.

**Comment by yaelAmitay** [comment]
#286

**Comment by Kolikant** [comment]
issue #286 does not cover accessing user information from client side ad it is a server side problem. the tiny feature I am adding to userprfile was inorder to see the advance in the server side. you can delete it for all i care. I read all the issue (as I always do) before opening this, it was not covered. it needs solving.

**Comment by yaelAmitay** [comment]
It's the same and it was pretty clear that this is part of this. meaning this is @koralchapnik  part.
if you want you can make changes without commiting them.

**Comment by Kolikant** [comment]
it was and is very much unclear. is it is very clearly an issue that I just saw and is not mentioned or seen anywhere there.
furthermore, when "we" split the work, I have no recollection of us ever actually sitting or discussing anything. it was unorganized and unofficial, the issues were made without most team members talking of them and distributed only to then claim that each issue covers large portions. I was never in any meeting discussing theses distributions as as far as I know, no such meetings have ever even occured. and it seems to me, that my work which is not in any where an actual page but rather features of pages can constantly be claimed by you who have given yourself the work o entire pages, to be taking work from you.

for example, I need to show in the user profile the searchqueries, there is no place where they can be other than that, opening my own page for it is iditoic. so everything I do would be considered undermining Koral.

if you wan't theses arbitrary distributions to actually bind anyone, the least you can do is have everyone involved in this distribution

**Comment by koralchapnik** [comment]
I prefer that this discussion will be in today's meeting.
I have a lot to say about that.

**Comment by yaelAmitay** [comment]
please give your commit a name I want to write you a comment on them but I can click on them cause you didn't named them.
what I wanted to say is the the token should be in the header.
the are exmaples in navigation and I mention it in issue about the login. 
there are slao examples regarding the server side you can see NavigationService.java

**Comment by Kolikant** [comment]
problem found, explained and resolved in #340
