### ISSUE TITLE
Better separation of concerns in Location

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#315]
While working on refactoring the location manager I ran into something we did last semster
After some discussion last semester we decided to put functions such as `deleteReview(User u, Review r)` and `pinReview(User u, Review r)` under the `Location` class
Those functions check the users permission and/or relevance to said review, and then do the actual function (in case of delete, a function that contacts the DB and deletes)

I'm thinking that this could be done better, especially now that we are working with services.
My idea :
- these function are removed from the `Location` class
- User has functions such as `canDelete(Review r)` and `canPin(Review r)` that return boolean value 
- In the service in charge of deleting review, we will do the following 
```
if (user.canDelete(review))
    AbstractReviewManager.instance().delete(review)
```

This works better to separate different roles in the system (db, map management and so on), in addition to allowing calls to the db to be done in background (which can't be done right now because the call to the db is done inside the delete function of location)

This is a minor change but will make life easier when implementing the services

If you agree to this I will complete this as part of the integration of the new database classes
@Kolikant @koralchapnik @yaelAmitay @ArthurSap

**Comment by Kolikant** [comment]
this seems to be the better design even without the easier implementation. so it's two thumbs up from me, luckily I do indeed have two thumbs

**Comment by yaelAmitay** [comment]
I'm ok with that

**Comment by koralchapnik** [comment]
It's fine by me

**Comment by kapalex** [comment]
Alright, I'll get it done
