### ISSUE TITLE
Admin can delete misleading information

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#32]
Admin has the option to delete reviews that are misleading.
Need to build an interface that allows the logged in admin user to delete resources (Reviews for example) as he sees fit.
This option should not be accessible to regular users.
#20

**Comment by yossigil** [comment]
I am not sure I understand what the deliverable here is...

**Comment by kapalex** [comment]
Clarified a little bit in the comment body

**Comment by ArthurSap** [comment]
@assaflu Should I wait until you implement the delete option from the reviews DB or should I simply delete the reviews from the location itself (and not the DB)?
What do you guys think?
@koralchapnik @yaelAmitay @Kolikant @KaplanAlexander

**Comment by kapalex** [comment]
deleting from anywhere other than the DB wouldn't do much good, so synchronize between you how you'll do it (stubs should do)

a point both of you should consider : when an admin deletes a review users who got it from the database (currently using the application) might do something to make the review go up the DB again (add a like for example), and it might mean the review goes back on the server (or crashes the software)
so deleting should be done carefully

**Comment by ArthurSap** [comment]
Added support for deleting review for Location class
@KaplanAlexander  please close the issue if you confirm.

**Comment by kapalex** [comment]
Some tests seem to be in order, this relies on Review `equals()` function working properly, which should be checked
Other than that, need to add support for user deleting his own reviews (his not an admin, but should still be allowed to do so)

**Comment by kapalex** [comment]
Also just noticed `checkExistence` does nothing (return value not used), why not use `List.contains`?

**Comment by ArthurSap** [comment]
I'm using Location's getReview there for safety as well as I'm printing some error messaged regarding this event (review doesn't belong to current location). So I put every thing in a single method to prevent code duplication.
Regarding user deleting his own review I'm working on it now.

**Comment by kapalex** [comment]
`getReview` actually does the same thing as `get` for list, which is the same check that `contains` does, so it does not add a lot
and if you call it but only print an error (which no one will ever read when using the gui) it doesn't do much

**Comment by kapalex** [comment]
using `getReview` is ok as well, but the `checkExistence` on top of it, without checking return value seems redundant

**Comment by ArthurSap** [comment]
I can throw an exception but when I wrote it kolikant said it's better to print errors for now (at the time).
I prefer using Location's getReview in case of future changed that might be needed so the code won't break (and less changes required)

**Comment by ArthurSap** [comment]
I am checking the return value of checkExistence  though

**Comment by kapalex** [comment]
Yeah exception isn't needed, but a return value `boolean` wheter or not the delete succeded could be useful
And yeah, I see you are using it know (wasn't when I wrote it)
closing
