### ISSUE TITLE
A few notes about the new database and other changes

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#326]
A detailed explanation about using the database can be found at #300 , and if you have any questions you can either contact me or post them here so I can answer in detail for everyone to see.

A few changes that were merged in :
1. `User` is no longer an interface but a singular class.  Since we have only  a single implementation of User it seemed redundant to hold both `User` and `UserImpl` (since admin is also just `User` with different privilege)
2. `User` now holds `UserProfile` that is the public part of the user.  Review holds `UserProfile` instead of `User`.  You can check out more info about this change at #291 .
3. Both location and user now use the builder pattern with the classes `LocationBuilder` and `UserBuilder`. This done to avoid multiple confusing constructors across both classes.  Some details at #273 
4. `Review` now doesn't allow creation without a location object.  Reviews don't exist by them selves, but are tied to a location, so the constructors should match.

A few of the problems that we need to fix :
1. I've commented out a few code parts that came up as errors after the merge. I will open separate issues for the people relevant to go over those parts and see what makes sense to do there.
Some however don't have an author so I'm putting them here 
> AddReviewService:33
2. There are warnings in the code, which according to our coding standards shouldn't be there.
Again, issues for people relevant and for those with no author I'll put here
> AddReviewService:26
> AddSearchQueryService:32
> Pom.xml:207
3. A few tests are now failing, those all have authors

Everyone read this and check yourselves off the list and remove assign. I will close the issue once it is no longer relevant (mostly here for questions) :
- [x] Yael
- [x] Koral
- [x] Arthur
- [x] Ariel

**Comment by koralchapnik** [comment]
I've read this. Good job. 
The review services belongs to Arthur

**Comment by yaelAmitay** [comment]
AddSearchQueryService:32 - ariel
Pom.xml:207 - probably me, I'll look at this.

**Comment by yaelAmitay** [comment]
@KaplanAlexander , I see you made some changes in services/Application.java
you replaced the init of the DB, but did you initalize the user DB too?

**Comment by kapalex** [comment]
The new initialization covers the previous one as well, through the injection
Did you run into any problems with it?

**Comment by yaelAmitay** [comment]
yes I did. I'm having a problem when I'm using the UserManager.(that as far as I know you didn't change)
the problem I have occured before and back then the reason was that I didn't initalize the DB. now you removed my initaliztion with yours. so I thought that maybe you forgot to initalize it.
`org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]`
 maybe it different this time, I'll look again
also, I didn't have problems before the merge..

**Comment by kapalex** [comment]
I'll try to look into it as well
When is this exception thrown?

**Comment by yaelAmitay** [comment]
in:
UserNameExists(..) line 42 in UserManager
it's called by SignUpUser(...) line 53 in UserManager

**Comment by kapalex** [comment]
Found a possible problem (lazy evaluation causing late initialization in some cases) and pushed it, try it now
Can you tell me the flow that leads to the problem if it persists?
If it's from a testing environment some initialization is in order, and if not I'd like to run it my self to maybe get a better picture of the problem

**Comment by yaelAmitay** [comment]
still have problem.
the flow is trying to signup with some name and password:
`User u = UserManager.SignUpUser(name, password, User.Privilege.RegularUser);`
it's from testing environment, but you can try create the flow by just trying the line above.

**Comment by kapalex** [comment]
If it's from a testing environment then the initialization in the application is irrelevant
You should call ParseDatabase.initialize() in the `@BeforeClass`
If that doesn't work - which test is it?

**Comment by yaelAmitay** [comment]
now it's working.
so you said I should add ParseDatabase.initialize() to all my test(in @Before)?
and in the code It'll be fine without that?

anyway, now it's fine.

**Comment by kapalex** [comment]
The initialization in the Application class takes care of any use of the DB in the app itself
Tests don't go through the Application class so each test class needs its own initialization to be independent of other tests 
You should however use it only when the test actually requires the database (as it will cause a network call, which takes up time), which most shouldn't as you should use mocking instead (user manager excluded sadly), so if avoidable - better not to

**Comment by yaelAmitay** [comment]
they actually kind of do for the services tests. so it's very strange...
BTW I now have different problem that I didn't have before, I'll check it. I hope it's not DB related..

**Comment by kapalex** [comment]
Let me know if it is in the db

**Comment by yaelAmitay** [comment]
it's in UserManager again, in LoginUser(...) line 102. the exception is:
`No enum constant smartcity.accessibility.socialnetwork.User.Privilege.2`
This exception wasn't before the merge. and I didn't write UserManager.
I made sure that I'm giving this method the right parameters. and as I said I didn;t have problems before.

**Comment by kapalex** [comment]
Ok, that's on me, will get it fixed soon&trade;

**Comment by kapalex** [comment]
I've reset the user base in parse, which is actually where the problem was
Should work now
A point about the tests - use test categories as explained in [this wiki](https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Test-Categories) and specified in [this wiki](https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Coding-Standards)
Currently some of your tests are under no category, and thus Jenkins does not run them (which is why the build isn't failing right now)

**Comment by yaelAmitay** [comment]
Is it alright that I added this line to Application?
`UserProfileManager.initialize(injector.getInstance(UserProfileManager.class));
`

**Comment by kapalex** [comment]
Yes, apparently I forgot to put it there, so thank you

**Comment by ArthurSap** [comment]
Gonna start looking at my parts to see what needs to be fixed, nice job.
