### ISSUE TITLE
Fix merge issues 

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#328]
Follow up to #326 
A few issues that came up after the merge.  They might be my fault, but aren't in my code, which makes it hard to tell.

Code :
- Navigation:90 👍 
- NavigationService:30 (isn't actually a problem, but I've changed your code, so let me know if it works ok) 👍 

Warnings :
- NavigationService:28 👍 

Test failures :
- NavigationServiceTest:navigationUnauthorized 👍 
- NavigationServiceTest:navigationAuthorizedBadRequest 👍 

Take a look and let me know

**Comment by yaelAmitay** [comment]
also:
Pom.xml:207
#326

**Comment by yaelAmitay** [comment]
@KaplanAlexander  about the warning in NavigationService, I know it's there I need to delete this line BUT I'm using navigation as an example for others so I'm leaving it there till I'll know that everybody understand it.

**Comment by kapalex** [comment]
Maybe comment it out with an explanation?

**Comment by yaelAmitay** [comment]
Okey I can do it

**Comment by yaelAmitay** [comment]
I'm leaving the warning, the bug in #339 was because of that.
the warning will remined me to delete it in a few weeks so I'm leaving the warning as it is.

**Comment by kapalex** [comment]
I've removed the warning by removing the assignment to a not used variable but kept the call it self to avoid issues
seems to pass

**Comment by yaelAmitay** [comment]
of course it pass! I don't need this line at all. But this line throws a runtime excpetion!
This the reason why the test failed when I remove this line.(the test excepted this error)

BUT I wanted to keep the assignment  so the warning will remined me to delete this line in the future.
(I don't really need this line as I explained above)
If the warnins bothers you then I'll just have to remember to delete it alone.

**Comment by kapalex** [comment]
Apparently I missread what you wrote as I thought you wrote it caused it,
my bad.

Anyhow as per our coding standards warnings aren't supposed to make it to
the source control, not on the master branch.
If you want a reminder you are welcome to put a to-do in code or open an
issue, a warning shouldn't fill that role.
