### ISSUE TITLE
Set up database

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#33]
we need to set up a database to contain information for all users
this includes setting up an interface to communicate with an online database 
Includes setting up a Parse server and a class to control that database from within out project.

**Comment by yossigil** [comment]
Make sure you define a clear deliverable.

**Comment by yossigil** [comment]
Please consider openId

**Comment by kapalex** [comment]
To my understanding openId is used to store user info.  The database we are planning on creating is meant to store both user info (which we are now considering moving to openId) and review information which as far as I can tell cannot be stored in openId.
Further more the parse server we plan on creating support geo queries to get reviews based on their location, a feature that suits our needs very well.

**Comment by yossigil** [comment]
I think the case you describe is similar to use cases of many open id clients

**Comment by kapalex** [comment]
I might be missing something but I still don't see how this solves our problem.
Generally clients of our system don't have to sign in.  When a non-signed in user looks at the main screen he will see a map with reviews near by him, in addition to being able to search for reviews in in the search bar.
This means we need to be able to store reviews left by signed in users on some server, and be able to fetch them based on the location they are reviewing.  This isn't directly related to the user authentication or any specific user, and I haven't found a way in which openId can be used in this scenario.

OpenId is what we plan on using for user authentication, but beyond that we still need a database (in our case a parse server)

**Comment by yossigil** [comment]
Yes. You need a DB you are very right. 
But, don't waste time at this stage on sign in/ login/ delete account or any user authentication password etc..

**Comment by kapalex** [comment]
**progress** :
server is up and running [here](https://smartcityaccessibility.herokuapp.com/)
dashboard is [here](https://easypark-parse-dashboard.herokuapp.com/)
username and password will be added to a wiki soon (privately)

the interface for parse server we planned on using is `thiagolocatelli/parse4j` , but it seems the latest release in maven does not support servers not hosted in parse.com (parse.com is shutting down, so server were moved to external sites, our is in heroku) even though the code was updated accordingly.
So I will fork the repo and create our own jar with the latest files.  this means parse4j will be an external dependency and will be added manually to the project, the same as jxmaps.
A wiki about this issue will be created shortly, and the code updated accordingly
@Kolikant @yaelAmitay @koralchapnik @assaflu @ArthurSap 

**update** : 
No external issue added, the dependency is synchronized from a repository

**Comment by Kolikant** [comment]
I went over the wiki and was unable to figure how to use the server.
could you simplify it to a simple: do this if you want the code to compile?

**Comment by yossigil** [comment]
For 2^10 Karma, you may want to check how to keep private information on public github, and if you find a solution you might want to share with others in facebook.

**Comment by kapalex** [comment]
@assaflu added functions that will be useful to you for putting complex objects in the server

later this week I'll also implement some functions for generic queries to the server

**Comment by KaplanAlexander** [comment]
@assaflu as we agreed last meeting we need to be able to move reviews from one class in parse to another, I will add the generic functionality here, the rest is up to you
