### ISSUE TITLE
Admin Page Client Side

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#332]
A page for the admin, who has more privilege than the regular user.
The features include all the regular user capabilities, and the ability to pin and unpin reviews, and more detailed features will be added soon

**Comment by koralchapnik** [comment]
Right now in order to see the page i've added a button in the home page.
That will be changed

**Comment by Kolikant** [comment]
You mean by checking the privilege and showing the relevant page for the user?

**Comment by koralchapnik** [comment]
In the login phase @yaelAmitay  will deliver the user to the right page by checking his privilege
