### ISSUE TITLE
use ionic functionality in pages under me

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#338]
mostly a TODO list for me, though you can feel free to add stuff if you so wish. a lot of features for client side were made by the team and it's hard for me to keep track, so I will reference them here so I can use them in the pages later.

**Comment by Kolikant** [comment]
#334 #317 #299

**Comment by yaelAmitay** [comment]
remove #299 it's not done yet(maybe won't be done at all)

**Comment by Kolikant** [comment]
these are memos for me, if I go do it and it's not done, then I just won't use it :)

**Comment by Kolikant** [comment]
#297

**Comment by Kolikant** [comment]
delayed to next sprint for the importance of beinging locations into working conditions

**Comment by Kolikant** [comment]
right, done
