### ISSUE TITLE
Create login menu

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#34]
users and admin login to their profiles to receive access to their profile
paaswords
no two users can have the same username

**Comment by yossigil** [comment]
I said to @inbalzukerman  that the GUI stuff is less important at this stage.

**Comment by Kolikant** [comment]
Hi
Wrong project :) inbal is in another smartcity project

**Comment by inbalzukerman** [comment]
@yossigil - This is not a project i'm part of 😕

**Comment by yossigil** [comment]
OOPS.... Apologies. I have around 470 open issues I am involved in...

But the same applies. GUI and stuff is traditionally done by automatic tools, and is quite boring, time consuming and not so productive. It must be done, but the essence is really elsewhere. I would invistigate openId and the such for user management.

**Comment by Kolikant** [comment]
Very well,
I opened a bigger issue that contains this one and will reference this ine to it.
We will ofcourse take your advice and notmind the gui for now #39

**Comment by yossigil** [comment]
Please check OPENID and adopt if necessary.

**Comment by Kolikant** [comment]
https://en.wikipedia.org/wiki/OpenID

http://openid.net/get-an-openid/what-is-openid/

@KaplanAlexander  @koralchapnik  @assaflu  @ArthurSap  @yaelAmitay 

what do you guys think?

**Comment by kapalex** [comment]
definitely seems like a good idea to fall back on an existing system rather than create our own

**Comment by Kolikant** [comment]
It does seem to be precislywhat we need
Thank you for the recommendation yossi

**Comment by yossigil** [comment]
Not sure. Why not use openid for login and that's it?

**Comment by Kolikant** [comment]
That is the intention

**Comment by Kolikant** [comment]
in accordance to the meeting today, Alex will be in charge of this issue as well as others like it yet to be open
