### ISSUE TITLE
bug with userinformation, token expires after 10 minutes but users are left logged in

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#340]
took a while to figure out. the wightfull refactoring of user now means that the users saved in parse (and userManagement) are no longer synced, meaning that reading userinformation from server and putting userinformation in server is not aligned. we need to make the changes needed for it to work, 

(noticed this since Welcoe userName no longer worked and it took a while to rezlize that it is unfixable without it, so reopening THAT issue #314)

**Comment by kapalex** [comment]
I've just emptied all the users from the db a day ago, I'm not sure where the problem is

**Comment by Kolikant** [comment]
when a user is uploaded to or from the database, it is still done using fields in the previous user. we should just sit on this together at some point to just get those changes fixed in signup and login methods. though if you want I can just try myself and ask you questions if needed

**Comment by kapalex** [comment]
I'm a little bit out of touch with what the problem is, so I think you should try doing it yourself, failing that we will sit together and work on it

**Comment by koralchapnik** [comment]
Welcomin admin works and print the user name, take a loot at that, I don't think there is a problem

**Comment by Kolikant** [comment]
we've done the same codewe've done the same code, and it seems that after reseting ionic no problem occured. I'm closing this issue since everything seems great, but need to open a different issue as to why logging out and in was the only solution to this. when we get a more coherent understading of the problem we should open the issue.

**Comment by Kolikant** [comment]
it seems that when first logging in. the userinformation is found and all is well. but after a while of working and being logged in, it stops finding the user information.

is it possible that the token has expired? 

it keeps happening that the welcoming works yet after a while of working while logged in, it eventually stops working (until closing ionic and re logging in) I want to perform a test about if that's true , but maybe someone knows to answer me before that

**Comment by koralchapnik** [comment]
@yaelAmitay

**Comment by Kolikant** [comment]
I just made the test (not sure how much time I've waited) but more then ten minutes, and afterwards the working welcome message stopped working. 

that seems to be the problem! we founds it

**Comment by yaelAmitay** [comment]
the token expired after 10 min. Is there any problem with that?

**Comment by Kolikant** [comment]
yes. the user is still logged in. userprofile and now admin both assume that they have a valid token, but after ten minutes they no longer have one and no way of getting one (since they are considered logged on and therefor can't log on again)

I think making the user logged off after the expiration should fix it. would be a bit tedious logging in every ten minutes, but atleast it won't be an error. is that possible to do?

**Comment by Kolikant** [comment]
the user is not logged out after the token expiration, and all of the services given to logged users, assume the token is valid (since a user with no token should not be logged in)

**Comment by Kolikant** [comment]
changing title of issue to match the real problem...

**Comment by yaelAmitay** [comment]
I see what you want and it can be done! :)
I'll do it.

**Comment by Kolikant** [comment]
great! thank you :)
