### ISSUE TITLE
Install SonarLint and connect to SonarQube server

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#342]
As we've agreed at the start of this semester, we are using SonarQube to analyse our code to conform to a higher standard

The thing about SonarQube is that it is too easily ignored, because it doesn't scream in your face that there is a problem, it just lets you know of all the problem in the [main page ](http://kapalex.ddns.net:9000/dashboard/index?id=SmartCity-Accessibility%3ASmartCity-Accessibility)

The result being we haven't actually been keeping up with the reports we are getting.

But good news! 
## Follow these 5 easy steps, and you too can have SonarQube reports in your IDE!

1. Install SonarLint from the eclipse marketplace (help -> eclipse marketplace), then restart eclipse
2. Click on Window -> Show View -> Other and select SonarLint -> SonarQube Server
3. In the new view that opens up, click "Connect to a sonarQube Server and fill in
> URL : http://kapalex.ddns.net:9000
and click Test Connection (should succeed) then Finish
4. In package explorer right click on the project -> SonarLint -> Bind to SonarQube Project
5. Make sure "select a SonarQube server" chooses the one we added, and the click under SonarQube Project where it says "type here to start searching ..." and start writing "SmartCity-Accessibility", it will auto complete and when you click it will say "SmartCity-Accessibility on server ..."
now click finish

That is it!
From now on under "Problems" view you will see info markers that will show issues SonarQube has found.

Note that the sonarlint and sonarqube don't do the exact same job, meaning there might be some differences between what you see in the sonar lint and qube.  
According to our standards we conform with **SonarQube**, so while sonarlint should give you a good understanding of most problems, we will need to solve all the problems that appear in the sonar qube as well, so you are adviced to have a look there every now and again and fix issues.

If you find something that requires change that you don't agree with, let me know and we will decide if that rule should be followed or disabled.

By the end of the semester we should have no warnings on the sonarqube server.

As usual, check list for you to read and **install** according to the instructions , last one closes the issue :
- [ ] Ariel
- [x] Yael
- [x] Koral
- [x] Arthur

**Comment by kapalex** [comment]
@Kolikant @ArthurSap @koralchapnik , needs to be done before the end of the sprint.

**Comment by Kolikant** [comment]
finished step 4. not sure about what step 5 means. there is no "select a SonarQube server" or sonarQubeProject  I just have this 
![image](https://cloud.githubusercontent.com/assets/23051198/26530701/a4e640b6-43e2-11e7-9822-33f4b18d1cef.png)

**Comment by kapalex** [comment]
After you do step 4 (Right click on the project in the left hand window, select  SonarLint -> Bind to SonarQube Project) , a window will open, the one you are showing is not it
It will be a window similar to the settings window

**Comment by Kolikant** [comment]
cheers mate!

**Comment by Kolikant** [comment]
almost took your credit....

**Comment by Kolikant** [comment]
better
