### ISSUE TITLE
Developer installation instructions for presentation

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#346]

**Comment by kapalex** [comment]
wiki can be found [here](https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Developer-installation-instructions)

Left to do :
- according to the resolution to be established at #354 specify instructions for client to connect to server correctly
- instructions on how to create and apk

**Comment by yaelAmitay** [comment]
1. you need to install ionic2, if you don't specify the version it'll install ionic3 and it's not our version.
the commands should be:
```
npm install -g cordova
npm install -g ionic@2.2.3
```
2. In the mail they send us they requested a "user guide".  do you want to do it as well?

**Comment by kapalex** [comment]
1.
Good catch, I thought i had it there, will fix soon
2. 
I would, but being the person least savvy with the client it doesn't strike me as a good idea

**Comment by kapalex** [comment]
Done
everyone welcome to read and suggest changes @Kolikant @yaelAmitay @koralchapnik @ArthurSap
