### ISSUE TITLE
Exception thrown from a new thread

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#351]
Exception thrown from a new thread so the original thread can't catch the exception.(in blocking operations)

for example in `UserProfileManager` in the method `get` line 55. the new thread that is created there throws exception and the original thread tries to cacth this exception. but it's on a different thread.
thte calling method is in `userManager` in the method `login` in line 104.

This problem might exist in other places in the code. so you might want to check in other files too.

**Comment by kapalex** [comment]
When calling these function in background in case of exception the callback simply won't be called (This behavior isn't final, but that is the situation right now, if you have suggestion on this, I welcome it)
When calling with a null callback, it will throw a `RuntimeException`.
You can get the original exception by catching the runtime one and doing `e.getCause()`
The question is, is this good enough?
Or would this be a problem?

Possible solution include some boiler plate code inside the function, or entirely replacing the exception with a null return.

**Comment by yaelAmitay** [comment]
I didn't write the UserManager code so I do not know if it's okay with the person who wrote it.
But that's fine by me. my only problem was that the exception wasn't caught. if now the exception is been caught that's alright with me, is this the case? did I understood you correctly?

**Comment by kapalex** [comment]
Oh ok I missed the problem a bit
Yeah, I'll make work ok
