### ISSUE TITLE
Ionic tries to connect to a server locally

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#354]
While working on #344 , I noticed that the client isn't communicating with the server properly.

What I've realized is that the client thinks the server is at `localhost:8090`, which isn't true when the client and the server are not run on the same machine (which is of course what we aim to do) since the server is run out our server (kapalex.ddns.net), while are client is run locally on each machine that connects to it, as it should.

Ideally the server should be given on startup (`ionic serve`) so we can use different servers when needed.
When running from a local machine the current setting makes sense, while when deploying we want to direct the ionic to one global server.

**Comment by yaelAmitay** [comment]
I think it's possible but do we really want to do it right now? we have plenty of more important issues to take care of.
I assume you are running the client side and the server side on the same machine so right now is it urgent?

However on a slightly different issue, the ionic is the client side and it should sit on the client side(the phone of the user for example) 
so I don't understand why are you trying to put the client side on the server as well.

**Comment by kapalex** [comment]
This isn't a top priority task, but it is important in my opinion. I will specify soon but first a clarification -
The client side isn't supposed to run on every machine separately
The way it works is the client is run on a server, and when users connect to said server, the browser connecting gets the pages (the whole  html, js, ts and so on) and runs them locally, in the browser sandbox.

This is important because the way our application works users don't need to install anything if they want to use the client, they just go to some address, in our case kapalex.ddns.net and everything is done for them.

BUT, the client code while **served** on the server, is being run on the client. Meaning all the code you wrote, including the constants are run in the context of the client machine. So the address `localhost:8090` is actually the clients address, who isn't the one running the server, since the server is singular.

In the specific case of android as I understand we can also manufacture an .apk to be installed on the users phone, but that is a specific use, and not the only one.

Now I think this problem should be resolved sooner rather than later because same as continuous integration, a continuous deployment setup (which is what i'm trying to achieve, new versions of the client and server because continuously deployed and tested out by us) tends to find flaws we would find running locally, and is more similar to the final product we would publish. Example : this problem, which we would not know about had we kept running it only on each of our computers.

Since we are on a tight schedule for the presentation, I understand postponing it until afterwards, but I do believe this should be taken care of ASAP.

**Comment by yaelAmitay** [comment]
about the client side I though we are developing for phones(androids...) and not for browsers...
in the case of phones ionic make it easy for us and wo don't need to put the client side on the server(as far as I understand).

About the dynamic name of the server. I do agree that this is important...
BUT the main requirement for this semester was a good product with useable features so I want to put more effort in the product itself and in it's features. 
So I'll be able to do the change you want in the far future. (If it's urgant to you, you can do it right now :| )

**Comment by kapalex** [comment]
I assumed our point was to enable both phone access and web browser access (other wise we are kind of missing the point of ionic no?)

Anyway, as I said, when you can, do it, but it isn't as important as some other features of course

**Comment by yossigil** [comment]
Keep up the good work

**Comment by yaelAmitay** [comment]
mmm as far as I understand Ionic is more for mobiles but that's okey we can use it for web browsers too :)

**Comment by yaelAmitay** [comment]
it's working now.
if you want the release version:
```
gulp rel
ionic serve
```
if you want the development version:
```
gulp dev
ionic serve
```

the server right now works with the release version.
 
On another note, @KaplanAlexander , is the server side up?
does this is the correct url? 
http://kapalex.ddns.net:8090/
cause I can't access it even with the browser.(for example I was trying to access reviews).

**Comment by kapalex** [comment]
it seems to be failing when running it as part of the deployment job, but works when running it manually

I'll run it now, and look into why it's failing later

**Comment by yaelAmitay** [comment]
will be solved with gulp as I mentioned above so I'm closing this #370
