### ISSUE TITLE
Map view not working when deployed on server

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#355]
When running locally map view works fine (asks for my location and then shows the map)
But when I run it on the server I get nothing, just a blank space where the map should be
I'm not sure what the problem actually is, but would appreciate ideas on how to try to figure it out

client can be found at http://kapalex.ddns.net/

**Comment by yaelAmitay** [comment]
Try adding this commands:
```
ionic plugin add cordova-plugin-geolocation
npm install --save @ionic-native/geolocation
```
(they apeared in the maps guide #242 )

**Comment by kapalex** [comment]
Thanks!
Will try it out and report back

**Comment by kapalex** [comment]
Tried it, still got nothing
It does work with the same running commands on my pc, so it doesn't seem to be a problem with the script

**Comment by yaelAmitay** [comment]
mm does the server allows getting the location?

**Comment by kapalex** [comment]
As far as I know it does
Any specific setting I should be looking for?

**Comment by yaelAmitay** [comment]
I needed to allow the browser to access the location I did it from the "control panel"

**Comment by kapalex** [comment]
Oh, when running locally it asked me with a popup and I agreed and it worked,
here it doesn't even ask
can you tell me where in the control panel you enabled it so I can make sure its not the problem?

**Comment by yaelAmitay** [comment]
from settings go to "privacy" and then "location" and then allow the location there.
I've win10 in hebrew so I'm not sure If I translate correctly :/

**Comment by kapalex** [comment]
Yeah, it's enabled and still nothing

**Comment by yaelAmitay** [comment]
How can I access it myself? I need to see it

**Comment by kapalex** [comment]
kapalex.ddns.net

**Comment by kapalex** [comment]
It's running on al linux machine, if youll need i can give you ssh access later, but thats a bit more complicated

**Comment by yaelAmitay** [comment]
maybe CORS problem?
I'll look at it more

**Comment by yaelAmitay** [comment]
OKEY,
works from Edge(the new Explorer)
not from chrome.
I've a strong feeling in has to do with CORS but for now you can use Edge.
Maybe it'll also work on firefox but I didn't tried yet.

**Comment by kapalex** [comment]
Alright, that's good enough for me for now
when you have time for it, do look into it, I'm leaving the issue open

**Comment by kapalex** [comment]
Just as a side note-  when creating an apk and installing it, it doesn't work either

**Comment by yaelAmitay** [comment]
I never got to try it on android so I had a feeling it won't work.
I don't have android so I can't work on it. 
But I think I know why it's not working on android I just can't check it without a android and I can't use an emulator cause my computer is too slow. 

Yael

‫ב-22 במאי 2017, בשעה 16:26, ‏‏Alexander Kaplan ‏<notifications@github.com> כתב/ה:‬

**Comment by yaelAmitay** [comment]
Since we are moving to android this is no longer relevant. so I'm closing this. Is it okey?

**Comment by kapalex** [comment]
I've tested now on my android device and it still doesn't show the map
I think it might be because android 6.0+ requires the app to ask for permission when accessing the device location, and our app doesn't
I'll look into how it should be done

**Comment by yaelAmitay** [comment]
I tried it on android 4.4 and It works.

It might take some time so maybe you didn't wait?
anyway did you use `ionic build android` and `ionic run android` or did you so it in a different way?

However, there can be many reasons why it's not working on your android. But I need to see it myself in order to find the problem.

**Comment by kapalex** [comment]
I did exactly that, and yes, like I said my point is relevant to android 6.0+
I'll find a way to fix it

**Comment by kapalex** [comment]
fixed it with
`cordova plugin add cordova-plugin-geolocation`

**Comment by yaelAmitay** [comment]
did you follow the commands on my ionic guides?

**Comment by kapalex** [comment]
yes..?

**Comment by yaelAmitay** [comment]
these 2 commands were in the map guides, I think they are equivalent to what you added
```
ionic plugin add cordova-plugin-geolocation
npm install --save @ionic-native/geolocation
```

but nevermind, the important thing is that it works  :)

**Comment by kapalex** [comment]
The thing is that plugin addition should once be done once, and then they should be covered under `npm install`
Our package.json showed we didn't have `cordova-plugin-geolocation`, and now it does, meaning no one else needs to call `ionic plugin add cordova-plugin-geolocation`
I'll work out the details of how it works soon for the installation guide
And yeah, it works so we are all good 😄
