### ISSUE TITLE
Save user info in the database

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#36]
once signed up users info will be stored in the database
when logging in the users will be restored from the database
#18

**Comment by yossigil** [comment]
How would we know that this is complete? Is there a code change planned?

**Comment by kapalex** [comment]
@assaflu see discussion in #34 , we are moving to  openId so this issue is affected

**Comment by kapalex** [comment]
decided to move back to authentication with Parse 
some resources -

- https://github.com/thiagolocatelli/parse4j (our java client)
- https://parseplatform.github.io/#sdks 
      (here is the rest api and android one.  java client is just a mapping for the rest api, and android client might be similar, so might help explain the usage)

**Comment by assaflu** [comment]
Decided to save the username, password, and list of faivorit search queries.

**Comment by yossigil** [comment]
favorite or recent?

**Comment by Kolikant** [comment]
recent would be in the favourites by default, but the user can initiate adding searches to his favorite selection.

**Comment by yossigil** [comment]
Add this to spec that the user can modify this list. (If you think this is an important feature)
