### ISSUE TITLE
Logo To Our App

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#361]
Hi, what are you saying about creating a logo to our app that will be presented in small icon in each page we create and in bigger icon in the home page ? 
And if you want a logo, what objects do you suggest it will contain ? (wheeling chair for example...)
@KaplanAlexander @yaelAmitay @ArthurSap @Kolikant ?

**Comment by yaelAmitay** [comment]
you can do it if you want

**Comment by kapalex** [comment]
It's a good idea to have one (Maybe a wheelchair with the wheel of a car?) but also not a proiority for the presentation, the actual functionality should be
So if you have time left - yeah
