### ISSUE TITLE
Ionic remove all unused imports

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#362]
We have a lot of unused imports, in the client side(ionic side)
Everybody should remove the unused imports in _their pages_.

**Comment by yaelAmitay** [comment]
- [ ] @ArthurSap 

- [x] @koralchapnik 

- [x] @Kolikant

**Comment by Kolikant** [comment]
do you happen to know a way to tell which unused warning belongs to which file? because when I set on removing my unused import I believe I only touched the tip of the iceberg, yet the work of finding them was extremely inefficient.

**Comment by kapalex** [comment]
I think when you build the app (`ionic serve` or `ionic build android`) you you will get a full list of warnings, including the unused imports

**Comment by Kolikant** [comment]
yes, but it doesn't say to which files. it prints the lines that have unused imports without saying in which file.

**Comment by yaelAmitay** [comment]
it's enough to do `ionic serve`. you should _roll up a little_ and see a list of files that has unused imports. 
if after some builds it's stop showing you the file with unused imports do `ionic serve` again.

![image](https://cloud.githubusercontent.com/assets/23058068/26530480/13660986-43de-11e7-982e-89359bcf98a7.png)

**Comment by Kolikant** [comment]
I'm not getting these yellow lines. could you just print screen all of it? I can get rid of all the unused import right now if you do. I can finally see where they are

**Comment by yaelAmitay** [comment]
that's all of them. did you rolled up a little?

**Comment by Kolikant** [comment]
I'm tagging @koralchapnik since it seems she missed a few of the imports. it was really hard to remove all of them without this print here. but with it we would both be done in seconds
