### ISSUE TITLE
adminManager

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#365]
in order to continue with the AdminPage (#332) I need you to create an adminManager which will enable the following features : 

- [x] getting the n regular users with the highest helpfulness
- [x] getting the number of users in the system
- [x] getting the n locations which are most rated / most reviewed

> getting the number of logged in users

**Comment by kapalex** [comment]
The first three aren't too complicated, will get them done quickly
As for the last point, How are we monitoring logged in users now @Kolikant @ArthurSap @yaelAmitay @koralchapnik ?

**Comment by yaelAmitay** [comment]
We have cache of users that are logged in.
The last point doesn't require the adminManager .it can be done easily in the service.

Yael

‫ב-22 במאי 2017, בשעה 13:36, ‏‏Alexander Kaplan ‏<notifications@github.com> כתב/ה:‬

**Comment by kapalex** [comment]
I've created stubs for you to be able to use while I implement
according to what Yael said, i'm not implementing the fourth one

They are in `UserProfileManager` and `LocationManager`
