### ISSUE TITLE
Helpful Users Page

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#368]
as part of the Admin features (#332) the admin will see the n most helpful users in the system.

**Comment by yaelAmitay** [comment]
Is it going to be a page?

Yael

‫ב-23 במאי 2017, בשעה 18:23, ‏‏koralchapnik ‏<notifications@github.com> כתב/ה:‬

**Comment by koralchapnik** [comment]
Yes
