### ISSUE TITLE
Question about using local map

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#37]
Is it okay by all of you, if the map will be local?
I mean the search and the navigation options will be available only for one city or couple of neighborhoods.
this issue is relate to #19 .

**Comment by Kolikant** [comment]
Absolutely,  as long as you make sure that it is scalable.
We will be needing it for demonstrations at first anyways :)

**Comment by koralchapnik** [comment]
Sure. 
There is no need at that point to have more than once city in the map. 
It will be better for us to start in one city and later on enhance it. 
Thanks for consulting us :)

**Comment by yaelAmitay** [comment]
closed for now. First we need to discuss another issue.
