### ISSUE TITLE
Ionic gulp set variable

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#370]
**ATTENTION!!!!!!!!**
for  now, we need to rollback because the installation does not work for every body,
please use the following command:
`git reset --hard 89645e9dd6163e43961b888f1b521ae38127f7d5`
then do pul, **you must do the pulll**:
`git pull`

when we have more time we will fix the problem with some of yours computer so we can use gulp.
So right now, no need to do the other part of this issue.

----------------------------------------------------------------------
Not for now, **Dont do it yet!**
I add gulp to our project for #354 
after pulling do:
```
npm install
npm install --global gulp 
npm install --save-dev run-sequence
```

also might help:
`npm install findup-sync@0.1.2`

It now should work.

**Comment by kapalex** [comment]
just as side note gulp installation is done with 
```
npm install gulp-cli -g
npm install gulp -D
```
according to their site
and if you need something like that, you can tell me to install on the server, so you don't need to put it on the script

**Comment by yaelAmitay** [comment]
I already install it...
I added dependency and I need everybody to update their project. 
Don't worry I'm taking care for it

**Comment by yaelAmitay** [comment]
though i did miss here the cli!

**Comment by yaelAmitay** [comment]
nope no need to add the cli...

This commands works for me and for the server.
if you have problems talk to me and we will try to figure it out.

**Comment by yaelAmitay** [comment]
@koralchapnik , @Kolikant , @ArthurSap , @KaplanAlexander 
pls do:
`git reset --hard 89645e9dd6163e43961b888f1b521ae38127f7d5`
then do pul, **you must do the pulll**:
`git pull`

**Comment by yaelAmitay** [comment]
well unfortunately the group decided to give this up. so I'm closing it.
