### ISSUE TITLE
Move maps to android

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#373]
Right now all our maps related work on the browser but not on the android.
we are going to make them work on the android. 
but then it won't work on the browser anymore.
so I'm moving the map to android on another branch and after a while we will merge the branches.

so we can all still use the browser. (and I'll use android in the other branch) 

The name of the new branch is: android_version

**Comment by yaelAmitay** [comment]
testing on the android; (while the device is connected to your computer via USB)
`cordova platform add android`
`ionic build android`
`ionic run android`

**Comment by yaelAmitay** [comment]
Looks like we won't have to change anything it work for android(I tried version 4.4)

**Comment by kapalex** [comment]
> Working on a fix for android 6.0+

**Comment by yaelAmitay** [comment]
it works for Alex too. no need to change code so far.
