### ISSUE TITLE
user management

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#39]
Everything needed to identify users and give them the different settings that they might want (saving search queries for instance)

**Comment by Kolikant** [comment]
@ArthurSap  
I need a way to recognize admins when I bring them from the server.
have we agreed that there will be only one admin and that his name would be admin? or is there another way to recognize them? (when on server they have no class, only fields) is there a field admin's use that you could maybe add? to be able to diffrentiate

**Comment by ArthurSap** [comment]
We agreed that there are several admin users and that distinguishing admins from users by names is problematic (we agreed to show admin users in different colors once the GUI is up).
Currently, there are no special fields admins need, only methods and I can't think of any right now (on this sprint I mean - on what we agreed admin should be able to use).
Can you use methods to differentiate admins from users? Delete is obviously a method only admin would have and its not going anywhere.
Worst case I/you can add a boolean field (isAdmin) for the class and never use it (and maybe later, if we decide admin needs special fields, we will use those and not the boolean).

**Comment by Kolikant** [comment]
I'll try to figure something out, thanks :)

**Comment by yossigil** [comment]
My $0.02: Don't encode permissions within the type system. It never works. All users should be of the same Java type. But, special operations require the ADMIN bit toggled.

@AdiOmari @zvili @idabran @yh-github @orimarco

**Comment by Kolikant** [comment]
I haven't understood what you said
admin inherits from out user type, his "regular" operations have extensions on user's and work differently. therefor when he is logged in, doing the same operations has different effects.

**Comment by yossigil** [comment]
What I said is that the design is fragile. Say you want to have levels of admins? And how do you promote/demote a user?

Common practice is to use a permissions value, and check permissions at runtime, not compiletime.

**Comment by Kolikant** [comment]
I see.
so in order to be scalable, you suggest that we should put the responsibility of checking priviliges to all the functions which users use?
