### ISSUE TITLE
make showReview the Location page

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#391]
as discussed in #390, showReview will become the Location page. this includes as well as the location review, to have the add review button on it. this page and all services under it are under @ArthurSap

**Comment by ArthurSap** [comment]
Can we close this now?

**Comment by Kolikant** [comment]
If you finished it then sure

**Comment by ArthurSap** [comment]
I'm simply unsure what this issue is about.. If it's to make "show reviews" the first thing you see as a floating window when clicking a location then yes, I finished.

**Comment by Kolikant** [comment]
Okay, then you are finished
