### ISSUE TITLE
Bug list

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#396]
This issue will compile different bugs found during the usage of the project
It will provide a check list of "known bugs" on the way for us to fix them.
**Separate issue should (unless are minor) be created to fix a certain bug and and assigned to the fixer.**

- [x] Login page, on failing to login will get stuck in a spinner - _fixed by Yael_
- [x] When logging into an Admin account, and then refreshing the  page, the side menu shows "User Profile" button instead of "Admin" -  _fixed by Yael_
- [x] On android it doesnt show "admin" button at all, just User Profile-   _fixed by Yael_ 
- [x] On android logout doesn't seem to work -  _fixed by Yael_
- [x] Admin page "most helpful users" allows values higher than 20
- [x] Add spinner to top location and top users from admin page
- [x] Login page spinner not centered (android)  _- fixed by Yael_
- [x] On registration the Home page is opened instead of the map -- _fixed by Alex_
- [x] When adding new location dismiss window 
- [x] When adding new location fails add error
- [x] Clicking on your own locaiton in the map opens a "you are here" pop up, but it is shown on the side of the map and not on the location it self - _the pop up window is now removed_
- [x] Create review should have a text box and not a single line to write a review -- _fixed by Alex_
- [x] You can create multiple locaitons on the same LAT LNG with the same type and subtype
- [x] Reviews for different locations on the same latlng are all shown for each location in the lat lng
- [x] Add review page menu toggle doesnt work (possibly related to how we moved to it from a floating window)
- [x] _maybe_  : Review for a location aren't shown on android, but are on browser
- [x] New actions dont clear old actions from screen (search doesnt clear navigation for example)-Yael, search should not clear navigation and vice versa.

- [x] after signup the user should be already login, right now the user needs to login after sign up.-_fixed by Yael_
- [x] Radius should only be allowed >0 values
- [x] Radius should specify units (meters, km ..)
- [x] When moving to a different page and back the map is not loaded properly -- _fixed by Alex_
- [x] Android 6.0+ after accepting location permission map is not loaded -- _fixed by Alex_
- [x] upvote closes reviews page -- _fixed by Alex_
- [x] Auto capitallization in signup -- _fixed by Alex_

@koralchapnik @yaelAmitay @Kolikant @ArthurSap add additional bugs you run into #

**Comment by yaelAmitay** [comment]
I'll fix some of them right now

**Comment by yaelAmitay** [comment]
I'm updating this issue as I'm go

**Comment by yaelAmitay** [comment]
about these 2:
- [ ] On android it doesnt show "admin" button at all, just User Profile 
- [ ] On android logout doesn't seem to work

what's the problem? It works fine on the android.

**Comment by kapalex** [comment]
On my device when loggin into an admin account I see "User Profile" button and no admin button
in addition when I click logout nothing happens

Maybe something changed since this morning, but thats what happens in that version

**Comment by yaelAmitay** [comment]
maybe you didn't work on the recent version.
Either way if you'll still have problem tell me...

**Comment by kapalex** [comment]
Just installed latest version, still the same
I'm connecting to the server at `kapalex.ddns.net:8090` if that at all matters

**Comment by yaelAmitay** [comment]
maybe the server is not using the recent version?
I'm up-to-date with the git, I'm using my computer as the server but it should not matter cause I'm up-to-date with git.

**Comment by kapalex** [comment]
The servers version was just deployed today

**Comment by kapalex** [comment]
Actually might be related to the server, checking it out

**Comment by kapalex** [comment]
Ok, tried redeploying it just in care - same result

**Comment by yaelAmitay** [comment]
I think it's something with the server. it look like it's not up-to-date.
I'll try to deploy it myself.

**Comment by kapalex** [comment]
ok I'm closing the instance I opened then

**Comment by kapalex** [comment]
dont run the client tho, cause our server cant really handle both of them

**Comment by yaelAmitay** [comment]
okey we moved this discussion to whatsapp. we will update here when we'll know more.

Update: there was a problem with the server, problem was solved

**Comment by yaelAmitay** [comment]
@KaplanAlexander 
about this:
New actions dont clear old actions from screen (search doesnt clear navigation for example)

why should search clear navigation?
I don't think it should.

only new search clear old search and new navigation clear old navigation.

**Comment by kapalex** [comment]
In my opinion it looks very cluttered if both of them stay
If new search removes old search (and the same with navigation) then it's ok, altough I still think it's better removed

**Comment by yaelAmitay** [comment]
We can vote on this as a group.

**Comment by ArthurSap** [comment]
@KaplanAlexander 
Every time I try to update a review with a new up/downvote I get the error "[RxCachedThreadScheduler-5] ERROR s.a.database.ReviewManager - Multiple reviews found, not updating"

Also, add review now goes to a floating window instead of a new page

**Comment by kapalex** [comment]
You should clear the reviews from the db
I'm guessing our testing caused multiple reviews by the same person on the
same location, which is what the error means

**Comment by yaelAmitay** [comment]
Done :)
