### ISSUE TITLE
Write a short comparison between both available Geo APIs for next meeting

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#4]
Google maps API for the map
(available for java via [this](https://github.com/googlemaps/google-maps-services-java))

-Or-

[Geotools](http://www.geotools.org/)

**Comment by yossigil** [comment]
@zvili, @idabran this issue has no milestone, nor assiggnee. I presume @KaplanAlexander is the assignee.

**Comment by kapalex** [comment]
We have not yet set the planned milestone for the project, when we do we shall update this issue accordingly.
I've assigned this to me now

**Comment by idabran** [comment]
so, please set a milestone, and labels, you know the drill, and you should not wait for us

**Comment by yossigil** [comment]
How do we know that this issue is done? 

The issue should be "Write a short report on adequability of x for y'

**Comment by kapalex** [comment]
Another possible solution [JxMaps](https://www.teamdev.com/jxmaps)

**Comment by kapalex** [comment]
Decided on JxMaps - 
- Provides a full solution to our problem
- Very simple java integration 
- Free academic version available
