### ISSUE TITLE
showing adress rather than latlng

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#400]
right now we show users the latlng of chosen locations, needs to be changed into adresess

**Comment by Kolikant** [comment]
not possible in jxMaps, I ='ve been searching for it, it is not an implemented functionality, furthemore, the "adress" attribute is the name of the location and it has been used as so so far, meaning that the adress field has no intention of having an adress.

furthermore, in googlemaps API the action of taking a coordinate and turning it into an adress is called reverse geocoding which does not exist in jxmaps.

good news are, we are going to get rid of jxmaps soon, until then this issue is moot

**Comment by kapalex** [comment]
Keep it open as it will be relevant soon
