### ISSUE TITLE
 There is insufficient memory for the Java Runtime Environment to continue.

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#407]
it's all here #406

**Comment by kapalex** [comment]
A possible solution, which at this point would probably be easier, is completely removing JxMaps and replacing it with the [google maps java sdk](https://github.com/googlemaps/google-maps-services-java)
At this point we don't need to jxmaps gui and just the seach seems to be using it
So I think it might be better to remove completely

@koralchapnik @yaelAmitay @ArthurSap 
Thoughts?

**Comment by Kolikant** [comment]
After broken heartedly removing all of the jxmaps uses last sprint, this would onlt need to change a few dependencies, i concur

**Comment by yaelAmitay** [comment]
I agree

Yael

‫ב-5 ביוני 2017, בשעה 13:56, ‏‏Ariel Kolikant ‏<notifications@github.com> כתב/ה:‬

**Comment by koralchapnik** [comment]
Ariel, did you remove the jxmaps dependencies?

**Comment by ArthurSap** [comment]
If it doesn't require to much work/re-work I'm fine with that. 
Should happen on a separate branch though in case of bugs imo.

**Comment by Kolikant** [comment]
it would demand much work, just won't completely creeple the project as it would have before the changes I made to jxMapsFunctionality

**Comment by kapalex** [comment]
Separate branch is the way to go though

**Comment by kapalex** [comment]
Whos going to be in charge of this?

**Comment by Kolikant** [comment]
Not it, got my work cut out for me

**Comment by kapalex** [comment]
I can, but that means I'm dropping every other task for this sprint, and will almost entirely editing code that is not mine

**Comment by Kolikant** [comment]
That's the problem, you just described what anyone given this task would say

**Comment by kapalex** [comment]
Well, I'll take it then.
