### ISSUE TITLE
Replace JxMaps with Google map java API

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#409]
According to #407

**Comment by kapalex** [comment]
Things to change :
- [x] findNearbyPlaces
- [x] searchQuery
- [x] services

**Comment by kapalex** [comment]
For later this week :
- [x] Fix API key issue

and continue testing

**Comment by kapalex** [comment]
- [x] Fix subtypes to fit PlaceType in google maps

**Comment by kapalex** [comment]
We are officially DONE with Jxmaps :raised_hands:
everything has been commited to the master branch, and as far as I could test works wonderfully
Extremely faster than jxmaps, unsurprisingly

If you do run into problems let me know
@Kolikant @koralchapnik @yaelAmitay @ArthurSap

**Comment by ArthurSap** [comment]
Damn that was fast, gj.

**Comment by Kolikant** [comment]
Thank god

**Comment by Kolikant** [comment]
mmmmm seems that none of the map features work now for me. 

adress search just shows the loadr and ends, location list never finishes and the same with type search

am i missing something?

**Comment by Kolikant** [comment]
reopening because ran into a problem

**Comment by kapalex** [comment]
Open separate issue if still doesn't work after the current phone call we are having
