### ISSUE TITLE
Error in adding location

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#419]
when trying to add location, i'm getting the following error: 
![image](https://user-images.githubusercontent.com/23156121/26837122-4883b786-4ae5-11e7-872f-8c0e1e245807.png)

**Comment by koralchapnik** [comment]
and there are no locations now in the DB

**Comment by Kolikant** [comment]
someone changed the enums.... @KaplanAlexander any reason for that? or can I change them back?

**Comment by Kolikant** [comment]
you know what, all uppercase is just as arbitrary as capitilized, i'll just change it to match all caps then no need to change the enums back to what they were

**Comment by kapalex** [comment]
Yeah it actually is necessary for it to work with google maps place types
So all caps, and if you want to add more locations sub types (we probably
wont though) we need to add from the PlaceType of google maps service
