### ISSUE TITLE
Create new wiki page with class diagram 

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#42]
In our meeting last week we have drafted a class diagram,  this class diagram should be finalized with recent changes and uploaded to the wiki .

**Comment by yossigil** [comment]
Splendid

**Comment by Kolikant** [comment]
did you take a picture of it in the meeting? I see that I haven't

**Comment by kapalex** [comment]
Yes, both me and @assaflu did

**Comment by Kolikant** [comment]
Alex and I made the [wiki page](https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Class-Diagram)

**Comment by yossigil** [comment]
Splendid
