### ISSUE TITLE
show adress to user rather than lat lng

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#422]
reversegeocoding is now available to us, I've finished the service that returns a string in human addresses for a latlng.

the issue was #400 the service is inside searchService and an example for usage is within location-list

I just assigned people who's pages had lat lng displayed for the user, if you don't think you need to change it to an adress, just unasiggn/ close. but one of the complaints we got from the presention was that we were showing latlngs and not adresses, so keep that in mind

**Comment by yaelAmitay** [comment]
done for my part,
let my know if I missed a place

**Comment by ArthurSap** [comment]
Done my part too.
