### ISSUE TITLE
User profile images

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#424]
adding user profile images.

- [x] adding images to our parse server

- [x] create service that accept image from the user and insert the image to the db

- [x] create service that send the image to the user

- [x] client side request the image in the profile page

- [x] enable ionic to access camera/gallery in order to send image to our server

@koralchapnik  and I(Yael) will share the work on this issue duo to it's complexity and lack of time.

**Comment by koralchapnik** [comment]
need to in client side from 'localhost' to the server address. not working for now

**Comment by koralchapnik** [comment]
after all installations and bugs the project now run on my phone and I can start working on uploading photos in client side

**Comment by koralchapnik** [comment]
the installation didn't work.
trying it again

**Comment by koralchapnik** [comment]
after a lot of hours, the installations works! :)

**Comment by yaelAmitay** [comment]
> need to in client side from 'localhost' to the server address. not working for now

maybe try creating the url in the '.ts' and using it in the '.html'
for example:
in the '.ts':
`url = Constatns.ServerAddress+'profileImg?userName'+userName;
`
in the 'html':
`<img src={{url}} />` or `<img src='{{url}}' />`

**Comment by yaelAmitay** [comment]
there are a few bugs but I opened a new issue about them so I'm closing this one.
