### ISSUE TITLE
add option to leave a review on street

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#433]
add option to leave a review on street.

**Comment by yaelAmitay** [comment]
@ArthurSap  you will add the option to review on a street in the client side.
I'll take care of the server side

**Comment by ArthurSap** [comment]
No need, if the only change is that 'subtype=street', I think changing the client side will be enough. Unless there are other additions in the server side.

**Comment by yaelAmitay** [comment]
there are more changes that needed in the server side but they include calling my function so I think I would do it.

**Comment by yaelAmitay** [comment]
I've done my part, let my know when you done. I want to check that my changes were fine.

**Comment by ArthurSap** [comment]
Done

**Comment by ArthurSap** [comment]
Seems like the HTML doesn't show the text, working on it so don't close the issue yet
