### ISSUE TITLE
Working with Continuous Integration

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#44]
As a possible tool for testing the project we could work with a Jenkins server.
What that would mean is having an external server setup that once a day (or possibly every time something is pushed to github) pulls the code from the repository, builds it and runs all our tests on it.  The server will then notify the responsible parties if something is now broken.

This would be a good way of making sure our code is always functional and passing all of the tests.  
It would require us all to only push code that is in working condition.

Setting up the server is not too complicated and I could assign myself to do it.

The question is what do you think about this idea? 
@Kolikant @koralchapnik @yaelAmitay @ArthurSap @assaflu

**Comment by Kolikant** [comment]
Seems highly unnecessary, but if you think that you can do it, it obviously cat hurt

**Comment by yossigil** [comment]
We use travis. It works great. And I think it is quite important to do now, before the flood of commits start! Choose whatever server you fill is good for you.

**Comment by kapalex** [comment]
Will do.
opened relavant issue #45
