### ISSUE TITLE
Nearby location bug

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#448]
While trying to load locations on Bat Hen street in Haifa I have encountered this bug.
Please catch errors from the server and take care of this bug

![image](https://user-images.githubusercontent.com/23156121/27282229-b5c4ee0c-54f7-11e7-8234-782f0b73da74.png)

**Comment by Kolikant** [comment]
It is catching the exception
Had it not caught and displayed it, you wouldn't see anuthing as the aerver would have crushed

Feel free to change the error message displayed to user to one of your liking
