### ISSUE TITLE
Set up jenkins CI

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#45]
Set up a jenkins server to make daily builds and run junit tests

**Comment by kapalex** [comment]
@yossigil two issues I need help with

1. according to the travis user guide I need admin access to the project, and as far as I know I don't currently have it (could be wrong)
2. I need someone to approve my request to access repos from `TechnionYP5777`

Can you help?

**Comment by kapalex** [comment]
I've actually decided for better familiarity with it to set up a Jenkins server
the server is up and running and I will update the info here tomrrow

**Comment by yossigil** [comment]
I reassign to @zvili

**Comment by zvili** [comment]
Travis CI request accepted.

**Comment by kapalex** [comment]
To enable the jenkins server I need to set a webhook in for the project
@zvili can you add the following webhook?
http://163.172.171.65:8080/github-webhook/

**Comment by zvili** [comment]
Webhook added.

**Comment by kapalex** [comment]
The server is not getting the POST when code is pushed to github, I've tested the same thing on my private repo and it worked well
I'm having some difficulty debugging the situation without being able to see the setting in the server
Is it possible for me to get admin rights to the repo for a day, just to set up the CI?

**Comment by yossigil** [comment]
Does travis require admin?

**Comment by kapalex** [comment]
It does

**Comment by zvili** [comment]
Granting you admin rights is not the right solution.
I've made some changes in the GitHub-we hook.
Please try now.
If this still does not help, let's meet tomorrow in my office (#209). Let me know ahead when are you comming.

**Comment by kapalex** [comment]
Still nothing
I'm not going to be at the technion tomorrow, can you meet on monday?

**Comment by zvili** [comment]
Yes. We can meet on Monday.
Most of the day I'm free.

**Comment by yossigil** [comment]
I guess it is too late, but you may want to take a look at [this](https://github.com/TechnionYP5777/SmartCity-ParkingManagement/issues/58#issuecomment-266219962).

**Comment by kapalex** [comment]
@yossigil I'm not sure what I am supposed to see in that issue

**Comment by kapalex** [comment]
@zvili in an effort to solve the problem sooner I've tried testing some more, and I see in the webhooks page for the repo there is (under the Manage webhook section) a section called "recent deliveries"
Can I by chance ask you to send it to me? a printscreen or a text copy would help tremendously

**Comment by zvili** [comment]
No problem. I'll email it tomorrow morning.

Sent from my iPad

On 10 Dec 2016, at 20:13, Alexander Kaplan <notifications@github.com<mailto:notifications@github.com>> wrote:


@zvili<https://github.com/zvili> in an effort to solve the problem sooner I've tried testing some more, and I see in the webhooks page for the repo there is (under the Manage webhook section) a section called "recent deliveries"
Can I by chance ask you to send it to me? a printscreen or a text copy would help tremendously

�

**Comment by kapalex** [comment]
Set a build once every two hours as a temporary solution until we figure out the problem

**Comment by yossigil** [comment]
Excellent work @KaplanAlexander #11 !

**Comment by kapalex** [comment]
added automatic issue creation upon build failure
_to be tested upon next build scheduled at 10:00_

**Comment by kapalex** [comment]
@zvili possible solution to the problem : add a trailing '/' to the url of the web hook
(i.e.  http://163.172.171.65:8080/github-webhook  -> http://163.172.171.65:8080/github-webhook/ )

**Comment by zvili** [comment]
Trailing "/" added to the URL of the Webhook.

**Comment by kapalex** [comment]
Jenkins CI officially up and running and building every push!

**Comment by kapalex** [comment]
@zvili could you take our project out of travis ci?  now that we have jenkins working we don't need it

**Comment by kapalex** [comment]
found a way to disable it myself, closed.
