### ISSUE TITLE
need minor change in two DB methods

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#455]
in the DB methods: 

-  mostHelpful(int n, ICallback<List<UserProfile>> callback) 

- getTopRated(LatLng l, double radius, int n, ICallback<List<Location>> callback)

if n is bigger than the number of locations or users, just return the existing users/locations without throwing an exception

**Comment by kapalex** [comment]
Note that this is already the behaviour for mostHelful users, just the getTopRated need to be fixed

**Comment by kapalex** [comment]
I just tested it out in the app for both locations and users and both work perfectly, returning the the amount of users\locs when n is bigger.
(Only problem I ran into is a spinner not disappearing on top rated location)
Note that I tested it on my phone with a version I put on it yesterday.
Either way the bug doesn't seem to be with me.
