### ISSUE TITLE
Add authors to client side

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#462]
add authors to files you have written in the client side.
most of the files in server side are documented but if you forgot to add author then add it too.

mark and unassign yourself when you're done: 

 

- [x] yael

 

- [x] ariel

 

- [x] arthur

 

- [x] alex

 

- [x] koral

**Comment by kapalex** [comment]
My job on the client side was mostly changing other peoples pages (mostly design, some others) so I didn't author any

**Comment by yaelAmitay** [comment]
to the *.ts only or to the html as well?

**Comment by koralchapnik** [comment]
HTML as well
