### ISSUE TITLE
How can I install the project as a user ? 

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/SmartCity-Accessibility#468]
How can I use the project as a client ? 
Do I have to install everything as a developer just then use it ?

**Comment by koralchapnik** [comment]
no, the apk is in the playstore

**Comment by yonzarecki** [comment]
Great! I didn't see that written there.

**Comment by yonzarecki** [comment]
Maybe its a good idea to add that there, I had no idea what app it was until I saw the screenshots.

**Comment by kapalex** [comment]
There is a link in the readme, and also at the end of the developer instructions
