### ISSUE TITLE
change the review constructor 

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#47]
when a review is just made, it has no like nor dislikes and is therefor at a rating of 0. 
edit- it therefor has a like/dislike of 0

**Comment by koralchapnik** [comment]
When review is just made someone just have rated the route/location.  Therefore it actually does have rating.

**Comment by Kolikant** [comment]
you are right, I got confused. 
therefor likes/dislike counter should be added and set to 0 (is what i intended)

**Comment by Kolikant** [comment]
I resolved what I thought but added signitures on what I've changed.
please review and if you agree with changes, close the issue.

**Comment by koralchapnik** [comment]
accepted
