### ISSUE TITLE
Main screen showing "Loading Map" endlessly...

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Accessibility#470]
![image](https://user-images.githubusercontent.com/12379320/27768899-6c3801ae-5f27-11e7-9684-306938cab466.png)

**Comment by koralchapnik** [comment]
turn the location on

**Comment by Kolikant** [comment]
turn on gps and check wifi

**Comment by ArthurSap** [comment]
turn on your GPS

**Comment by KaplanAlexander** [comment]
turn on your GPS

**Comment by SharonKL** [comment]
Turn on GPS

**Comment by IdanAtias** [comment]
GPS is on and also Wifi.
What am i missing?

**Comment by yaelAmitay** [comment]
close and reopen the app

**Comment by IdanAtias** [comment]
Same...
Maybe I'll try with the 4G instead of WiFi?

**Comment by yaelAmitay** [comment]
it might be problem with slow wifi

**Comment by IdanAtias** [comment]
or maybe i need to be outdoors for the gps to "work"?

**Comment by yaelAmitay** [comment]
it works indoors, try to switch to another wifi network

**Comment by IdanAtias** [comment]
tried both with TechPublic & StudentsWiFi. Remains the same...

**Comment by yaelAmitay** [comment]
you can install ionic and run the project on your computer and use the **_cable internet_**

**Comment by yaelAmitay** [comment]
you can find installation instructions [here](https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Developer-installation-instructions)

**Comment by IdanAtias** [comment]
Ok i'll try it

**Comment by inbalzukerman** [comment]
It still doesn't work for me...

**Comment by yaelAmitay** [comment]
what kind of andorid do you have? whats your operation system? @inbalzukerman

**Comment by yaelAmitay** [comment]
can we close it? everybody managed to see the map?

**Comment by inbalzukerman** [comment]
Yep, sorry for not answering before, didn't get the notification on a new comment 😕
