### ISSUE TITLE
Non informative error alerts

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/SmartCity-Accessibility#472]
errors pop ups are not informative enough -
"error: undefined"
" Illegal address" (I live there, I hope it is legal 😅  )

**Comment by yaelAmitay** [comment]
@Kolikant , @koralchapnik

**Comment by koralchapnik** [comment]
what address did you entered ?
and where ?

**Comment by Kolikant** [comment]
are you sure! that your house exists?

**Comment by inbalzukerman** [comment]
Pretty sure 👍 
It worked though on the 3rd try.. I had to enter a different address before

**Comment by koralchapnik** [comment]
what is the address?

**Comment by inbalzukerman** [comment]
The problem is not the address, it is the error pop ups..

**Comment by koralchapnik** [comment]
tell us what is the exact use case so we can see it in our phones

**Comment by inbalzukerman** [comment]
1. Wait to the map to load
2. register
3. enter "Jerusalem, Moshe kol 64"

**Comment by NivShalmon** [comment]
The [error message](http://i65.tinypic.com/zlxamp.png) when trying to register an already existing user name suffers from the same issue

**Comment by Kolikant** [comment]
wasn't able to recreate the problem.
probably some issue with the server, will need to change error to user to be more specific of this
thank you!

**Comment by yaelAmitay** [comment]
@NivShalmon,  whats the problem with the massage in sign up? it tells you exactly  what the problem is.

**Comment by NivShalmon** [comment]
@yaelAmitay in a sea of unrealted info. The message should be "username already taken" or something similar, not three lines in which the actual error is hidden

**Comment by ArthurSap** [comment]
@NivShalmon This error could arise from several **different** problems hence the three lines, this is not a "sea of unrelated info" m8, but a sea of possibilities

**Comment by NivShalmon** [comment]
@ArthurSap that makes this even worse. As a user, there is a huge difference between "use name already taken" to "connection failed". In the former I need to change my user name, while in the latter I simply need to try again with the same use name and password.

**Comment by yaelAmitay** [comment]
@NivShalmon  okey we will take your note into consideration.

**Comment by yaelAmitay** [comment]
we changed the error msg of failed signup a little. thank you for your contribution.
