### ISSUE TITLE
bug: can't find navigation from current location to leumi bank

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/SmartCity-Accessibility#473]
I'm getting a "Bad request" when trying to use navigation to this location.
Its weird because it works fine on other locations, this is the only one I've tried that doesn't work.

Great app otherwise !

![image](https://user-images.githubusercontent.com/23148393/27769135-e6cdf37a-5f2b-11e7-91b1-c30501dac13a.png)

**Comment by yaelAmitay** [comment]
could be that a few things:
1. internet connection is bad -> try again
2. we already have some location in our db so might it's could not find an accessible route.

**Comment by yonzarecki** [comment]
OK
I don't think this is an internet problem as other location work.
Maybe it really doesn't find a route.. idk
A more informative error message would be appreciated.

**Comment by yaelAmitay** [comment]
noted! thank you for your contribution :)

**Comment by yaelAmitay** [comment]
well apparently we had bug in getting the real error message  so it showed you the default message. I fixed it now. 
you can only see the fix in git and not in the old apk.(ofcourse)

**Comment by yonzarecki** [comment]
Great !
