### ISSUE TITLE
navigation fails with odd message

### ISSUE THREAD

**Issue by NivShalmon** [TechnionYP5777/SmartCity-Accessibility#474]
I picked a location inside the technion and asked for navigation to it, and got the following message:
![default](https://user-images.githubusercontent.com/18422810/27769239-6e04fe36-5f2e-11e7-89d4-0539065c7bed.jpg)

the location is around the student's union buidling according to the image shown. Tried with both 5 star requirement and 1 star requirement and got the same result. Currently in taub

**Comment by yaelAmitay** [comment]
I agree it's odd explantion. It just couldn't find a route or you don't have interent connection.

try to navigate to place outside the technion.

**Comment by NivShalmon** [comment]
works when navigating outside of the technion

**Comment by yaelAmitay** [comment]
okey the navaigation service that we use does not suppot routing inside the technion. 
thank you for your contribution.

**Comment by yaelAmitay** [comment]
well apparently we had bug in getting the real error message  so it showed you the default message. I fixed it now. 
you can only see the fix in git and not in the old apk.(ofcourse)
