### ISSUE TITLE
Custom location not showing when advance searching, but do show when I click on the map

### ISSUE THREAD

**Issue by SharonKL** [TechnionYP5777/SmartCity-Accessibility#477]
I tried adding a new location (a hotel in Taub) and by clicking on Taub, selecting "Nearby Locations" and then "Add New Location". When I try clicking on the map and search for Nearby Locations the taub hotel shows as expected, but when I try to do an Advanced Search and search for hotels around taub, the hotel doesn't show.

Any particular reason or is it a minor bug?

**Comment by yaelAmitay** [comment]
@koralchapnik

**Comment by ArthurSap** [comment]
It's because we can't have good things in taub

**Comment by koralchapnik** [comment]
It was in the code and then the search took a **lot** of time because of the DataBase is very slow so we decided to remove it

**Comment by koralchapnik** [comment]
I will add it again now

**Comment by Kolikant** [comment]
was fixed, thank you
