### ISSUE TITLE
Error while trying to signup

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Accessibility#479]
While running your app localy on my computer, I tried to signup with username "idan" and pass "1234" ad got this error:

![image](https://user-images.githubusercontent.com/12379320/27787866-04c4419a-5fef-11e7-8f2c-7dfc724ffec9.png)

**Comment by yaelAmitay** [comment]
are you connected to the interent?

**Comment by IdanAtias** [comment]
![image](https://user-images.githubusercontent.com/12379320/27788101-ea6043e8-5fef-11e7-9a3a-d185b5f61b83.png)

**Comment by yaelAmitay** [comment]
can you try again? Looks like this message appear if the application can't access the server.
maybe you have slow connection and the application had timeout

**Comment by IdanAtias** [comment]
if that is the case then maybe the "error" popup should be more informative, and contain the error reason.
Anyway, i'll check it again - tnx.

**Comment by yaelAmitay** [comment]
you are right, right now we are not telling our costumer if there are problems in the network connection .
We cannot fix it right away, we think we can fix it but not in a short amount of time.
thank you for your contributaion. please let us know if you this message keeps showing up.
