### ISSUE TITLE
Application hangs when navigation to a far off location

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/SmartCity-Accessibility#480]
It tried navigating from the Technion to a street in tel aviv, and the application just hangs.
If this is too much calculations, you can disable navigations to such far off locations. No one will walk that far anyways.
![image](https://user-images.githubusercontent.com/23148393/27787998-8847f188-5fef-11e7-94ea-b86a887a55de.png)

**Comment by yaelAmitay** [comment]
Our application is slow because we are using free DB. 
and of course for long routes the calculation takes time. 
we can block long route. we need to think about it as a group.
thank you for your suggestion :)

**Comment by yonzarecki** [comment]
OK, understandable. 
Closing.
