### ISSUE TITLE
Login and Sign-up stopped working 

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/SmartCity-Accessibility#482]
I've tried logging in using both faculty internet and cellular internet and it doesn't work.
Still it's probably an issue with the server or internet connection.
![image](https://user-images.githubusercontent.com/23148393/27789684-2921821c-5ff6-11e7-94e7-32f6943f9ea7.png)

**Comment by Kolikant** [comment]
yes, the problem is the internet :\
I have fast response from my 4G internet, but the other group members using wifi in the group also have difficulties now

**Comment by yonzarecki** [comment]
Too bad.. I can't continue checking the project :(

**Comment by yaelAmitay** [comment]
We know but we don't have control over the quality of the internet in the faculty
