### ISSUE TITLE
"Go back to map" should me in a more reachable place

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Accessibility#483]
Took me some time to find out that it's location is shown only after clicking the "hamburger".
![image](https://user-images.githubusercontent.com/12379320/27790755-91252680-5ffa-11e7-90f8-d8f3af6c9114.png)

![image](https://user-images.githubusercontent.com/12379320/27790773-ac2d32f6-5ffa-11e7-9cf1-bcc77093189a.png)

**Comment by yaelAmitay** [comment]
Right now it's in the menu (the button map).
this was our desgin choice.
but we will take your note under consideration. thank you :)
