### ISSUE TITLE
Error msg while trying to "Strat Navigation"

### ISSUE THREAD

**Issue by IdanAtias** [TechnionYP5777/SmartCity-Accessibility#484]
After choosing location in the map i got the following screen:
![image](https://user-images.githubusercontent.com/12379320/27790815-d7ee7062-5ffa-11e7-9843-207799dbf163.png)

and after clicking start navigation i got this:
![image](https://user-images.githubusercontent.com/12379320/27790828-ea0ab792-5ffa-11e7-9b7e-d67e4f66c027.png)

**Comment by yaelAmitay** [comment]
this is a wifi problem. as I explained #479
