### ISSUE TITLE
Decide how Admin Reviews should be treated

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#49]
so far admin reviews were discussed to be simply more important, the question remaining is in what way.

the obvious choice would be that admin's reviews would always be considered to be in the "best reviews", but the meaning of their reviews should be discussed

**Comment by ArthurSap** [comment]
We decided on our meeting that admins' reviews are simply automatically pinned.
(Already implemented that).
So I'm closing this issue for now (until we might want to add more behavior later).
