### ISSUE TITLE
favourite Queries

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#50]
users recent search queries are to be added to his favourite list,
user can also modify his favorite list by hand, adding or removing queries.

**Comment by Kolikant** [comment]
User's favourite queries can be stored and are loaded with them when they log in. exactly what those queries contain is yet to be determined

**Comment by yossigil** [comment]
I would avoid the UI for managing favorites. I would just keep the last ten for the prototype
