### ISSUE TITLE
Navigation API allows to declared location as non-accessible 

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#52]
The navigation API will allow it's clients to add a location to the list of non-accessible locations.
This means that when asked for a route the navegation algorithm won't allow the route to pass throught non-accessible locations.
pay attention that if a location is non-accessible that means that the map segement that contains this location is not accessible.
(map segement is the smallest segement in the map to contains a location)

relate to issue #19

**Comment by Kolikant** [comment]
user does not at all define locations as unaccessible. 
that is determined by the social network and the best reviews  #25

**Comment by yaelAmitay** [comment]
Yes, I meant client of my API.
"The navegation **API** will allow **it's clients** to add a location"

**Comment by yaelAmitay** [comment]
I'll change the title so it'll be more clear.

**Comment by yaelAmitay** [comment]
After our meeting yesterday this issue is no longer relevant. I'll open a new issue that is more accurate.
