### ISSUE TITLE
Create class MapSegment

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#53]
MapSegment is a class that represent the smallest segement of the map.
When a location is declared non-accessible the whole segement that contains him is declared non-accessible too.
Beware that we are using MapQuest service. In MapQuest the map segment is represented by LinkId. therefore this class will probably wrap LinkId.

relevent to issues: #19, #51 , #52

**Comment by Kolikant** [comment]
add map segments to the wiki. we have no idea what that is.

**Comment by yaelAmitay** [comment]
Will be added soon

**Comment by yaelAmitay** [comment]
wiki explantion was added: 
https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Navigation-explanation

**Comment by yaelAmitay** [comment]
done.

**Comment by yossigil** [comment]
You can close it with the commit message
