### ISSUE TITLE
Create classes to support route request/response from MapQuest

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#54]
MapQuest API is a web service that helps us navegate in the city.
We are using this service in order to find a route that does not goes through non-accessible locations.
This is a REST service, therefore we need to create classes to supprot the request/response to/from the server. Each request/response pass/receives Objects to/from the server by using json. that's why we need to add classes that contains the information that we pass/receive to/from the MapQuest server.

relate to issue #19

**Comment by yossigil** [comment]
:+1:

**Comment by yaelAmitay** [comment]
progress: added some classes, more classes will be added soon.

**Comment by yaelAmitay** [comment]
Done. if I'll need more classes I'll add them separately in different issue.
