### ISSUE TITLE
Add Class Diagram for navigation

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#56]
Add ClassDiagram for navigation to the wiki page.

**Comment by yaelAmitay** [comment]
Explantion was added to Wiki:
https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Navigation-explanation
the class diagram will be added soon.

**Comment by yaelAmitay** [comment]
draft of class diagram was added:
https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Class-Diagram
I'm closing this issue but more classes will be updated in the class diagram in the future.

**Comment by yossigil** [comment]
:+1:
