### ISSUE TITLE
add Location Manager

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#57]
save locations and allow queries on the locations

- [ ]  get all location under threshold in a radius

**Comment by yossigil** [comment]
:+1:

**Comment by yaelAmitay** [comment]
I added a stub to managerLocation for this issue @assaflu 
I also added a few lines to explain what I need from this class. 
And this issue might help too. #65

**Comment by yossigil** [comment]
@assaflu...

**Comment by assaflu** [comment]
@yaelAmitay sorry about the late implementation

**Comment by yaelAmitay** [comment]
@assaflu  hi I read your comments in LocationManager
you can change the return value from List(Location) to List(LatLng) just let me know so I'll change my code too.
About the threshold it should be named score in the code, and i think @Kolikant is in charge of that. 
Or at least I know he opened an issue about it.
Let me know here if you want to discussed more about details.

**Comment by Kolikant** [comment]
I am not, 
@koralchapnik

**Comment by yaelAmitay** [comment]
@Kolikant  what about issue #76?

**Comment by Kolikant** [comment]
Yes, i filter it, but koral calculates it.
(you are right that i am relevant but koral is more so)

**Comment by yossigil** [comment]
Without getting into the details of 

```
@assaflu hi I read your comments in LocationManager
you can change the return value from List(Location) to List(LatLng) just let me know so I'll change my code too.
```

a small comment: if A changes the code that interacts with B, then A in his agility should change B's code as well.

**Comment by koralchapnik** [comment]
@assaflu the method that calculates the score called getReting() and you can find it in Location class.
If you mean something else tell me :)

**Comment by yaelAmitay** [comment]
@assaflu hi I changed the return value from List(Location) to List(LatLng).

**Comment by Kolikant** [comment]
We need the location list for later on(in the displays)
Could you maybe add a second method instead or maybe add a map on the output of the original method?

**Comment by yaelAmitay** [comment]
I can change it back, I only changed it because @assaflu  asked me to.
talk to him about it.

**Comment by yossigil** [comment]
:+1:  good cooperation

**Comment by kapalex** [comment]
`getLocation(LatLng)` function in `LocationManager` works in the background (uses internal callback you defined) but returns result as if it works in foreground
I'm trying to use it from the GUI to get the locaiton based on a latlng, I should either be given to option to give a callback function of my own (best option) and it happen in the background, or it needs to happen in the foreground
Right now I'm just getting errors and wierd behavior

**Comment by assaflu** [comment]
@koralchapnik @Kolikant  due to changes in the class "Location" I dont quit understand what to do with all the fields and if they are relevant to save in the DB

**Comment by Kolikant** [comment]
Resolved? Or need explanation?
