### ISSUE TITLE
add the three sub locations and interface them with JxMaps

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#58]
there are three classes inheriting from location. create them all and add what they require.
Explanation [here](https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Location-classes)

- [ ]  all classes have getCoordinate

**Comment by yossigil** [comment]
:+1:

**Comment by koralchapnik** [comment]
After looking at JxMaps API I think that there are only two classes inheriting from Location derived from JxMaps classes GeocoderResult and PlaceResult.
@Kolikant what do you think about that ?

**Comment by kapalex** [comment]
I think the idea was the third one to have a simple LatLng component in it

**Comment by koralchapnik** [comment]
Both has method that returns the LatLng, do you think it still necessary?

**Comment by kapalex** [comment]
The idea is to have some class to recognize location that don't have an official representation in the JxMaps (maybe a shop that doesn't have info in google maps and people still want to leave a review) so it will be marked with just a LatLng coordinate

**Comment by koralchapnik** [comment]
Now I understand,  thanks

**Comment by Kolikant** [comment]
Locations
Are -- our --presentation of the data
Containing our information
They need not be equivelant to a jxmaps class

**Comment by koralchapnik** [comment]
I think that Alex has explained that good enough

**Comment by Kolikant** [comment]
Oh, sorry

**Comment by koralchapnik** [comment]
What I'm gonna do : 
Add three classes inherit from Location : Street, Facility and Coordinates that will encapsulate the JxMaps capabilities for our own needs.

**Comment by kapalex** [comment]
Should be changed according to #145 , open a new issue if you see fit

**Comment by kapalex** [comment]
closing this as it is no longer relevant
