### ISSUE TITLE
add pinned and unpinned to the location

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#59]
as described in the wiki under 5 clarrification

**Comment by yossigil** [comment]
:+1:

**Comment by ArthurSap** [comment]
@Kolikant  @koralchapnik Is that okay that I will add another List to the Location class (pinnedReviews or something) so that I can work on this issue? With all the methods I need.
Or should I leave it to you?

**Comment by koralchapnik** [comment]
Do stubs,  I'll implement it after you'll make them

**Comment by ArthurSap** [comment]
@koralchapnik I can get around with getters for both lists or with 2 methods to do each action.
I will implements it with getters - save you some work and seems like a better idea.
If you want to do it differently later let me know too.

**Comment by koralchapnik** [comment]
So you're adding two getters to  Location class?

**Comment by ArthurSap** [comment]
Yes, and a new private ArrayList<Review> variable.

**Comment by koralchapnik** [comment]
No problem

**Comment by ArthurSap** [comment]
I added the logic for the admin - all that remains is to implement the logic whilst presenting the reviews (i.e taking pinnedReviews list in each location into account) so I'm closing this issue.
