### ISSUE TITLE
no idea how the dependecies work now

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#66]
I tried to do the updates that were scattered across github.
they have not worked.
whoever changed the dependencies, please make a single answer as to how to get it to work (from having cloned a new project) :) I wpent a lot of time trying to get it to work. I cant work until it does.
@KaplanAlexander @koralchapnik @yaelAmitay  @assaflu @ArthurSap.
create it's own wiki or something, the one existing now is either not updated or wrong (from the point of having a clean just clones project)

**Comment by kapalex** [comment]
Solution here #61 , last comment
which references the relevant wiki, and I also sent it to the entire group
_did a clean build myself and it worked, if you want to address a specific issue, message me_

**Comment by Kolikant** [comment]
that solution does not work

**Comment by Kolikant** [comment]
I received it. fished the scattred details and followed it. it had not worked, after doing it and checking myself I opened this issue as it is evedently not working.
please check if you might have missed something

**Comment by kapalex** [comment]
It in fact does work both on the build server and my environment, and if you would provide any specific problem, looking for a solution would be a lot easier.

**Comment by Kolikant** [comment]
the same as any maven problem, unrecognized dependencies

**Comment by kapalex** [comment]
Issue found and fixed
