### ISSUE TITLE
Save Queries and Load Queries as String (parse them)

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#68]
our server doesn't allow to save elaborate types on it, so search queries will be saved as a string and parsed back and forth. I will add the stubs and implement them when Search queries grows in power

**Comment by Kolikant** [comment]
forgot to mention in last commit that allthe base is set for the parse back and forth, just need to decide what fields SearchQuery should have

**Comment by yossigil** [comment]
Good design decision to use strings @Kolikant

**Comment by Kolikant** [comment]
well the methods are there pretty much the day I opened this, just left it open as a reminder that if fields are ever open, to take them to account in the parsing, since I am in charge of that class the reminder is unnecessary
