### ISSUE TITLE
what to show on the presentation?

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#70]
we might want to add gui now, for us to present some abilities at the presentation.
what do you believe that can be presented until then? 
user login, sign up can, what else?

@koralchapnik  @KaplanAlexander @yaelAmitay  @assaflu @ArthurSap

**Comment by yossigil** [comment]
Good leadership @Kolikant 

Everyone should try to demonsrate he or she introduced

**Comment by kapalex** [comment]
I can show some of the functionality the DatabaseManager holds for communication with the server (should include location based queries by the presentation)
I think other than gui everyone can create some tests that demonstrate functionalities (in addition to actually testing) they wrote

**Comment by yaelAmitay** [comment]
We already discussed this on our meeting this week...
I'm responsible for the navigatoin, I can show points in the roure(my output) or hopefully some images of the route.

**Comment by Kolikant** [comment]
I can now show search results for specific adresses. 
please make a test that shows the abilities you want us to present :)
