### ISSUE TITLE
Synchronized access to reviews/locations

### ISSUE THREAD

**Issue by ArthurSap** [TechnionYP5777/SmartCity-Accessibility#71]
As @KaplanAlexander pointed in #32 , we need to synchronize reviews' deletion.
Questions are:
1) How? Using locks doesn't sound like a good idea. I thought maybe putting the review in a new DB so that if a review is in that DB it a) won't be shown on a location b) whenever a user access to such a review (if for example he opened it and while reading it an admin deleted it i.e moved it to the new DB) he won't be able to affect it and c) after X time/#reviews the DB would be emptied.
2) Are there any other cases where we might want to sync. access to reviews?
3) On the same note - should we sync. access to locations? Say a user is watching a cafe and another user added a review to that place - do we want to show him that review live, notify him of a new review live or not do anything?

What do you guys think @Kolikant @yaelAmitay @koralchapnik @assaflu @KaplanAlexander

**Comment by yaelAmitay** [comment]
What's worng with java's synchronize?

**Comment by Kolikant** [comment]
Not sure i understood everything, so tell me if something is nissing
Reviews are saved on the parse server, when a client looks at locations, he imports the reviews of the things he searched for, offering a local save.
Were someone to delete the reviews when they are already in his device, all that needs happen is that the next user to look at the reviews, wont see them.
The server we are using should be able to deal with these simultanious reads and deletions on the way i dicribed.
Showing live seems both needless and unnecessary to the usage we had inmind, which is a more static aproach od the information.

**Comment by ArthurSap** [comment]
Question is:
User is reading review R
Admin deletes review R
User comments on/like review R
What happens now? The review is re-inserted to the DB (which it shouldn't do 'cause we deleted it)? The user receives a crash? Or what

**Comment by koralchapnik** [comment]
I think that when the admit deletes it it should be deleted from all the users.

**Comment by koralchapnik** [comment]
Maybe we can add a flag to review says the admin has deleted it? 
And when trying to access this review by a user to shoe him rellevant error message?  
Or that we want the user couldn't even see the review after the admin has deleted it?

**Comment by Kolikant** [comment]
Very simple, in my opinion
User sees reveiw, when he likes/dislikes it, the information on his device
changes, but when we come to save it to the db, it wont save sonce the
review was deleted.

It would be the same as having deleted the review, but with no need to
constantly synchronize

Anyone looking at reviews -after- the delete, would not see it
Anyone who got the reviews before would.



בתאריך 18 בדצמ' 2016 13:05,‏ "koralchapnik" <notifications@github.com> כתב:

**Comment by kapalex** [comment]
@Kolikant that does seem like a good way of doing it
I can add an update function for DatabaseManager ( #33 ) that will first get the item from the DB (assuring us it still exists) and only then saving the new information

**Comment by ArthurSap** [comment]
Question is how will the DB know if the admin deleted it? It might as well as treat that review as a newly posted review.

**Comment by ArthurSap** [comment]
Hopefully everything works now.
I'm closing this @KaplanAlexander .
