### ISSUE TITLE
Adding Mockito dependency to the pom

### ISSUE THREAD

**Issue by ArthurSap** [TechnionYP5777/SmartCity-Accessibility#72]
I wrote a test for admin but got an error while adding reviews in a different class so I decided to work with mockito to prevent future bugs like that.
I'm adding mockito dependency to the pom.xml, FYI @KaplanAlexander 
I will also commit the test that didn't pass so whomever it may concern can see what was the problem (FYI @assaflu @yossigil )

**Comment by yossigil** [comment]
:+1:

**Comment by yossigil** [comment]
no label/no milestone/no assignee = BAD KARMA...
@zvili @idabran
