### ISSUE TITLE
Add the bot to the accounts with write access to this repository

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#75]
Can you add account who created issue #73 
this is an account I made to better clarify that automatic issues are not created or regulated by me, as up until now they were created by my account.
The account needs write access to be able to mark commits as successful or failed.

**Comment by zvili** [comment]
I've sent an invitation to JuanJenkinsBot to join your repository.
Who is going to ack this invitation ?

**Comment by kapalex** [comment]
I have accepted the invitation from the bot account, thank you.

**Comment by zvili** [comment]
"Your wish is my command" (Aladdin). :smile:
