### ISSUE TITLE
filter locations by acessibility

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#76]
As agreed in our discussions, though i noticed an issue was not opened for it, having method have a method. That recieves an acessibility level and returns whether the location is above or bellow it,
As to allow filtering by our information

**Comment by yaelAmitay** [comment]
@Kolikant , this is more relevant to @assaflu .
He needs to get all the locations below the threshold  in some radius and give them back to me.
Make sure you are not implementing the same thing :\

**Comment by Kolikant** [comment]
We are not

**Comment by Kolikant** [comment]
Mine is the filter by acessibility and his is the one getting bybradius
