### ISSUE TITLE
Fix UserManagerTest.test2 

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#79]
Full output can be found here #73

**Comment by Kolikant** [comment]
done

**Comment by kapalex** [comment]
Actually it caused the same issue as with the search test.  I added the same solution I talked about in #74 and its ok now, welcome to edit it as you see fit

**Comment by Kolikant** [comment]
the test doesn't have a map component. the test does not fail at all running on my pc, even when I add the faults on the server (parse server) that caused it.
I don't believe that it is the right solution for whyever jenkins is failing it, as it is not using map at all

**Comment by kapalex** [comment]
Again, fix as you see fit.
I did see it failing with the same error and have seen it uses the search component, so I figured it dies use jxmaps through it.
Will look into it if you claim otherwise

**Comment by Kolikant** [comment]
tbh, those tests were sanity checks for me, using parse servers through my classes, making sure it works right.
the OOP way would be using mockito now that I know i'm using the server right.
so I'll use mockito and hide the evil server (probably the time taking the server to respond is what pisses jenkins off?)

**Comment by kapalex** [comment]
actualy no, the communication with the server seems completely fine (as evident by my tests at Databasemanger that at the moment use the server as well)
as far as I could tell the problem is with display components from jxmaps that are based on chromium that won't run without a display

**Comment by kapalex** [comment]
you can actually see that it calls JxMaps since you see the license validation in the output

**Comment by kapalex** [comment]
I encountered a weird behavior today while running my tests where a session create by user login was left unattended and resulted in number of tests failing because of session errors
I've added a small piece of code to user management test in `@After` that helped solve that, i'm leaving the rest of the issue to you

**Comment by Kolikant** [comment]
Okay, thanks, wierd, I am yet to encounter any similiar behaviour, but will try to put what you said solves it into the method implementations.

Since i am yet to see the test actually fail on my device, you'll need to tell me if it worked

**Comment by Kolikant** [comment]
I added the logout of curruser that you said helped, into the implementation of usermanager. 
my tests pass consistently, same as before, tell me if they still fail for you :\ @KaplanAlexander

**Comment by kapalex** [comment]
Seems that all is well although the problem itself was inconsistent.
We'll assume it work as expected now and if we run into it again we'll open a seperate issue

**Comment by Kolikant** [comment]
Though i am yet to encounter said problem myself, this did getme to fix a different problem, so we have thT
