### ISSUE TITLE
Question regarding the rating of Location

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#83]
In Location class, we have two lists : one of reviews and another of pinnedReviews. 
I have two questions regarding the rating of a location:
1. if there is no reviews at all we should return the minimal\maximal score ? 
(i.e which on of them representing an accessible location an which one an unaccessible ? 
2. if there are a pinned reviews ? how should we treat them ? 

what do you guys think ? @yaelAmitay @ArthurSap @Kolikant @KaplanAlexander @assaflu

**Comment by Kolikant** [comment]
Default is min
Pinned reviews are always counted as "bwst x reviews"

**Comment by Kolikant** [comment]
Min being ininaccessible

**Comment by koralchapnik** [comment]
Thanks
