### ISSUE TITLE
Should Location and SearchQuery extends MapView?

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#90]
Currently both `Location` and `SearchQuery` class extend MapView.
I think this should be changed so they get a MapView component upon initialization and use that for all their requirements.
There shouldn't be a MapView component created for each class as this is a GUI component and should be singular for the whole app (the view that the user sees) and should be passed on to different components for their need  (In addition to allowing dependency injection for testing needs).

Opinions? @koralchapnik @Kolikant

**Comment by koralchapnik** [comment]
@KaplanAlexander  Just clarify me what did you mean: 
Location and SearchQuery will get a MapView singleton object in the constructor or will have a static field of MapView ?

**Comment by kapalex** [comment]
in the constructor they will get a MapView object (doesn't have to be a singleton, although in practice there will probably be one).
In the program itself (not when testing) this will be the object that displays the map to the user

**Comment by koralchapnik** [comment]
Ok, I think its a good idea.
we'll wait to Ariel's opinion and then decide

**Comment by Kolikant** [comment]
They really shouldnt, the reason that they do is due to the fact that up to now aby attempt of using any method rewuired them to inherit.
If what you say works, it is the obvious choice.

**Comment by kapalex** [comment]
Don't see a reason why it wouldnt, as long as a MapView is given the functions needed public
Closing this, you can open issues according to each class

**Comment by Kolikant** [comment]
I saw no reason it shouldnt work either
And yet it didn't
