### ISSUE TITLE
Should we replace JxMaps with GMapsFx?

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#92]
This was raised as a question after the last presentation.
[GMapsFX](https://github.com/rterp/GMapsFX)

Things that seems to be in favor of switching :
- GMapsFX works with JavaFX natively, a thing that JxMaps claims to do as well but doesn't seem to actually work (failure on trying to import the javafx instead of swing library of JxMaps).  Swing is an outdated GUI library and we really should be working with javafx.
- It is open source which is very convenient to work with.
- After actually working a bit with JxMaps (and as been raised by most people in the project) it seems to be very poorly built and not very convenient to use.

While the above is true this would require alot of changes as we already started working with jxmaps.
Most of all this seems to effect @yaelAmitay so your opinion will be deciding on this point.

Thoughts?  @Kolikant @koralchapnik @ArthurSap @assaflu

**Comment by Kolikant** [comment]
This effects my code immensly. The past weeks i worked only with jxmaps. and as ive said already i would rather test it first which i didn't get to yet

**Comment by kapalex** [comment]
This is why this issue exists, test it and share your opinion here
We won't be switching quickly as, like you said, this effects a lot of code (mentioned @yaelAmitay specifically because I think she has done the most work with the api)

**Comment by kapalex** [comment]
I added the dependency to the pom for anyone who wants to test it out

**Comment by Kolikant** [comment]
The people who touched the api 
Are @koralchapnik, @yaelAmitay and I

Even without looking at GMapsFX i can be certain that it would probably be betterthan jxmaps

**Comment by yaelAmitay** [comment]
I'll check it out and return to you with my conclusions...
I just wand to add that I didn't encounter any problem with JxMaps

**Comment by yaelAmitay** [comment]
OK I think I can handle this switch. Tell me what is your decision.

**Comment by koralchapnik** [comment]
I also didn't find any problem with Jx-Maps, but I'll check this

**Comment by kapalex** [comment]
I think mostly the lack of support for java fx will be a bother in the future.  Everyone should test it and we will have a discussion next meeting on monday.

**Comment by Kolikant** [comment]
seems to be just as bad, maybe inherently in the usage of google maps api outside of android :\

**Comment by Kolikant** [comment]
it seems that your idea (i don't remember which of thread it was) of saving only the mapview works.
it breaks down the coupling.
it might be a good idea to have a library of common features now that the coupling can be broken.

if we are okay with keeping jxMaps I'll take that initiative. I think both API's are pretty bad, better the devil you know

**Comment by kapalex** [comment]
The main point I think we should discuss is javafx vs swing
I've contacted the company about the javafx library being broken but until they answer we don't know if we can get it to work together
if not that means we will be creating our gui with swing which is quite aweful
We'll talk about it tomrrow
I do like your idea about creating such a library

**Comment by yaelAmitay** [comment]
What's the problem with swing?
edit:
Never mind I read about it. I now understand why you tend to replace JxMaps. and as I said before i'm fine with that.

**Comment by Kolikant** [comment]
in accordance to the meeting today we agreed to stick with JxMaps, and create a class for common functionality #94
