### ISSUE TITLE
best reviews taking pinned reviews to account

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#93]
tried to create the filtering using the BestReviews class, but noticed it doesn't take a location to account but rather a list of reviews, which is fine, but it seems not to take the pinned reiews to account. 
also, if it has popular functionality, wouldn't it be better to make the methods static? regardless, I am using it as is meant right now.

**Comment by koralchapnik** [comment]
you should use the method getRating() of Location class, it considers the pinned reviews and also uses the bestReviews class.
