### ISSUE TITLE
create class for frequently used methods with JxMaps

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#94]
we found a way to de-couple the usage of Jx-maps.
need a class to gather all the JxMaps functionality that we are interested in

**Comment by Kolikant** [comment]
tell me what functionality you need from JxMaps 
@koralchapnik  @KaplanAlexander

**Comment by koralchapnik** [comment]
Later on today I'll add the functionality of the nearby places

**Comment by kapalex** [comment]
Please note, MapView should be disposed at the end of use. otherwise it is in its way a memory leak
(`.dispose()`)

**Comment by kapalex** [comment]
Probably only relevant for testing, as we want to keep it up while the app is running

**Comment by Kolikant** [comment]
Added it
Cheers mate

**Comment by kapalex** [comment]
I think the right place for this class is in the mapmanagement package, and not in what used to be the jxmaps examples package, can I move it?

**Comment by kapalex** [comment]
In addition just noticed the mapview has a `waitready()` function, which makes the additional functionality of waitablemap redundant

**Comment by Kolikant** [comment]
both good points.
writableMap still exists though as to contain usage of functionality

**Comment by yaelAmitay** [comment]
why is this class abstract?

**Comment by Kolikant** [comment]
Its suppoused to aggregate the functionality needed for jxmaps, same as databasemander or usermanager only contain finctionality


For an example of using this class look at search test or on application

If you need anymore jxmaps functionality, tell me or out it here as well

**Comment by Kolikant** [comment]
its been a while and no one asked for more functionality so I'm closing it, open a separate issue if more functionality is needed in the future
