### ISSUE TITLE
users design, by privilege rings

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#95]
in accordance to the meeting today, the implementation of the priviliges of users would be as suggested by Arthur here #67 
the class of Authenticated User now passes under his juresdiction. 

UserManagement needs to change in accordance

**Comment by ArthurSap** [comment]
Have we decided to have an interface and a single implementation or just the implementation?

**Comment by Kolikant** [comment]
Leave the interface in case of future changes, doesn't change much

**Comment by Kolikant** [comment]
implementation looks good, just not sure if "setPrivilige" should exist or not, but not critical.
should be easy enough to fix userManager to fit the new implementation

**Comment by ArthurSap** [comment]
Automatic getters and setters, thought might as well leave it there.
Do you think we need more methods to User class?
where should we implement Pin and unPin?

**Comment by Kolikant** [comment]
now that we changed the implementation to rings, all methods would recieve user's ass input and act through the rings. pin and unpin should be in Location or Location Manager (probably location)

**Comment by ArthurSap** [comment]
Should we change/add those ourselves or leave it to others?

**Comment by Kolikant** [comment]
I think you should add the methods that used to be in admin, no need to wait for someone to need the methods
