### ISSUE TITLE
Rating out of score's boundaries

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#97]
Review's constructor gets a rating.
the question is what if the rating exceeds the Score's bounds ? 
to raise an exception in Review's constructor (which means using try-catch statement in each creation of review or keep throwing the exception) or to show the user some pop-up window which tells him the bounds of the rating and asking him insert another rating ? 
What do you think ? 
@assaflu @ArthurSap @yaelAmitay @KaplanAlexander @Kolikant

**Comment by kapalex** [comment]
This will only be an issue if the user can actually enter a number.
Assuming the GUI will offer an option similar to what google play offers for rating an app (you mark between 1 and 5 stars) then the option of wrong rating won't be an issue.
So I think the best course of action will be to either throw some run-time exception (specifically run-time so someone using the constructor doesn't need to check it) or just fix the rating automatically (>max turns to max, <min turns to min) and ignore the error

**Comment by koralchapnik** [comment]
I think that the Google play idea is great.
but we need to change the Max Score bound from 10 to lower one, like 5

**Comment by koralchapnik** [comment]
changed the relevant code.
the GUI is responsible for showing the score's range like in google play.
