### ISSUE TITLE
failed test of addReview in Location class

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#99]
in Location Class there is method of addReview which calls the code : 
```JAVA
ReviewManager.uploadReview(r);
```
when trying to execute the next code:
```JAVA
Location l = new Coordinates(c);
Review r1 = new Review(l, Score.getMinScore(), "very unaccessible place!", u1);
l.addReview(r1);
```
the adding of r1 raises the exception.
does someone who interacted with the parser knows why ? @assaflu @Kolikant @KaplanAlexander

**Comment by Kolikant** [comment]
You cant save and non primitive classes intheparser, i reccomend parsing it to string and back

**Comment by Kolikant** [comment]
Or int, ot ehatever seems right

**Comment by kapalex** [comment]
@Kolikant but the functions uploading are in change of it, so probably @assaflu ?

**Comment by koralchapnik** [comment]
but that is what @assaflu did in the uploadReview method : 
```JAVA
public static void uploadReview(Review r) throws ParseException{
		Map<String, Object> m = new HashMap<String,Object>();
		m.put("user", r.getUser());
		m.put("location", new ParseGeoPoint(r.getLocation().getCoordinates().getLat(),r.getLocation().getCoordinates().getLng()));
		m.put("rating",r.getRating().getScore());
		m.put("comment",r.getComment());
		ParseObject p = DatabaseManager.putValue("Review",m); 
	}
```

**Comment by kapalex** [comment]
Can you add the full stack trace?

**Comment by koralchapnik** [comment]
that's what I ran : 
```JAVA
	@BeforeClass
	public static void init(){
		User u1 = new AuthenticatedUser("Koral","123","");
		User u2 = new AuthenticatedUser("Koral2","123","");
		User u3 = new Admin("Simba", "355", "");
		LatLng c = new LatLng(39.750307, -104.999472);
		l = new Coordinates(c);
		r1 = new Review(l, Score.getMinScore(), "very unaccessible place!", u1);
		r2 = new Review(l, 5, "middle accessibility level", u2);
		r3 = new Review(l, Score.getMaxScore(), "high accessibility level", u3);
		try {
			l.addReview(r1);
			l.addReview(r2);
			l.addReview(r3);
		} catch (ParseException e) {
			fail("shouldn't failed!");
		}
		
	}
	
```
and it get to the fail

**Comment by Kolikant** [comment]
Look at location field, seems he save a latlong, no? Maybe converting that to two ints will help

**Comment by Kolikant** [comment]
Oh

**Comment by Kolikant** [comment]
Authenticated user and adminclasses are deprecated,
Use userimpl instead

**Comment by koralchapnik** [comment]
That is not the problem..
I used it in another test and it made no problems

**Comment by kapalex** [comment]
again, stack trace would really help..

**Comment by Kolikant** [comment]
Seconded

**Comment by koralchapnik** [comment]
one sec

**Comment by koralchapnik** [comment]
![image](https://cloud.githubusercontent.com/assets/23156121/21497682/655fc578-cc2f-11e6-8e3e-6fba959215cd.png)

**Comment by koralchapnik** [comment]
![image](https://cloud.githubusercontent.com/assets/23156121/21497707/93c3c52c-cc2f-11e6-95b5-f2ab70083e00.png)

the marked row is the problematic one

**Comment by kapalex** [comment]
Same problem as the test yesterday
you don't init the database vefore using it
`DatabaseManager.initialize()`
In the before class of the tests

**Comment by kapalex** [comment]
This will only need to be called once in the actual app (in the main) but for tests each test class needs to

**Comment by koralchapnik** [comment]
Ok,
Thanks
